from dataclasses import dataclass, field
from BasicNoitaTypes import NoitaBool
from BasicNoitaTypes import NoitaString
from BasicNoitaTypes import NoitaInt
from BasicNoitaTypes import NoitaFloat
from GeneratedClasses.ConfigGun import ConfigGun
from GeneratedClasses.ConfigGunActionInfo import ConfigGunActionInfo

from NoitaStream import NoitaStream
@dataclass
class AbilityComponent:
    Deleted:NoitaBool = field(default_factory=NoitaBool)
    Enabled:NoitaBool = field(default_factory=NoitaBool)
    Tags:NoitaString = field(default_factory=NoitaString)
    cooldown_frames:NoitaInt = field(default_factory=NoitaInt)
    entity_file:NoitaString = field(default_factory=NoitaString)
    sprite_file:NoitaString = field(default_factory=NoitaString)
    entity_count:NoitaInt = field(default_factory=NoitaInt)
    never_reload:NoitaBool = field(default_factory=NoitaBool)
    reload_time_frames:NoitaInt = field(default_factory=NoitaInt)
    mana:NoitaFloat = field(default_factory=NoitaFloat)
    mana_max:NoitaFloat = field(default_factory=NoitaFloat)
    mana_charge_speed:NoitaFloat = field(default_factory=NoitaFloat)
    rotate_in_hand:NoitaBool = field(default_factory=NoitaBool)
    rotate_in_hand_amount:NoitaFloat = field(default_factory=NoitaFloat)
    rotate_hand_amount:NoitaFloat = field(default_factory=NoitaFloat)
    fast_projectile:NoitaBool = field(default_factory=NoitaBool)
    swim_propel_amount:NoitaFloat = field(default_factory=NoitaFloat)
    max_charged_actions:NoitaInt = field(default_factory=NoitaInt)
    charge_wait_frames:NoitaInt = field(default_factory=NoitaInt)
    item_recoil_recovery_speed:NoitaFloat = field(default_factory=NoitaFloat)
    item_recoil_max:NoitaFloat = field(default_factory=NoitaFloat)
    item_recoil_offset_coeff:NoitaFloat = field(default_factory=NoitaFloat)
    item_recoil_rotation_coeff:NoitaFloat = field(default_factory=NoitaFloat)
    base_item_file:NoitaString = field(default_factory=NoitaString)
    use_entity_file_as_projectile_info_proxy:NoitaBool = field(default_factory=NoitaBool)
    click_to_use:NoitaBool = field(default_factory=NoitaBool)
    stat_times_player_has_shot:NoitaInt = field(default_factory=NoitaInt)
    stat_times_player_has_edited:NoitaInt = field(default_factory=NoitaInt)
    shooting_reduces_amount_in_inventory:NoitaBool = field(default_factory=NoitaBool)
    throw_as_item:NoitaBool = field(default_factory=NoitaBool)
    simulate_throw_as_item:NoitaBool = field(default_factory=NoitaBool)
    max_amount_in_inventory:NoitaInt = field(default_factory=NoitaInt)
    amount_in_inventory:NoitaInt = field(default_factory=NoitaInt)
    drop_as_item_on_death:NoitaBool = field(default_factory=NoitaBool)
    ui_name:NoitaString = field(default_factory=NoitaString)
    use_gun_script:NoitaBool = field(default_factory=NoitaBool)
    is_petris_gun:NoitaBool = field(default_factory=NoitaBool)
    gun_config:ConfigGun = field(default_factory=ConfigGun)
    gunaction_config:ConfigGunActionInfo = field(default_factory=ConfigGunActionInfo)
    gun_level:NoitaInt = field(default_factory=NoitaInt)
    add_these_child_actions:NoitaString = field(default_factory=NoitaString)
    current_slot_durability:NoitaInt = field(default_factory=NoitaInt)
    slot_consumption_function:NoitaString = field(default_factory=NoitaString)
    mNextFrameUsable:NoitaInt = field(default_factory=NoitaInt)
    mCastDelayStartFrame:NoitaInt = field(default_factory=NoitaInt)
    mReloadFramesLeft:NoitaInt = field(default_factory=NoitaInt)
    mReloadNextFrameUsable:NoitaInt = field(default_factory=NoitaInt)
    mChargeCount:NoitaInt = field(default_factory=NoitaInt)
    mIsInitialized:NoitaBool = field(default_factory=NoitaBool)
    
    def Read(self, s:NoitaStream):
        self.Deleted.Read(s)
        self.Enabled.Read(s)
        self.Tags.Read(s)
        self.cooldown_frames.Read(s)
        self.entity_file.Read(s)
        self.sprite_file.Read(s)
        self.entity_count.Read(s)
        self.never_reload.Read(s)
        self.reload_time_frames.Read(s)
        self.mana.Read(s)
        self.mana_max.Read(s)
        self.mana_charge_speed.Read(s)
        self.rotate_in_hand.Read(s)
        self.rotate_in_hand_amount.Read(s)
        self.rotate_hand_amount.Read(s)
        self.fast_projectile.Read(s)
        self.swim_propel_amount.Read(s)
        self.max_charged_actions.Read(s)
        self.charge_wait_frames.Read(s)
        self.item_recoil_recovery_speed.Read(s)
        self.item_recoil_max.Read(s)
        self.item_recoil_offset_coeff.Read(s)
        self.item_recoil_rotation_coeff.Read(s)
        self.base_item_file.Read(s)
        self.use_entity_file_as_projectile_info_proxy.Read(s)
        self.click_to_use.Read(s)
        self.stat_times_player_has_shot.Read(s)
        self.stat_times_player_has_edited.Read(s)
        self.shooting_reduces_amount_in_inventory.Read(s)
        self.throw_as_item.Read(s)
        self.simulate_throw_as_item.Read(s)
        self.max_amount_in_inventory.Read(s)
        self.amount_in_inventory.Read(s)
        self.drop_as_item_on_death.Read(s)
        self.ui_name.Read(s)
        self.use_gun_script.Read(s)
        self.is_petris_gun.Read(s)
        self.gun_config.Read(s)
        self.gunaction_config.Read(s)
        self.gun_level.Read(s)
        self.add_these_child_actions.Read(s)
        self.current_slot_durability.Read(s)
        self.slot_consumption_function.Read(s)
        self.mNextFrameUsable.Read(s)
        self.mCastDelayStartFrame.Read(s)
        self.mReloadFramesLeft.Read(s)
        self.mReloadNextFrameUsable.Read(s)
        self.mChargeCount.Read(s)
        self.mIsInitialized.Read(s)
    
    def Write(self, s:NoitaStream):
        self.Deleted.Write(s)
        self.Enabled.Write(s)
        self.Tags.Write(s)
        self.cooldown_frames.Write(s)
        self.entity_file.Write(s)
        self.sprite_file.Write(s)
        self.entity_count.Write(s)
        self.never_reload.Write(s)
        self.reload_time_frames.Write(s)
        self.mana.Write(s)
        self.mana_max.Write(s)
        self.mana_charge_speed.Write(s)
        self.rotate_in_hand.Write(s)
        self.rotate_in_hand_amount.Write(s)
        self.rotate_hand_amount.Write(s)
        self.fast_projectile.Write(s)
        self.swim_propel_amount.Write(s)
        self.max_charged_actions.Write(s)
        self.charge_wait_frames.Write(s)
        self.item_recoil_recovery_speed.Write(s)
        self.item_recoil_max.Write(s)
        self.item_recoil_offset_coeff.Write(s)
        self.item_recoil_rotation_coeff.Write(s)
        self.base_item_file.Write(s)
        self.use_entity_file_as_projectile_info_proxy.Write(s)
        self.click_to_use.Write(s)
        self.stat_times_player_has_shot.Write(s)
        self.stat_times_player_has_edited.Write(s)
        self.shooting_reduces_amount_in_inventory.Write(s)
        self.throw_as_item.Write(s)
        self.simulate_throw_as_item.Write(s)
        self.max_amount_in_inventory.Write(s)
        self.amount_in_inventory.Write(s)
        self.drop_as_item_on_death.Write(s)
        self.ui_name.Write(s)
        self.use_gun_script.Write(s)
        self.is_petris_gun.Write(s)
        self.gun_config.Write(s)
        self.gunaction_config.Write(s)
        self.gun_level.Write(s)
        self.add_these_child_actions.Write(s)
        self.current_slot_durability.Write(s)
        self.slot_consumption_function.Write(s)
        self.mNextFrameUsable.Write(s)
        self.mCastDelayStartFrame.Write(s)
        self.mReloadFramesLeft.Write(s)
        self.mReloadNextFrameUsable.Write(s)
        self.mChargeCount.Write(s)
        self.mIsInitialized.Write(s)

