from dataclasses import dataclass, field
from BasicNoitaTypes import NoitaBool
from BasicNoitaTypes import NoitaString
from BasicNoitaTypes import NoitaInt
from BasicNoitaTypes import NoitaFloat

from NoitaStream import NoitaStream
@dataclass
class AIAttackComponent:
    Deleted:NoitaBool = field(default_factory=NoitaBool)
    Enabled:NoitaBool = field(default_factory=NoitaBool)
    Tags:NoitaString = field(default_factory=NoitaString)
    use_probability:NoitaInt = field(default_factory=NoitaInt)
    min_distance:NoitaFloat = field(default_factory=NoitaFloat)
    max_distance:NoitaFloat = field(default_factory=NoitaFloat)
    angular_range_deg:NoitaFloat = field(default_factory=NoitaFloat)
    state_duration_frames:NoitaInt = field(default_factory=NoitaInt)
    frames_between:NoitaInt = field(default_factory=NoitaInt)
    frames_between_global:NoitaInt = field(default_factory=NoitaInt)
    animation_name:NoitaString = field(default_factory=NoitaString)
    attack_landing_ranged_enabled:NoitaBool = field(default_factory=NoitaBool)
    attack_ranged_action_frame:NoitaInt = field(default_factory=NoitaInt)
    attack_ranged_offset_x:NoitaFloat = field(default_factory=NoitaFloat)
    attack_ranged_offset_y:NoitaFloat = field(default_factory=NoitaFloat)
    attack_ranged_root_offset_x:NoitaFloat = field(default_factory=NoitaFloat)
    attack_ranged_root_offset_y:NoitaFloat = field(default_factory=NoitaFloat)
    attack_ranged_use_message:NoitaBool = field(default_factory=NoitaBool)
    attack_ranged_predict:NoitaBool = field(default_factory=NoitaBool)
    attack_ranged_entity_file:NoitaString = field(default_factory=NoitaString)
    attack_ranged_entity_count_min:NoitaInt = field(default_factory=NoitaInt)
    attack_ranged_entity_count_max:NoitaInt = field(default_factory=NoitaInt)
    attack_ranged_use_laser_sight:NoitaBool = field(default_factory=NoitaBool)
    attack_ranged_aim_rotation_enabled:NoitaBool = field(default_factory=NoitaBool)
    attack_ranged_aim_rotation_speed:NoitaFloat = field(default_factory=NoitaFloat)
    attack_ranged_aim_rotation_shooting_ok_angle_deg:NoitaFloat = field(default_factory=NoitaFloat)
    
    def Read(self, s:NoitaStream):
        self.Deleted.Read(s)
        self.Enabled.Read(s)
        self.Tags.Read(s)
        self.use_probability.Read(s)
        self.min_distance.Read(s)
        self.max_distance.Read(s)
        self.angular_range_deg.Read(s)
        self.state_duration_frames.Read(s)
        self.frames_between.Read(s)
        self.frames_between_global.Read(s)
        self.animation_name.Read(s)
        self.attack_landing_ranged_enabled.Read(s)
        self.attack_ranged_action_frame.Read(s)
        self.attack_ranged_offset_x.Read(s)
        self.attack_ranged_offset_y.Read(s)
        self.attack_ranged_root_offset_x.Read(s)
        self.attack_ranged_root_offset_y.Read(s)
        self.attack_ranged_use_message.Read(s)
        self.attack_ranged_predict.Read(s)
        self.attack_ranged_entity_file.Read(s)
        self.attack_ranged_entity_count_min.Read(s)
        self.attack_ranged_entity_count_max.Read(s)
        self.attack_ranged_use_laser_sight.Read(s)
        self.attack_ranged_aim_rotation_enabled.Read(s)
        self.attack_ranged_aim_rotation_speed.Read(s)
        self.attack_ranged_aim_rotation_shooting_ok_angle_deg.Read(s)
    
    def Write(self, s:NoitaStream):
        self.Deleted.Write(s)
        self.Enabled.Write(s)
        self.Tags.Write(s)
        self.use_probability.Write(s)
        self.min_distance.Write(s)
        self.max_distance.Write(s)
        self.angular_range_deg.Write(s)
        self.state_duration_frames.Write(s)
        self.frames_between.Write(s)
        self.frames_between_global.Write(s)
        self.animation_name.Write(s)
        self.attack_landing_ranged_enabled.Write(s)
        self.attack_ranged_action_frame.Write(s)
        self.attack_ranged_offset_x.Write(s)
        self.attack_ranged_offset_y.Write(s)
        self.attack_ranged_root_offset_x.Write(s)
        self.attack_ranged_root_offset_y.Write(s)
        self.attack_ranged_use_message.Write(s)
        self.attack_ranged_predict.Write(s)
        self.attack_ranged_entity_file.Write(s)
        self.attack_ranged_entity_count_min.Write(s)
        self.attack_ranged_entity_count_max.Write(s)
        self.attack_ranged_use_laser_sight.Write(s)
        self.attack_ranged_aim_rotation_enabled.Write(s)
        self.attack_ranged_aim_rotation_speed.Write(s)
        self.attack_ranged_aim_rotation_shooting_ok_angle_deg.Write(s)

