from dataclasses import dataclass, field
from BasicNoitaTypes import NoitaBool
from BasicNoitaTypes import NoitaString
from BasicNoitaTypes import NoitaInt
from BasicNoitaTypes import NoitaFloat
from GeneratedClasses.ConfigExplosion import ConfigExplosion
from BasicNoitaTypes import NoitaLensValue
from BasicNoitaTypes import NoitaInt

from NoitaStream import NoitaStream
@dataclass
class AnimalAIComponent:
    Deleted:NoitaBool = field(default_factory=NoitaBool)
    Enabled:NoitaBool = field(default_factory=NoitaBool)
    Tags:NoitaString = field(default_factory=NoitaString)
    ai_state:NoitaInt = field(default_factory=NoitaInt)
    ai_state_timer:NoitaInt = field(default_factory=NoitaInt)
    keep_state_alive_when_enabled:NoitaBool = field(default_factory=NoitaBool)
    preferred_job:NoitaString = field(default_factory=NoitaString)
    escape_if_damaged_probability:NoitaInt = field(default_factory=NoitaInt)
    attack_if_damaged_probability:NoitaInt = field(default_factory=NoitaInt)
    eye_offset_x:NoitaInt = field(default_factory=NoitaInt)
    eye_offset_y:NoitaInt = field(default_factory=NoitaInt)
    attack_only_if_attacked:NoitaBool = field(default_factory=NoitaBool)
    dont_counter_attack_own_herd:NoitaBool = field(default_factory=NoitaBool)
    creature_detection_range_x:NoitaFloat = field(default_factory=NoitaFloat)
    creature_detection_range_y:NoitaFloat = field(default_factory=NoitaFloat)
    creature_detection_angular_range_deg:NoitaFloat = field(default_factory=NoitaFloat)
    creature_detection_check_every_x_frames:NoitaInt = field(default_factory=NoitaInt)
    max_distance_to_cam_to_start_hunting:NoitaFloat = field(default_factory=NoitaFloat)
    pathfinding_max_depth_no_target:NoitaInt = field(default_factory=NoitaInt)
    pathfinding_max_depth_has_target:NoitaInt = field(default_factory=NoitaInt)
    aggressiveness_min:NoitaFloat = field(default_factory=NoitaFloat)
    aggressiveness_max:NoitaFloat = field(default_factory=NoitaFloat)
    tries_to_ranged_attack_friends:NoitaBool = field(default_factory=NoitaBool)
    attack_melee_enabled:NoitaBool = field(default_factory=NoitaBool)
    attack_dash_enabled:NoitaBool = field(default_factory=NoitaBool)
    attack_landing_ranged_enabled:NoitaBool = field(default_factory=NoitaBool)
    attack_ranged_enabled:NoitaBool = field(default_factory=NoitaBool)
    attack_knockback_multiplier:NoitaFloat = field(default_factory=NoitaFloat)
    is_static_turret:NoitaBool = field(default_factory=NoitaBool)
    attack_melee_max_distance:NoitaInt = field(default_factory=NoitaInt)
    attack_melee_action_frame:NoitaInt = field(default_factory=NoitaInt)
    attack_melee_frames_between:NoitaInt = field(default_factory=NoitaInt)
    attack_melee_damage_min:NoitaFloat = field(default_factory=NoitaFloat)
    attack_melee_damage_max:NoitaFloat = field(default_factory=NoitaFloat)
    attack_melee_impulse_vector_x:NoitaFloat = field(default_factory=NoitaFloat)
    attack_melee_impulse_vector_y:NoitaFloat = field(default_factory=NoitaFloat)
    attack_melee_impulse_multiplier:NoitaFloat = field(default_factory=NoitaFloat)
    attack_melee_offset_x:NoitaFloat = field(default_factory=NoitaFloat)
    attack_melee_offset_y:NoitaFloat = field(default_factory=NoitaFloat)
    attack_melee_finish_enabled:NoitaBool = field(default_factory=NoitaBool)
    attack_melee_finish_config_explosion:ConfigExplosion = field(default_factory=ConfigExplosion)
    attack_melee_finish_action_frame:NoitaInt = field(default_factory=NoitaInt)
    attack_dash_distance:NoitaFloat = field(default_factory=NoitaFloat)
    attack_dash_frames_between:NoitaInt = field(default_factory=NoitaInt)
    attack_dash_damage:NoitaFloat = field(default_factory=NoitaFloat)
    attack_dash_speed:NoitaFloat = field(default_factory=NoitaFloat)
    attack_dash_lob:NoitaFloat = field(default_factory=NoitaFloat)
    attack_ranged_min_distance:NoitaFloat = field(default_factory=NoitaFloat)
    attack_ranged_max_distance:NoitaFloat = field(default_factory=NoitaFloat)
    attack_ranged_action_frame:NoitaInt = field(default_factory=NoitaInt)
    attack_ranged_frames_between:NoitaLensValue = field(default_factory=lambda: NoitaLensValue(NoitaInt))
    attack_ranged_offset_x:NoitaFloat = field(default_factory=NoitaFloat)
    attack_ranged_offset_y:NoitaFloat = field(default_factory=NoitaFloat)
    attack_ranged_use_message:NoitaBool = field(default_factory=NoitaBool)
    attack_ranged_predict:NoitaBool = field(default_factory=NoitaBool)
    attack_ranged_entity_file:NoitaString = field(default_factory=NoitaString)
    attack_ranged_entity_count_min:NoitaInt = field(default_factory=NoitaInt)
    attack_ranged_entity_count_max:NoitaInt = field(default_factory=NoitaInt)
    attack_ranged_use_laser_sight:NoitaBool = field(default_factory=NoitaBool)
    attack_ranged_laser_sight_beam_kind:NoitaBool = field(default_factory=NoitaBool)
    attack_ranged_aim_rotation_enabled:NoitaBool = field(default_factory=NoitaBool)
    attack_ranged_aim_rotation_speed:NoitaFloat = field(default_factory=NoitaFloat)
    attack_ranged_aim_rotation_shooting_ok_angle_deg:NoitaFloat = field(default_factory=NoitaFloat)
    attack_ranged_state_duration_frames:NoitaInt = field(default_factory=NoitaInt)
    hide_from_prey:NoitaBool = field(default_factory=NoitaBool)
    hide_from_prey_target_distance:NoitaFloat = field(default_factory=NoitaFloat)
    hide_from_prey_time:NoitaInt = field(default_factory=NoitaInt)
    food_material:NoitaInt = field(default_factory=NoitaInt)
    food_particle_effect_material:NoitaInt = field(default_factory=NoitaInt)
    food_eating_create_particles:NoitaBool = field(default_factory=NoitaBool)
    eating_area_radius_x:NoitaInt = field(default_factory=NoitaInt)
    eating_area_radius_y:NoitaInt = field(default_factory=NoitaInt)
    mouth_offset_x:NoitaInt = field(default_factory=NoitaInt)
    mouth_offset_y:NoitaInt = field(default_factory=NoitaInt)
    defecates_and_pees:NoitaBool = field(default_factory=NoitaBool)
    butt_offset_x:NoitaInt = field(default_factory=NoitaInt)
    butt_offset_y:NoitaInt = field(default_factory=NoitaInt)
    pee_velocity_x:NoitaFloat = field(default_factory=NoitaFloat)
    pee_velocity_y:NoitaFloat = field(default_factory=NoitaFloat)
    needs_food:NoitaBool = field(default_factory=NoitaBool)
    sense_creatures:NoitaBool = field(default_factory=NoitaBool)
    sense_creatures_through_walls:NoitaBool = field(default_factory=NoitaBool)
    can_fly:NoitaBool = field(default_factory=NoitaBool)
    can_walk:NoitaBool = field(default_factory=NoitaBool)
    path_distance_to_target_node_to_turn_around:NoitaInt = field(default_factory=NoitaInt)
    path_cleanup_explosion_radius:NoitaFloat = field(default_factory=NoitaFloat)
    max_distance_to_move_from_home:NoitaFloat = field(default_factory=NoitaFloat)
    mAggression:NoitaLensValue = field(default_factory=lambda: NoitaLensValue(NoitaFloat))
    
    def Read(self, s:NoitaStream):
        self.Deleted.Read(s)
        self.Enabled.Read(s)
        self.Tags.Read(s)
        self.ai_state.Read(s)
        self.ai_state_timer.Read(s)
        self.keep_state_alive_when_enabled.Read(s)
        self.preferred_job.Read(s)
        self.escape_if_damaged_probability.Read(s)
        self.attack_if_damaged_probability.Read(s)
        self.eye_offset_x.Read(s)
        self.eye_offset_y.Read(s)
        self.attack_only_if_attacked.Read(s)
        self.dont_counter_attack_own_herd.Read(s)
        self.creature_detection_range_x.Read(s)
        self.creature_detection_range_y.Read(s)
        self.creature_detection_angular_range_deg.Read(s)
        self.creature_detection_check_every_x_frames.Read(s)
        self.max_distance_to_cam_to_start_hunting.Read(s)
        self.pathfinding_max_depth_no_target.Read(s)
        self.pathfinding_max_depth_has_target.Read(s)
        self.aggressiveness_min.Read(s)
        self.aggressiveness_max.Read(s)
        self.tries_to_ranged_attack_friends.Read(s)
        self.attack_melee_enabled.Read(s)
        self.attack_dash_enabled.Read(s)
        self.attack_landing_ranged_enabled.Read(s)
        self.attack_ranged_enabled.Read(s)
        self.attack_knockback_multiplier.Read(s)
        self.is_static_turret.Read(s)
        self.attack_melee_max_distance.Read(s)
        self.attack_melee_action_frame.Read(s)
        self.attack_melee_frames_between.Read(s)
        self.attack_melee_damage_min.Read(s)
        self.attack_melee_damage_max.Read(s)
        self.attack_melee_impulse_vector_x.Read(s)
        self.attack_melee_impulse_vector_y.Read(s)
        self.attack_melee_impulse_multiplier.Read(s)
        self.attack_melee_offset_x.Read(s)
        self.attack_melee_offset_y.Read(s)
        self.attack_melee_finish_enabled.Read(s)
        self.attack_melee_finish_config_explosion.Read(s)
        self.attack_melee_finish_action_frame.Read(s)
        self.attack_dash_distance.Read(s)
        self.attack_dash_frames_between.Read(s)
        self.attack_dash_damage.Read(s)
        self.attack_dash_speed.Read(s)
        self.attack_dash_lob.Read(s)
        self.attack_ranged_min_distance.Read(s)
        self.attack_ranged_max_distance.Read(s)
        self.attack_ranged_action_frame.Read(s)
        self.attack_ranged_frames_between.Read(s)
        self.attack_ranged_offset_x.Read(s)
        self.attack_ranged_offset_y.Read(s)
        self.attack_ranged_use_message.Read(s)
        self.attack_ranged_predict.Read(s)
        self.attack_ranged_entity_file.Read(s)
        self.attack_ranged_entity_count_min.Read(s)
        self.attack_ranged_entity_count_max.Read(s)
        self.attack_ranged_use_laser_sight.Read(s)
        self.attack_ranged_laser_sight_beam_kind.Read(s)
        self.attack_ranged_aim_rotation_enabled.Read(s)
        self.attack_ranged_aim_rotation_speed.Read(s)
        self.attack_ranged_aim_rotation_shooting_ok_angle_deg.Read(s)
        self.attack_ranged_state_duration_frames.Read(s)
        self.hide_from_prey.Read(s)
        self.hide_from_prey_target_distance.Read(s)
        self.hide_from_prey_time.Read(s)
        self.food_material.Read(s)
        self.food_particle_effect_material.Read(s)
        self.food_eating_create_particles.Read(s)
        self.eating_area_radius_x.Read(s)
        self.eating_area_radius_y.Read(s)
        self.mouth_offset_x.Read(s)
        self.mouth_offset_y.Read(s)
        self.defecates_and_pees.Read(s)
        self.butt_offset_x.Read(s)
        self.butt_offset_y.Read(s)
        self.pee_velocity_x.Read(s)
        self.pee_velocity_y.Read(s)
        self.needs_food.Read(s)
        self.sense_creatures.Read(s)
        self.sense_creatures_through_walls.Read(s)
        self.can_fly.Read(s)
        self.can_walk.Read(s)
        self.path_distance_to_target_node_to_turn_around.Read(s)
        self.path_cleanup_explosion_radius.Read(s)
        self.max_distance_to_move_from_home.Read(s)
        self.mAggression.Read(s)
    
    def Write(self, s:NoitaStream):
        self.Deleted.Write(s)
        self.Enabled.Write(s)
        self.Tags.Write(s)
        self.ai_state.Write(s)
        self.ai_state_timer.Write(s)
        self.keep_state_alive_when_enabled.Write(s)
        self.preferred_job.Write(s)
        self.escape_if_damaged_probability.Write(s)
        self.attack_if_damaged_probability.Write(s)
        self.eye_offset_x.Write(s)
        self.eye_offset_y.Write(s)
        self.attack_only_if_attacked.Write(s)
        self.dont_counter_attack_own_herd.Write(s)
        self.creature_detection_range_x.Write(s)
        self.creature_detection_range_y.Write(s)
        self.creature_detection_angular_range_deg.Write(s)
        self.creature_detection_check_every_x_frames.Write(s)
        self.max_distance_to_cam_to_start_hunting.Write(s)
        self.pathfinding_max_depth_no_target.Write(s)
        self.pathfinding_max_depth_has_target.Write(s)
        self.aggressiveness_min.Write(s)
        self.aggressiveness_max.Write(s)
        self.tries_to_ranged_attack_friends.Write(s)
        self.attack_melee_enabled.Write(s)
        self.attack_dash_enabled.Write(s)
        self.attack_landing_ranged_enabled.Write(s)
        self.attack_ranged_enabled.Write(s)
        self.attack_knockback_multiplier.Write(s)
        self.is_static_turret.Write(s)
        self.attack_melee_max_distance.Write(s)
        self.attack_melee_action_frame.Write(s)
        self.attack_melee_frames_between.Write(s)
        self.attack_melee_damage_min.Write(s)
        self.attack_melee_damage_max.Write(s)
        self.attack_melee_impulse_vector_x.Write(s)
        self.attack_melee_impulse_vector_y.Write(s)
        self.attack_melee_impulse_multiplier.Write(s)
        self.attack_melee_offset_x.Write(s)
        self.attack_melee_offset_y.Write(s)
        self.attack_melee_finish_enabled.Write(s)
        self.attack_melee_finish_config_explosion.Write(s)
        self.attack_melee_finish_action_frame.Write(s)
        self.attack_dash_distance.Write(s)
        self.attack_dash_frames_between.Write(s)
        self.attack_dash_damage.Write(s)
        self.attack_dash_speed.Write(s)
        self.attack_dash_lob.Write(s)
        self.attack_ranged_min_distance.Write(s)
        self.attack_ranged_max_distance.Write(s)
        self.attack_ranged_action_frame.Write(s)
        self.attack_ranged_frames_between.Write(s)
        self.attack_ranged_offset_x.Write(s)
        self.attack_ranged_offset_y.Write(s)
        self.attack_ranged_use_message.Write(s)
        self.attack_ranged_predict.Write(s)
        self.attack_ranged_entity_file.Write(s)
        self.attack_ranged_entity_count_min.Write(s)
        self.attack_ranged_entity_count_max.Write(s)
        self.attack_ranged_use_laser_sight.Write(s)
        self.attack_ranged_laser_sight_beam_kind.Write(s)
        self.attack_ranged_aim_rotation_enabled.Write(s)
        self.attack_ranged_aim_rotation_speed.Write(s)
        self.attack_ranged_aim_rotation_shooting_ok_angle_deg.Write(s)
        self.attack_ranged_state_duration_frames.Write(s)
        self.hide_from_prey.Write(s)
        self.hide_from_prey_target_distance.Write(s)
        self.hide_from_prey_time.Write(s)
        self.food_material.Write(s)
        self.food_particle_effect_material.Write(s)
        self.food_eating_create_particles.Write(s)
        self.eating_area_radius_x.Write(s)
        self.eating_area_radius_y.Write(s)
        self.mouth_offset_x.Write(s)
        self.mouth_offset_y.Write(s)
        self.defecates_and_pees.Write(s)
        self.butt_offset_x.Write(s)
        self.butt_offset_y.Write(s)
        self.pee_velocity_x.Write(s)
        self.pee_velocity_y.Write(s)
        self.needs_food.Write(s)
        self.sense_creatures.Write(s)
        self.sense_creatures_through_walls.Write(s)
        self.can_fly.Write(s)
        self.can_walk.Write(s)
        self.path_distance_to_target_node_to_turn_around.Write(s)
        self.path_cleanup_explosion_radius.Write(s)
        self.max_distance_to_move_from_home.Write(s)
        self.mAggression.Write(s)

