from dataclasses import dataclass, field
from BasicNoitaTypes import NoitaBool
from BasicNoitaTypes import NoitaString
from BasicNoitaTypes import NoitaFloat
from BasicNoitaTypes import NoitaInt

from NoitaStream import NoitaStream
@dataclass
class BossDragonComponent:
    Deleted:NoitaBool = field(default_factory=NoitaBool)
    Enabled:NoitaBool = field(default_factory=NoitaBool)
    Tags:NoitaString = field(default_factory=NoitaString)
    speed:NoitaFloat = field(default_factory=NoitaFloat)
    speed_hunt:NoitaFloat = field(default_factory=NoitaFloat)
    acceleration:NoitaFloat = field(default_factory=NoitaFloat)
    direction_adjust_speed:NoitaFloat = field(default_factory=NoitaFloat)
    direction_adjust_speed_hunt:NoitaFloat = field(default_factory=NoitaFloat)
    gravity:NoitaFloat = field(default_factory=NoitaFloat)
    tail_gravity:NoitaFloat = field(default_factory=NoitaFloat)
    part_distance:NoitaFloat = field(default_factory=NoitaFloat)
    ground_check_offset:NoitaInt = field(default_factory=NoitaInt)
    eat_ground_radius:NoitaFloat = field(default_factory=NoitaFloat)
    eat_ground:NoitaBool = field(default_factory=NoitaBool)
    hitbox_radius:NoitaFloat = field(default_factory=NoitaFloat)
    bite_damage:NoitaFloat = field(default_factory=NoitaFloat)
    target_kill_radius:NoitaFloat = field(default_factory=NoitaFloat)
    target_kill_ragdoll_force:NoitaFloat = field(default_factory=NoitaFloat)
    hunt_box_radius:NoitaFloat = field(default_factory=NoitaFloat)
    random_target_box_radius:NoitaFloat = field(default_factory=NoitaFloat)
    new_hunt_target_check_every:NoitaInt = field(default_factory=NoitaInt)
    new_random_target_check_every:NoitaInt = field(default_factory=NoitaInt)
    jump_cam_shake:NoitaFloat = field(default_factory=NoitaFloat)
    jump_cam_shake_distance:NoitaFloat = field(default_factory=NoitaFloat)
    eat_anim_wait_mult:NoitaFloat = field(default_factory=NoitaFloat)
    projectile_1:NoitaString = field(default_factory=NoitaString)
    projectile_1_count:NoitaInt = field(default_factory=NoitaInt)
    projectile_2:NoitaString = field(default_factory=NoitaString)
    projectile_2_count:NoitaInt = field(default_factory=NoitaInt)
    ragdoll_filename:NoitaString = field(default_factory=NoitaString)
    
    def Read(self, s:NoitaStream):
        self.Deleted.Read(s)
        self.Enabled.Read(s)
        self.Tags.Read(s)
        self.speed.Read(s)
        self.speed_hunt.Read(s)
        self.acceleration.Read(s)
        self.direction_adjust_speed.Read(s)
        self.direction_adjust_speed_hunt.Read(s)
        self.gravity.Read(s)
        self.tail_gravity.Read(s)
        self.part_distance.Read(s)
        self.ground_check_offset.Read(s)
        self.eat_ground_radius.Read(s)
        self.eat_ground.Read(s)
        self.hitbox_radius.Read(s)
        self.bite_damage.Read(s)
        self.target_kill_radius.Read(s)
        self.target_kill_ragdoll_force.Read(s)
        self.hunt_box_radius.Read(s)
        self.random_target_box_radius.Read(s)
        self.new_hunt_target_check_every.Read(s)
        self.new_random_target_check_every.Read(s)
        self.jump_cam_shake.Read(s)
        self.jump_cam_shake_distance.Read(s)
        self.eat_anim_wait_mult.Read(s)
        self.projectile_1.Read(s)
        self.projectile_1_count.Read(s)
        self.projectile_2.Read(s)
        self.projectile_2_count.Read(s)
        self.ragdoll_filename.Read(s)
    
    def Write(self, s:NoitaStream):
        self.Deleted.Write(s)
        self.Enabled.Write(s)
        self.Tags.Write(s)
        self.speed.Write(s)
        self.speed_hunt.Write(s)
        self.acceleration.Write(s)
        self.direction_adjust_speed.Write(s)
        self.direction_adjust_speed_hunt.Write(s)
        self.gravity.Write(s)
        self.tail_gravity.Write(s)
        self.part_distance.Write(s)
        self.ground_check_offset.Write(s)
        self.eat_ground_radius.Write(s)
        self.eat_ground.Write(s)
        self.hitbox_radius.Write(s)
        self.bite_damage.Write(s)
        self.target_kill_radius.Write(s)
        self.target_kill_ragdoll_force.Write(s)
        self.hunt_box_radius.Write(s)
        self.random_target_box_radius.Write(s)
        self.new_hunt_target_check_every.Write(s)
        self.new_random_target_check_every.Write(s)
        self.jump_cam_shake.Write(s)
        self.jump_cam_shake_distance.Write(s)
        self.eat_anim_wait_mult.Write(s)
        self.projectile_1.Write(s)
        self.projectile_1_count.Write(s)
        self.projectile_2.Write(s)
        self.projectile_2_count.Write(s)
        self.ragdoll_filename.Write(s)

