from dataclasses import dataclass, field
from BasicNoitaTypes import NoitaBool
from BasicNoitaTypes import NoitaString
from BasicNoitaTypes import NoitaLensValue
from BasicNoitaTypes import NoitaFloat
from BasicNoitaTypes import NoitaInt

from NoitaStream import NoitaStream
@dataclass
class CharacterPlatformingComponent:
    Deleted:NoitaBool = field(default_factory=NoitaBool)
    Enabled:NoitaBool = field(default_factory=NoitaBool)
    Tags:NoitaString = field(default_factory=NoitaString)
    velocity_min_x:NoitaLensValue = field(default_factory=lambda: NoitaLensValue(NoitaFloat))
    velocity_max_x:NoitaLensValue = field(default_factory=lambda: NoitaLensValue(NoitaFloat))
    velocity_min_y:NoitaLensValue = field(default_factory=lambda: NoitaLensValue(NoitaFloat))
    velocity_max_y:NoitaLensValue = field(default_factory=lambda: NoitaLensValue(NoitaFloat))
    run_velocity:NoitaLensValue = field(default_factory=lambda: NoitaLensValue(NoitaFloat))
    fly_velocity_x:NoitaLensValue = field(default_factory=lambda: NoitaLensValue(NoitaFloat))
    jump_velocity_x:NoitaFloat = field(default_factory=NoitaFloat)
    jump_velocity_y:NoitaFloat = field(default_factory=NoitaFloat)
    jump_keydown_buffer:NoitaInt = field(default_factory=NoitaInt)
    fly_speed_max_up:NoitaLensValue = field(default_factory=lambda: NoitaLensValue(NoitaFloat))
    fly_speed_max_down:NoitaLensValue = field(default_factory=lambda: NoitaLensValue(NoitaFloat))
    fly_speed_mult:NoitaFloat = field(default_factory=NoitaFloat)
    fly_speed_change_spd:NoitaFloat = field(default_factory=NoitaFloat)
    fly_model_player:NoitaBool = field(default_factory=NoitaBool)
    fly_smooth_y:NoitaBool = field(default_factory=NoitaBool)
    accel_x:NoitaFloat = field(default_factory=NoitaFloat)
    accel_x_air:NoitaFloat = field(default_factory=NoitaFloat)
    pixel_gravity:NoitaFloat = field(default_factory=NoitaFloat)
    swim_idle_buoyancy_coeff:NoitaFloat = field(default_factory=NoitaFloat)
    swim_down_buoyancy_coeff:NoitaFloat = field(default_factory=NoitaFloat)
    swim_up_buoyancy_coeff:NoitaFloat = field(default_factory=NoitaFloat)
    swim_drag:NoitaFloat = field(default_factory=NoitaFloat)
    swim_extra_horizontal_drag:NoitaFloat = field(default_factory=NoitaFloat)
    mouse_look:NoitaBool = field(default_factory=NoitaBool)
    mouse_look_buffer:NoitaFloat = field(default_factory=NoitaFloat)
    keyboard_look:NoitaBool = field(default_factory=NoitaBool)
    turning_buffer:NoitaFloat = field(default_factory=NoitaFloat)
    animation_to_play:NoitaString = field(default_factory=NoitaString)
    animation_to_play_next:NoitaString = field(default_factory=NoitaString)
    run_animation_velocity_switching_threshold:NoitaFloat = field(default_factory=NoitaFloat)
    run_animation_velocity_switching_enabled:NoitaBool = field(default_factory=NoitaBool)
    turn_animation_frames_between:NoitaInt = field(default_factory=NoitaInt)
    precision_jumping_max_duration_frames:NoitaInt = field(default_factory=NoitaInt)
    audio_liquid_splash_intensity:NoitaFloat = field(default_factory=NoitaFloat)
    
    def Read(self, s:NoitaStream):
        self.Deleted.Read(s)
        self.Enabled.Read(s)
        self.Tags.Read(s)
        self.velocity_min_x.Read(s)
        self.velocity_max_x.Read(s)
        self.velocity_min_y.Read(s)
        self.velocity_max_y.Read(s)
        self.run_velocity.Read(s)
        self.fly_velocity_x.Read(s)
        self.jump_velocity_x.Read(s)
        self.jump_velocity_y.Read(s)
        self.jump_keydown_buffer.Read(s)
        self.fly_speed_max_up.Read(s)
        self.fly_speed_max_down.Read(s)
        self.fly_speed_mult.Read(s)
        self.fly_speed_change_spd.Read(s)
        self.fly_model_player.Read(s)
        self.fly_smooth_y.Read(s)
        self.accel_x.Read(s)
        self.accel_x_air.Read(s)
        self.pixel_gravity.Read(s)
        self.swim_idle_buoyancy_coeff.Read(s)
        self.swim_down_buoyancy_coeff.Read(s)
        self.swim_up_buoyancy_coeff.Read(s)
        self.swim_drag.Read(s)
        self.swim_extra_horizontal_drag.Read(s)
        self.mouse_look.Read(s)
        self.mouse_look_buffer.Read(s)
        self.keyboard_look.Read(s)
        self.turning_buffer.Read(s)
        self.animation_to_play.Read(s)
        self.animation_to_play_next.Read(s)
        self.run_animation_velocity_switching_threshold.Read(s)
        self.run_animation_velocity_switching_enabled.Read(s)
        self.turn_animation_frames_between.Read(s)
        self.precision_jumping_max_duration_frames.Read(s)
        self.audio_liquid_splash_intensity.Read(s)
    
    def Write(self, s:NoitaStream):
        self.Deleted.Write(s)
        self.Enabled.Write(s)
        self.Tags.Write(s)
        self.velocity_min_x.Write(s)
        self.velocity_max_x.Write(s)
        self.velocity_min_y.Write(s)
        self.velocity_max_y.Write(s)
        self.run_velocity.Write(s)
        self.fly_velocity_x.Write(s)
        self.jump_velocity_x.Write(s)
        self.jump_velocity_y.Write(s)
        self.jump_keydown_buffer.Write(s)
        self.fly_speed_max_up.Write(s)
        self.fly_speed_max_down.Write(s)
        self.fly_speed_mult.Write(s)
        self.fly_speed_change_spd.Write(s)
        self.fly_model_player.Write(s)
        self.fly_smooth_y.Write(s)
        self.accel_x.Write(s)
        self.accel_x_air.Write(s)
        self.pixel_gravity.Write(s)
        self.swim_idle_buoyancy_coeff.Write(s)
        self.swim_down_buoyancy_coeff.Write(s)
        self.swim_up_buoyancy_coeff.Write(s)
        self.swim_drag.Write(s)
        self.swim_extra_horizontal_drag.Write(s)
        self.mouse_look.Write(s)
        self.mouse_look_buffer.Write(s)
        self.keyboard_look.Write(s)
        self.turning_buffer.Write(s)
        self.animation_to_play.Write(s)
        self.animation_to_play_next.Write(s)
        self.run_animation_velocity_switching_threshold.Write(s)
        self.run_animation_velocity_switching_enabled.Write(s)
        self.turn_animation_frames_between.Write(s)
        self.precision_jumping_max_duration_frames.Write(s)
        self.audio_liquid_splash_intensity.Write(s)

