from dataclasses import dataclass, field
from BasicNoitaTypes import NoitaBool
from BasicNoitaTypes import NoitaString
from BasicNoitaTypes import NoitaInt
from BasicNoitaTypes import NoitaLensValue
from BasicNoitaTypes import NoitaFloat

from NoitaStream import NoitaStream
@dataclass
class CharacterDataComponent:
    Deleted:NoitaBool = field(default_factory=NoitaBool)
    Enabled:NoitaBool = field(default_factory=NoitaBool)
    Tags:NoitaString = field(default_factory=NoitaString)
    platforming_type:NoitaInt = field(default_factory=NoitaInt)
    collision_aabb_min_x:NoitaLensValue = field(default_factory=lambda: NoitaLensValue(NoitaFloat))
    collision_aabb_max_x:NoitaLensValue = field(default_factory=lambda: NoitaLensValue(NoitaFloat))
    collision_aabb_min_y:NoitaLensValue = field(default_factory=lambda: NoitaLensValue(NoitaFloat))
    collision_aabb_max_y:NoitaLensValue = field(default_factory=lambda: NoitaLensValue(NoitaFloat))
    mass:NoitaFloat = field(default_factory=NoitaFloat)
    buoyancy_check_offset_y:NoitaInt = field(default_factory=NoitaInt)
    liquid_velocity_coeff:NoitaFloat = field(default_factory=NoitaFloat)
    gravity:NoitaFloat = field(default_factory=NoitaFloat)
    fly_time_max:NoitaLensValue = field(default_factory=lambda: NoitaLensValue(NoitaFloat))
    fly_recharge_spd:NoitaFloat = field(default_factory=NoitaFloat)
    fly_recharge_spd_ground:NoitaFloat = field(default_factory=NoitaFloat)
    flying_needs_recharge:NoitaBool = field(default_factory=NoitaBool)
    flying_in_air_wait_frames:NoitaInt = field(default_factory=NoitaInt)
    flying_recharge_removal_frames:NoitaInt = field(default_factory=NoitaInt)
    climb_over_y:NoitaInt = field(default_factory=NoitaInt)
    check_collision_max_size_x:NoitaInt = field(default_factory=NoitaInt)
    check_collision_max_size_y:NoitaInt = field(default_factory=NoitaInt)
    is_on_ground:NoitaBool = field(default_factory=NoitaBool)
    is_on_slippery_ground:NoitaBool = field(default_factory=NoitaBool)
    ground_stickyness:NoitaFloat = field(default_factory=NoitaFloat)
    effect_hit_ground:NoitaBool = field(default_factory=NoitaBool)
    eff_hg_damage_min:NoitaInt = field(default_factory=NoitaInt)
    eff_hg_damage_max:NoitaInt = field(default_factory=NoitaInt)
    eff_hg_position_x:NoitaFloat = field(default_factory=NoitaFloat)
    eff_hg_position_y:NoitaFloat = field(default_factory=NoitaFloat)
    eff_hg_size_x:NoitaFloat = field(default_factory=NoitaFloat)
    eff_hg_size_y:NoitaFloat = field(default_factory=NoitaFloat)
    eff_hg_velocity_min_x:NoitaFloat = field(default_factory=NoitaFloat)
    eff_hg_velocity_max_x:NoitaFloat = field(default_factory=NoitaFloat)
    eff_hg_velocity_min_y:NoitaFloat = field(default_factory=NoitaFloat)
    eff_hg_velocity_max_y:NoitaFloat = field(default_factory=NoitaFloat)
    eff_hg_offset_y:NoitaFloat = field(default_factory=NoitaFloat)
    eff_hg_update_box2d:NoitaBool = field(default_factory=NoitaBool)
    eff_hg_b2force_multiplier:NoitaFloat = field(default_factory=NoitaFloat)
    destroy_ground:NoitaFloat = field(default_factory=NoitaFloat)
    send_transform_update_message:NoitaBool = field(default_factory=NoitaBool)
    dont_update_velocity_and_xform:NoitaBool = field(default_factory=NoitaBool)
    mFlyingTimeLeft:NoitaFloat = field(default_factory=NoitaFloat)
    
    def Read(self, s:NoitaStream):
        self.Deleted.Read(s)
        self.Enabled.Read(s)
        self.Tags.Read(s)
        self.platforming_type.Read(s)
        self.collision_aabb_min_x.Read(s)
        self.collision_aabb_max_x.Read(s)
        self.collision_aabb_min_y.Read(s)
        self.collision_aabb_max_y.Read(s)
        self.mass.Read(s)
        self.buoyancy_check_offset_y.Read(s)
        self.liquid_velocity_coeff.Read(s)
        self.gravity.Read(s)
        self.fly_time_max.Read(s)
        self.fly_recharge_spd.Read(s)
        self.fly_recharge_spd_ground.Read(s)
        self.flying_needs_recharge.Read(s)
        self.flying_in_air_wait_frames.Read(s)
        self.flying_recharge_removal_frames.Read(s)
        self.climb_over_y.Read(s)
        self.check_collision_max_size_x.Read(s)
        self.check_collision_max_size_y.Read(s)
        self.is_on_ground.Read(s)
        self.is_on_slippery_ground.Read(s)
        self.ground_stickyness.Read(s)
        self.effect_hit_ground.Read(s)
        self.eff_hg_damage_min.Read(s)
        self.eff_hg_damage_max.Read(s)
        self.eff_hg_position_x.Read(s)
        self.eff_hg_position_y.Read(s)
        self.eff_hg_size_x.Read(s)
        self.eff_hg_size_y.Read(s)
        self.eff_hg_velocity_min_x.Read(s)
        self.eff_hg_velocity_max_x.Read(s)
        self.eff_hg_velocity_min_y.Read(s)
        self.eff_hg_velocity_max_y.Read(s)
        self.eff_hg_offset_y.Read(s)
        self.eff_hg_update_box2d.Read(s)
        self.eff_hg_b2force_multiplier.Read(s)
        self.destroy_ground.Read(s)
        self.send_transform_update_message.Read(s)
        self.dont_update_velocity_and_xform.Read(s)
        self.mFlyingTimeLeft.Read(s)
    
    def Write(self, s:NoitaStream):
        self.Deleted.Write(s)
        self.Enabled.Write(s)
        self.Tags.Write(s)
        self.platforming_type.Write(s)
        self.collision_aabb_min_x.Write(s)
        self.collision_aabb_max_x.Write(s)
        self.collision_aabb_min_y.Write(s)
        self.collision_aabb_max_y.Write(s)
        self.mass.Write(s)
        self.buoyancy_check_offset_y.Write(s)
        self.liquid_velocity_coeff.Write(s)
        self.gravity.Write(s)
        self.fly_time_max.Write(s)
        self.fly_recharge_spd.Write(s)
        self.fly_recharge_spd_ground.Write(s)
        self.flying_needs_recharge.Write(s)
        self.flying_in_air_wait_frames.Write(s)
        self.flying_recharge_removal_frames.Write(s)
        self.climb_over_y.Write(s)
        self.check_collision_max_size_x.Write(s)
        self.check_collision_max_size_y.Write(s)
        self.is_on_ground.Write(s)
        self.is_on_slippery_ground.Write(s)
        self.ground_stickyness.Write(s)
        self.effect_hit_ground.Write(s)
        self.eff_hg_damage_min.Write(s)
        self.eff_hg_damage_max.Write(s)
        self.eff_hg_position_x.Write(s)
        self.eff_hg_position_y.Write(s)
        self.eff_hg_size_x.Write(s)
        self.eff_hg_size_y.Write(s)
        self.eff_hg_velocity_min_x.Write(s)
        self.eff_hg_velocity_max_x.Write(s)
        self.eff_hg_velocity_min_y.Write(s)
        self.eff_hg_velocity_max_y.Write(s)
        self.eff_hg_offset_y.Write(s)
        self.eff_hg_update_box2d.Write(s)
        self.eff_hg_b2force_multiplier.Write(s)
        self.destroy_ground.Write(s)
        self.send_transform_update_message.Write(s)
        self.dont_update_velocity_and_xform.Write(s)
        self.mFlyingTimeLeft.Write(s)

