from dataclasses import dataclass, field
from BasicNoitaTypes import NoitaBool
from BasicNoitaTypes import NoitaString
from BasicNoitaTypes import NoitaDouble
from GeneratedClasses.ConfigDamagesByType import ConfigDamagesByType
from BasicNoitaTypes import NoitaFloat
from BasicNoitaTypes import NoitaInt
from BasicNoitaTypes import NoitaUInt

from NoitaStream import NoitaStream
@dataclass
class DamageModelComponent:
    Deleted:NoitaBool = field(default_factory=NoitaBool)
    Enabled:NoitaBool = field(default_factory=NoitaBool)
    Tags:NoitaString = field(default_factory=NoitaString)
    hp:NoitaDouble = field(default_factory=NoitaDouble)
    max_hp:NoitaDouble = field(default_factory=NoitaDouble)
    max_hp_cap:NoitaDouble = field(default_factory=NoitaDouble)
    max_hp_old:NoitaDouble = field(default_factory=NoitaDouble)
    damage_multipliers:ConfigDamagesByType = field(default_factory=ConfigDamagesByType)
    critical_damage_resistance:NoitaFloat = field(default_factory=NoitaFloat)
    invincibility_frames:NoitaInt = field(default_factory=NoitaInt)
    falling_damages:NoitaBool = field(default_factory=NoitaBool)
    falling_damage_height_min:NoitaFloat = field(default_factory=NoitaFloat)
    falling_damage_height_max:NoitaFloat = field(default_factory=NoitaFloat)
    falling_damage_damage_min:NoitaFloat = field(default_factory=NoitaFloat)
    falling_damage_damage_max:NoitaFloat = field(default_factory=NoitaFloat)
    air_needed:NoitaBool = field(default_factory=NoitaBool)
    air_in_lungs:NoitaFloat = field(default_factory=NoitaFloat)
    air_in_lungs_max:NoitaFloat = field(default_factory=NoitaFloat)
    air_lack_of_damage:NoitaFloat = field(default_factory=NoitaFloat)
    minimum_knockback_force:NoitaFloat = field(default_factory=NoitaFloat)
    materials_damage:NoitaBool = field(default_factory=NoitaBool)
    material_damage_min_cell_count:NoitaInt = field(default_factory=NoitaInt)
    materials_that_damage:NoitaString = field(default_factory=NoitaString)
    materials_how_much_damage:NoitaString = field(default_factory=NoitaString)
    materials_damage_proportional_to_maxhp:NoitaBool = field(default_factory=NoitaBool)
    physics_objects_damage:NoitaBool = field(default_factory=NoitaBool)
    materials_create_messages:NoitaBool = field(default_factory=NoitaBool)
    materials_that_create_messages:NoitaString = field(default_factory=NoitaString)
    ragdoll_filenames_file:NoitaString = field(default_factory=NoitaString)
    ragdoll_material:NoitaString = field(default_factory=NoitaString)
    ragdoll_offset_x:NoitaFloat = field(default_factory=NoitaFloat)
    ragdoll_offset_y:NoitaFloat = field(default_factory=NoitaFloat)
    ragdoll_fx_forced:NoitaUInt = field(default_factory=NoitaUInt)
    blood_material:NoitaString = field(default_factory=NoitaString)
    blood_spray_material:NoitaString = field(default_factory=NoitaString)
    blood_spray_create_some_cosmetic:NoitaBool = field(default_factory=NoitaBool)
    blood_multiplier:NoitaFloat = field(default_factory=NoitaFloat)
    ragdoll_blood_amount_absolute:NoitaInt = field(default_factory=NoitaInt)
    blood_sprite_directional:NoitaString = field(default_factory=NoitaString)
    blood_sprite_large:NoitaString = field(default_factory=NoitaString)
    healing_particle_effect_entity:NoitaString = field(default_factory=NoitaString)
    create_ragdoll:NoitaBool = field(default_factory=NoitaBool)
    ragdollify_child_entity_sprites:NoitaBool = field(default_factory=NoitaBool)
    ragdollify_root_angular_damping:NoitaFloat = field(default_factory=NoitaFloat)
    ragdollify_disintegrate_nonroot:NoitaBool = field(default_factory=NoitaBool)
    wait_for_kill_flag_on_death:NoitaBool = field(default_factory=NoitaBool)
    kill_now:NoitaBool = field(default_factory=NoitaBool)
    drop_items_on_death:NoitaBool = field(default_factory=NoitaBool)
    ui_report_damage:NoitaBool = field(default_factory=NoitaBool)
    ui_force_report_damage:NoitaBool = field(default_factory=NoitaBool)
    in_liquid_shooting_electrify_prob:NoitaInt = field(default_factory=NoitaInt)
    wet_status_effect_damage:NoitaFloat = field(default_factory=NoitaFloat)
    is_on_fire:NoitaBool = field(default_factory=NoitaBool)
    fire_probability_of_ignition:NoitaFloat = field(default_factory=NoitaFloat)
    fire_how_much_fire_generates:NoitaInt = field(default_factory=NoitaInt)
    fire_damage_ignited_amount:NoitaFloat = field(default_factory=NoitaFloat)
    fire_damage_amount:NoitaFloat = field(default_factory=NoitaFloat)
    mLastElectricityResistanceFrame:NoitaInt = field(default_factory=NoitaInt)
    mLastFrameReportedBlock:NoitaInt = field(default_factory=NoitaInt)
    mLastMaxHpChangeFrame:NoitaInt = field(default_factory=NoitaInt)
    
    def Read(self, s:NoitaStream):
        self.Deleted.Read(s)
        self.Enabled.Read(s)
        self.Tags.Read(s)
        self.hp.Read(s)
        self.max_hp.Read(s)
        self.max_hp_cap.Read(s)
        self.max_hp_old.Read(s)
        self.damage_multipliers.Read(s)
        self.critical_damage_resistance.Read(s)
        self.invincibility_frames.Read(s)
        self.falling_damages.Read(s)
        self.falling_damage_height_min.Read(s)
        self.falling_damage_height_max.Read(s)
        self.falling_damage_damage_min.Read(s)
        self.falling_damage_damage_max.Read(s)
        self.air_needed.Read(s)
        self.air_in_lungs.Read(s)
        self.air_in_lungs_max.Read(s)
        self.air_lack_of_damage.Read(s)
        self.minimum_knockback_force.Read(s)
        self.materials_damage.Read(s)
        self.material_damage_min_cell_count.Read(s)
        self.materials_that_damage.Read(s)
        self.materials_how_much_damage.Read(s)
        self.materials_damage_proportional_to_maxhp.Read(s)
        self.physics_objects_damage.Read(s)
        self.materials_create_messages.Read(s)
        self.materials_that_create_messages.Read(s)
        self.ragdoll_filenames_file.Read(s)
        self.ragdoll_material.Read(s)
        self.ragdoll_offset_x.Read(s)
        self.ragdoll_offset_y.Read(s)
        self.ragdoll_fx_forced.Read(s)
        self.blood_material.Read(s)
        self.blood_spray_material.Read(s)
        self.blood_spray_create_some_cosmetic.Read(s)
        self.blood_multiplier.Read(s)
        self.ragdoll_blood_amount_absolute.Read(s)
        self.blood_sprite_directional.Read(s)
        self.blood_sprite_large.Read(s)
        self.healing_particle_effect_entity.Read(s)
        self.create_ragdoll.Read(s)
        self.ragdollify_child_entity_sprites.Read(s)
        self.ragdollify_root_angular_damping.Read(s)
        self.ragdollify_disintegrate_nonroot.Read(s)
        self.wait_for_kill_flag_on_death.Read(s)
        self.kill_now.Read(s)
        self.drop_items_on_death.Read(s)
        self.ui_report_damage.Read(s)
        self.ui_force_report_damage.Read(s)
        self.in_liquid_shooting_electrify_prob.Read(s)
        self.wet_status_effect_damage.Read(s)
        self.is_on_fire.Read(s)
        self.fire_probability_of_ignition.Read(s)
        self.fire_how_much_fire_generates.Read(s)
        self.fire_damage_ignited_amount.Read(s)
        self.fire_damage_amount.Read(s)
        self.mLastElectricityResistanceFrame.Read(s)
        self.mLastFrameReportedBlock.Read(s)
        self.mLastMaxHpChangeFrame.Read(s)
    
    def Write(self, s:NoitaStream):
        self.Deleted.Write(s)
        self.Enabled.Write(s)
        self.Tags.Write(s)
        self.hp.Write(s)
        self.max_hp.Write(s)
        self.max_hp_cap.Write(s)
        self.max_hp_old.Write(s)
        self.damage_multipliers.Write(s)
        self.critical_damage_resistance.Write(s)
        self.invincibility_frames.Write(s)
        self.falling_damages.Write(s)
        self.falling_damage_height_min.Write(s)
        self.falling_damage_height_max.Write(s)
        self.falling_damage_damage_min.Write(s)
        self.falling_damage_damage_max.Write(s)
        self.air_needed.Write(s)
        self.air_in_lungs.Write(s)
        self.air_in_lungs_max.Write(s)
        self.air_lack_of_damage.Write(s)
        self.minimum_knockback_force.Write(s)
        self.materials_damage.Write(s)
        self.material_damage_min_cell_count.Write(s)
        self.materials_that_damage.Write(s)
        self.materials_how_much_damage.Write(s)
        self.materials_damage_proportional_to_maxhp.Write(s)
        self.physics_objects_damage.Write(s)
        self.materials_create_messages.Write(s)
        self.materials_that_create_messages.Write(s)
        self.ragdoll_filenames_file.Write(s)
        self.ragdoll_material.Write(s)
        self.ragdoll_offset_x.Write(s)
        self.ragdoll_offset_y.Write(s)
        self.ragdoll_fx_forced.Write(s)
        self.blood_material.Write(s)
        self.blood_spray_material.Write(s)
        self.blood_spray_create_some_cosmetic.Write(s)
        self.blood_multiplier.Write(s)
        self.ragdoll_blood_amount_absolute.Write(s)
        self.blood_sprite_directional.Write(s)
        self.blood_sprite_large.Write(s)
        self.healing_particle_effect_entity.Write(s)
        self.create_ragdoll.Write(s)
        self.ragdollify_child_entity_sprites.Write(s)
        self.ragdollify_root_angular_damping.Write(s)
        self.ragdollify_disintegrate_nonroot.Write(s)
        self.wait_for_kill_flag_on_death.Write(s)
        self.kill_now.Write(s)
        self.drop_items_on_death.Write(s)
        self.ui_report_damage.Write(s)
        self.ui_force_report_damage.Write(s)
        self.in_liquid_shooting_electrify_prob.Write(s)
        self.wet_status_effect_damage.Write(s)
        self.is_on_fire.Write(s)
        self.fire_probability_of_ignition.Write(s)
        self.fire_how_much_fire_generates.Write(s)
        self.fire_damage_ignited_amount.Write(s)
        self.fire_damage_amount.Write(s)
        self.mLastElectricityResistanceFrame.Write(s)
        self.mLastFrameReportedBlock.Write(s)
        self.mLastMaxHpChangeFrame.Write(s)

