from dataclasses import dataclass, field
from BasicNoitaTypes import NoitaBool
from BasicNoitaTypes import NoitaString
from BasicNoitaTypes import NoitaUInt
from BasicNoitaTypes import NoitaInt
from BasicNoitaTypes import NoitaFloat
from BasicNoitaTypes import NoitaDouble

from NoitaStream import NoitaStream
@dataclass
class GameEffectComponent:
    Deleted:NoitaBool = field(default_factory=NoitaBool)
    Enabled:NoitaBool = field(default_factory=NoitaBool)
    Tags:NoitaString = field(default_factory=NoitaString)
    effect:NoitaUInt = field(default_factory=NoitaUInt)
    custom_effect_id:NoitaString = field(default_factory=NoitaString)
    frames:NoitaInt = field(default_factory=NoitaInt)
    exclusivity_group:NoitaInt = field(default_factory=NoitaInt)
    report_block_msg:NoitaBool = field(default_factory=NoitaBool)
    disable_movement:NoitaBool = field(default_factory=NoitaBool)
    ragdoll_effect:NoitaUInt = field(default_factory=NoitaUInt)
    ragdoll_material:NoitaInt = field(default_factory=NoitaInt)
    ragdoll_effect_custom_entity_file:NoitaString = field(default_factory=NoitaString)
    ragdoll_fx_custom_entity_apply_only_to_largest_body:NoitaBool = field(default_factory=NoitaBool)
    polymorph_target:NoitaString = field(default_factory=NoitaString)
    mSerializedData:NoitaString = field(default_factory=NoitaString)
    mCaster:NoitaUInt = field(default_factory=NoitaUInt)
    mCasterHerdId:NoitaInt = field(default_factory=NoitaInt)
    teleportation_probability:NoitaInt = field(default_factory=NoitaInt)
    teleportation_delay_min_frames:NoitaInt = field(default_factory=NoitaInt)
    teleportation_radius_min:NoitaFloat = field(default_factory=NoitaFloat)
    teleportation_radius_max:NoitaFloat = field(default_factory=NoitaFloat)
    teleportations_num:NoitaInt = field(default_factory=NoitaInt)
    no_heal_max_hp_cap:NoitaDouble = field(default_factory=NoitaDouble)
    causing_status_effect:NoitaUInt = field(default_factory=NoitaUInt)
    caused_by_ingestion_status_effect:NoitaBool = field(default_factory=NoitaBool)
    caused_by_stains:NoitaBool = field(default_factory=NoitaBool)
    mCharmDisabledCameraBound:NoitaBool = field(default_factory=NoitaBool)
    mCharmEnabledTeleporting:NoitaBool = field(default_factory=NoitaBool)
    mInvisible:NoitaBool = field(default_factory=NoitaBool)
    mCounter:NoitaInt = field(default_factory=NoitaInt)
    mCooldown:NoitaInt = field(default_factory=NoitaInt)
    mIsExtension:NoitaBool = field(default_factory=NoitaBool)
    mIsSpent:NoitaBool = field(default_factory=NoitaBool)
    
    def Read(self, s:NoitaStream):
        self.Deleted.Read(s)
        self.Enabled.Read(s)
        self.Tags.Read(s)
        self.effect.Read(s)
        self.custom_effect_id.Read(s)
        self.frames.Read(s)
        self.exclusivity_group.Read(s)
        self.report_block_msg.Read(s)
        self.disable_movement.Read(s)
        self.ragdoll_effect.Read(s)
        self.ragdoll_material.Read(s)
        self.ragdoll_effect_custom_entity_file.Read(s)
        self.ragdoll_fx_custom_entity_apply_only_to_largest_body.Read(s)
        self.polymorph_target.Read(s)
        self.mSerializedData.Read(s)
        self.mCaster.Read(s)
        self.mCasterHerdId.Read(s)
        self.teleportation_probability.Read(s)
        self.teleportation_delay_min_frames.Read(s)
        self.teleportation_radius_min.Read(s)
        self.teleportation_radius_max.Read(s)
        self.teleportations_num.Read(s)
        self.no_heal_max_hp_cap.Read(s)
        self.causing_status_effect.Read(s)
        self.caused_by_ingestion_status_effect.Read(s)
        self.caused_by_stains.Read(s)
        self.mCharmDisabledCameraBound.Read(s)
        self.mCharmEnabledTeleporting.Read(s)
        self.mInvisible.Read(s)
        self.mCounter.Read(s)
        self.mCooldown.Read(s)
        self.mIsExtension.Read(s)
        self.mIsSpent.Read(s)
    
    def Write(self, s:NoitaStream):
        self.Deleted.Write(s)
        self.Enabled.Write(s)
        self.Tags.Write(s)
        self.effect.Write(s)
        self.custom_effect_id.Write(s)
        self.frames.Write(s)
        self.exclusivity_group.Write(s)
        self.report_block_msg.Write(s)
        self.disable_movement.Write(s)
        self.ragdoll_effect.Write(s)
        self.ragdoll_material.Write(s)
        self.ragdoll_effect_custom_entity_file.Write(s)
        self.ragdoll_fx_custom_entity_apply_only_to_largest_body.Write(s)
        self.polymorph_target.Write(s)
        self.mSerializedData.Write(s)
        self.mCaster.Write(s)
        self.mCasterHerdId.Write(s)
        self.teleportation_probability.Write(s)
        self.teleportation_delay_min_frames.Write(s)
        self.teleportation_radius_min.Write(s)
        self.teleportation_radius_max.Write(s)
        self.teleportations_num.Write(s)
        self.no_heal_max_hp_cap.Write(s)
        self.causing_status_effect.Write(s)
        self.caused_by_ingestion_status_effect.Write(s)
        self.caused_by_stains.Write(s)
        self.mCharmDisabledCameraBound.Write(s)
        self.mCharmEnabledTeleporting.Write(s)
        self.mInvisible.Write(s)
        self.mCounter.Write(s)
        self.mCooldown.Write(s)
        self.mIsExtension.Write(s)
        self.mIsSpent.Write(s)

