from dataclasses import dataclass, field
from BasicNoitaTypes import NoitaBool
from BasicNoitaTypes import NoitaString
from BasicNoitaTypes import NoitaInt
from BasicNoitaTypes import NoitaCVector2
from BasicNoitaTypes import NoitaFloat
from BasicNoitaTypes import NoitaUInt

from NoitaStream import NoitaStream
@dataclass
class ItemComponent:
    Deleted:NoitaBool = field(default_factory=NoitaBool)
    Enabled:NoitaBool = field(default_factory=NoitaBool)
    Tags:NoitaString = field(default_factory=NoitaString)
    item_name:NoitaString = field(default_factory=NoitaString)
    is_stackable:NoitaBool = field(default_factory=NoitaBool)
    is_consumable:NoitaBool = field(default_factory=NoitaBool)
    stats_count_as_item_pick_up:NoitaBool = field(default_factory=NoitaBool)
    auto_pickup:NoitaBool = field(default_factory=NoitaBool)
    permanently_attached:NoitaBool = field(default_factory=NoitaBool)
    uses_remaining:NoitaInt = field(default_factory=NoitaInt)
    is_identified:NoitaBool = field(default_factory=NoitaBool)
    is_frozen:NoitaBool = field(default_factory=NoitaBool)
    collect_nondefault_actions:NoitaBool = field(default_factory=NoitaBool)
    remove_on_death:NoitaBool = field(default_factory=NoitaBool)
    remove_on_death_if_empty:NoitaBool = field(default_factory=NoitaBool)
    remove_default_child_actions_on_death:NoitaBool = field(default_factory=NoitaBool)
    play_hover_animation:NoitaBool = field(default_factory=NoitaBool)
    play_spinning_animation:NoitaBool = field(default_factory=NoitaBool)
    is_equipable_forced:NoitaBool = field(default_factory=NoitaBool)
    play_pick_sound:NoitaBool = field(default_factory=NoitaBool)
    drinkable:NoitaBool = field(default_factory=NoitaBool)
    spawn_pos:NoitaCVector2 = field(default_factory=lambda: NoitaCVector2(NoitaFloat))
    max_child_items:NoitaInt = field(default_factory=NoitaInt)
    ui_sprite:NoitaString = field(default_factory=NoitaString)
    ui_description:NoitaString = field(default_factory=NoitaString)
    preferred_inventory:NoitaUInt = field(default_factory=NoitaUInt)
    enable_orb_hacks:NoitaBool = field(default_factory=NoitaBool)
    is_all_spells_book:NoitaBool = field(default_factory=NoitaBool)
    always_use_item_name_in_ui:NoitaBool = field(default_factory=NoitaBool)
    custom_pickup_string:NoitaString = field(default_factory=NoitaString)
    ui_display_description_on_pick_up_hint:NoitaBool = field(default_factory=NoitaBool)
    inventory_slot:NoitaCVector2 = field(default_factory=lambda: NoitaCVector2(NoitaInt))
    next_frame_pickable:NoitaInt = field(default_factory=NoitaInt)
    npc_next_frame_pickable:NoitaInt = field(default_factory=NoitaInt)
    is_pickable:NoitaBool = field(default_factory=NoitaBool)
    is_hittable_always:NoitaBool = field(default_factory=NoitaBool)
    item_pickup_radius:NoitaFloat = field(default_factory=NoitaFloat)
    camera_max_distance:NoitaFloat = field(default_factory=NoitaFloat)
    camera_smooth_speed_multiplier:NoitaFloat = field(default_factory=NoitaFloat)
    has_been_picked_by_player:NoitaBool = field(default_factory=NoitaBool)
    mFramePickedUp:NoitaInt = field(default_factory=NoitaInt)
    
    def Read(self, s:NoitaStream):
        self.Deleted.Read(s)
        self.Enabled.Read(s)
        self.Tags.Read(s)
        self.item_name.Read(s)
        self.is_stackable.Read(s)
        self.is_consumable.Read(s)
        self.stats_count_as_item_pick_up.Read(s)
        self.auto_pickup.Read(s)
        self.permanently_attached.Read(s)
        self.uses_remaining.Read(s)
        self.is_identified.Read(s)
        self.is_frozen.Read(s)
        self.collect_nondefault_actions.Read(s)
        self.remove_on_death.Read(s)
        self.remove_on_death_if_empty.Read(s)
        self.remove_default_child_actions_on_death.Read(s)
        self.play_hover_animation.Read(s)
        self.play_spinning_animation.Read(s)
        self.is_equipable_forced.Read(s)
        self.play_pick_sound.Read(s)
        self.drinkable.Read(s)
        self.spawn_pos.Read(s)
        self.max_child_items.Read(s)
        self.ui_sprite.Read(s)
        self.ui_description.Read(s)
        self.preferred_inventory.Read(s)
        self.enable_orb_hacks.Read(s)
        self.is_all_spells_book.Read(s)
        self.always_use_item_name_in_ui.Read(s)
        self.custom_pickup_string.Read(s)
        self.ui_display_description_on_pick_up_hint.Read(s)
        self.inventory_slot.Read(s)
        self.next_frame_pickable.Read(s)
        self.npc_next_frame_pickable.Read(s)
        self.is_pickable.Read(s)
        self.is_hittable_always.Read(s)
        self.item_pickup_radius.Read(s)
        self.camera_max_distance.Read(s)
        self.camera_smooth_speed_multiplier.Read(s)
        self.has_been_picked_by_player.Read(s)
        self.mFramePickedUp.Read(s)
    
    def Write(self, s:NoitaStream):
        self.Deleted.Write(s)
        self.Enabled.Write(s)
        self.Tags.Write(s)
        self.item_name.Write(s)
        self.is_stackable.Write(s)
        self.is_consumable.Write(s)
        self.stats_count_as_item_pick_up.Write(s)
        self.auto_pickup.Write(s)
        self.permanently_attached.Write(s)
        self.uses_remaining.Write(s)
        self.is_identified.Write(s)
        self.is_frozen.Write(s)
        self.collect_nondefault_actions.Write(s)
        self.remove_on_death.Write(s)
        self.remove_on_death_if_empty.Write(s)
        self.remove_default_child_actions_on_death.Write(s)
        self.play_hover_animation.Write(s)
        self.play_spinning_animation.Write(s)
        self.is_equipable_forced.Write(s)
        self.play_pick_sound.Write(s)
        self.drinkable.Write(s)
        self.spawn_pos.Write(s)
        self.max_child_items.Write(s)
        self.ui_sprite.Write(s)
        self.ui_description.Write(s)
        self.preferred_inventory.Write(s)
        self.enable_orb_hacks.Write(s)
        self.is_all_spells_book.Write(s)
        self.always_use_item_name_in_ui.Write(s)
        self.custom_pickup_string.Write(s)
        self.ui_display_description_on_pick_up_hint.Write(s)
        self.inventory_slot.Write(s)
        self.next_frame_pickable.Write(s)
        self.npc_next_frame_pickable.Write(s)
        self.is_pickable.Write(s)
        self.is_hittable_always.Write(s)
        self.item_pickup_radius.Write(s)
        self.camera_max_distance.Write(s)
        self.camera_smooth_speed_multiplier.Write(s)
        self.has_been_picked_by_player.Write(s)
        self.mFramePickedUp.Write(s)

