from dataclasses import dataclass, field
from BasicNoitaTypes import NoitaBool
from BasicNoitaTypes import NoitaString
from BasicNoitaTypes import NoitaUInt
from BasicNoitaTypes import NoitaInt

from NoitaStream import NoitaStream
@dataclass
class LuaComponent:
    Deleted:NoitaBool = field(default_factory=NoitaBool)
    Enabled:NoitaBool = field(default_factory=NoitaBool)
    Tags:NoitaString = field(default_factory=NoitaString)
    script_source_file:NoitaString = field(default_factory=NoitaString)
    vm_type:NoitaUInt = field(default_factory=NoitaUInt)
    execute_on_added:NoitaBool = field(default_factory=NoitaBool)
    execute_on_removed:NoitaBool = field(default_factory=NoitaBool)
    execute_every_n_frame:NoitaInt = field(default_factory=NoitaInt)
    execute_times:NoitaInt = field(default_factory=NoitaInt)
    limit_how_many_times_per_frame:NoitaInt = field(default_factory=NoitaInt)
    limit_to_every_n_frame:NoitaInt = field(default_factory=NoitaInt)
    limit_all_callbacks:NoitaBool = field(default_factory=NoitaBool)
    remove_after_executed:NoitaBool = field(default_factory=NoitaBool)
    enable_coroutines:NoitaBool = field(default_factory=NoitaBool)
    call_init_function:NoitaBool = field(default_factory=NoitaBool)
    script_enabled_changed:NoitaString = field(default_factory=NoitaString)
    script_damage_received:NoitaString = field(default_factory=NoitaString)
    script_damage_about_to_be_received:NoitaString = field(default_factory=NoitaString)
    script_item_picked_up:NoitaString = field(default_factory=NoitaString)
    script_shot:NoitaString = field(default_factory=NoitaString)
    script_collision_trigger_hit:NoitaString = field(default_factory=NoitaString)
    script_collision_trigger_timer_finished:NoitaString = field(default_factory=NoitaString)
    script_physics_body_modified:NoitaString = field(default_factory=NoitaString)
    script_pressure_plate_change:NoitaString = field(default_factory=NoitaString)
    script_inhaled_material:NoitaString = field(default_factory=NoitaString)
    script_death:NoitaString = field(default_factory=NoitaString)
    script_throw_item:NoitaString = field(default_factory=NoitaString)
    script_material_area_checker_failed:NoitaString = field(default_factory=NoitaString)
    script_material_area_checker_success:NoitaString = field(default_factory=NoitaString)
    script_electricity_receiver_switched:NoitaString = field(default_factory=NoitaString)
    script_electricity_receiver_electrified:NoitaString = field(default_factory=NoitaString)
    script_kick:NoitaString = field(default_factory=NoitaString)
    script_interacting:NoitaString = field(default_factory=NoitaString)
    script_audio_event_dead:NoitaString = field(default_factory=NoitaString)
    script_wand_fired:NoitaString = field(default_factory=NoitaString)
    script_teleported:NoitaString = field(default_factory=NoitaString)
    script_portal_teleport_used:NoitaString = field(default_factory=NoitaString)
    script_polymorphing_to:NoitaString = field(default_factory=NoitaString)
    script_biome_entered:NoitaString = field(default_factory=NoitaString)
    mLastExecutionFrame:NoitaInt = field(default_factory=NoitaInt)
    mTimesExecutedThisFrame:NoitaInt = field(default_factory=NoitaInt)
    mModAppendsDone:NoitaBool = field(default_factory=NoitaBool)
    
    def Read(self, s:NoitaStream):
        self.Deleted.Read(s)
        self.Enabled.Read(s)
        self.Tags.Read(s)
        self.script_source_file.Read(s)
        self.vm_type.Read(s)
        self.execute_on_added.Read(s)
        self.execute_on_removed.Read(s)
        self.execute_every_n_frame.Read(s)
        self.execute_times.Read(s)
        self.limit_how_many_times_per_frame.Read(s)
        self.limit_to_every_n_frame.Read(s)
        self.limit_all_callbacks.Read(s)
        self.remove_after_executed.Read(s)
        self.enable_coroutines.Read(s)
        self.call_init_function.Read(s)
        self.script_enabled_changed.Read(s)
        self.script_damage_received.Read(s)
        self.script_damage_about_to_be_received.Read(s)
        self.script_item_picked_up.Read(s)
        self.script_shot.Read(s)
        self.script_collision_trigger_hit.Read(s)
        self.script_collision_trigger_timer_finished.Read(s)
        self.script_physics_body_modified.Read(s)
        self.script_pressure_plate_change.Read(s)
        self.script_inhaled_material.Read(s)
        self.script_death.Read(s)
        self.script_throw_item.Read(s)
        self.script_material_area_checker_failed.Read(s)
        self.script_material_area_checker_success.Read(s)
        self.script_electricity_receiver_switched.Read(s)
        self.script_electricity_receiver_electrified.Read(s)
        self.script_kick.Read(s)
        self.script_interacting.Read(s)
        self.script_audio_event_dead.Read(s)
        self.script_wand_fired.Read(s)
        self.script_teleported.Read(s)
        self.script_portal_teleport_used.Read(s)
        self.script_polymorphing_to.Read(s)
        self.script_biome_entered.Read(s)
        self.mLastExecutionFrame.Read(s)
        self.mTimesExecutedThisFrame.Read(s)
        self.mModAppendsDone.Read(s)
    
    def Write(self, s:NoitaStream):
        self.Deleted.Write(s)
        self.Enabled.Write(s)
        self.Tags.Write(s)
        self.script_source_file.Write(s)
        self.vm_type.Write(s)
        self.execute_on_added.Write(s)
        self.execute_on_removed.Write(s)
        self.execute_every_n_frame.Write(s)
        self.execute_times.Write(s)
        self.limit_how_many_times_per_frame.Write(s)
        self.limit_to_every_n_frame.Write(s)
        self.limit_all_callbacks.Write(s)
        self.remove_after_executed.Write(s)
        self.enable_coroutines.Write(s)
        self.call_init_function.Write(s)
        self.script_enabled_changed.Write(s)
        self.script_damage_received.Write(s)
        self.script_damage_about_to_be_received.Write(s)
        self.script_item_picked_up.Write(s)
        self.script_shot.Write(s)
        self.script_collision_trigger_hit.Write(s)
        self.script_collision_trigger_timer_finished.Write(s)
        self.script_physics_body_modified.Write(s)
        self.script_pressure_plate_change.Write(s)
        self.script_inhaled_material.Write(s)
        self.script_death.Write(s)
        self.script_throw_item.Write(s)
        self.script_material_area_checker_failed.Write(s)
        self.script_material_area_checker_success.Write(s)
        self.script_electricity_receiver_switched.Write(s)
        self.script_electricity_receiver_electrified.Write(s)
        self.script_kick.Write(s)
        self.script_interacting.Write(s)
        self.script_audio_event_dead.Write(s)
        self.script_wand_fired.Write(s)
        self.script_teleported.Write(s)
        self.script_portal_teleport_used.Write(s)
        self.script_polymorphing_to.Write(s)
        self.script_biome_entered.Write(s)
        self.mLastExecutionFrame.Write(s)
        self.mTimesExecutedThisFrame.Write(s)
        self.mModAppendsDone.Write(s)

