from dataclasses import dataclass, field
from BasicNoitaTypes import NoitaBool
from BasicNoitaTypes import NoitaString
from BasicNoitaTypes import NoitaInt
from BasicNoitaTypes import NoitaFloat

from NoitaStream import NoitaStream
@dataclass
class MagicConvertMaterialComponent:
    Deleted:NoitaBool = field(default_factory=NoitaBool)
    Enabled:NoitaBool = field(default_factory=NoitaBool)
    Tags:NoitaString = field(default_factory=NoitaString)
    radius:NoitaInt = field(default_factory=NoitaInt)
    min_radius:NoitaInt = field(default_factory=NoitaInt)
    is_circle:NoitaBool = field(default_factory=NoitaBool)
    steps_per_frame:NoitaInt = field(default_factory=NoitaInt)
    from_material:NoitaInt = field(default_factory=NoitaInt)
    from_material_tag:NoitaString = field(default_factory=NoitaString)
    from_any_material:NoitaBool = field(default_factory=NoitaBool)
    to_material:NoitaInt = field(default_factory=NoitaInt)
    clean_stains:NoitaBool = field(default_factory=NoitaBool)
    extinguish_fire:NoitaBool = field(default_factory=NoitaBool)
    fan_the_flames:NoitaInt = field(default_factory=NoitaInt)
    temperature_reaction_temp:NoitaInt = field(default_factory=NoitaInt)
    ignite_materials:NoitaInt = field(default_factory=NoitaInt)
    loop:NoitaBool = field(default_factory=NoitaBool)
    kill_when_finished:NoitaBool = field(default_factory=NoitaBool)
    convert_entities:NoitaBool = field(default_factory=NoitaBool)
    stain_frozen:NoitaBool = field(default_factory=NoitaBool)
    reaction_audio_amount:NoitaFloat = field(default_factory=NoitaFloat)
    convert_same_material:NoitaBool = field(default_factory=NoitaBool)
    from_material_array:NoitaString = field(default_factory=NoitaString)
    to_material_array:NoitaString = field(default_factory=NoitaString)
    mRadius:NoitaInt = field(default_factory=NoitaInt)
    
    def Read(self, s:NoitaStream):
        self.Deleted.Read(s)
        self.Enabled.Read(s)
        self.Tags.Read(s)
        self.radius.Read(s)
        self.min_radius.Read(s)
        self.is_circle.Read(s)
        self.steps_per_frame.Read(s)
        self.from_material.Read(s)
        self.from_material_tag.Read(s)
        self.from_any_material.Read(s)
        self.to_material.Read(s)
        self.clean_stains.Read(s)
        self.extinguish_fire.Read(s)
        self.fan_the_flames.Read(s)
        self.temperature_reaction_temp.Read(s)
        self.ignite_materials.Read(s)
        self.loop.Read(s)
        self.kill_when_finished.Read(s)
        self.convert_entities.Read(s)
        self.stain_frozen.Read(s)
        self.reaction_audio_amount.Read(s)
        self.convert_same_material.Read(s)
        self.from_material_array.Read(s)
        self.to_material_array.Read(s)
        self.mRadius.Read(s)
    
    def Write(self, s:NoitaStream):
        self.Deleted.Write(s)
        self.Enabled.Write(s)
        self.Tags.Write(s)
        self.radius.Write(s)
        self.min_radius.Write(s)
        self.is_circle.Write(s)
        self.steps_per_frame.Write(s)
        self.from_material.Write(s)
        self.from_material_tag.Write(s)
        self.from_any_material.Write(s)
        self.to_material.Write(s)
        self.clean_stains.Write(s)
        self.extinguish_fire.Write(s)
        self.fan_the_flames.Write(s)
        self.temperature_reaction_temp.Write(s)
        self.ignite_materials.Write(s)
        self.loop.Write(s)
        self.kill_when_finished.Write(s)
        self.convert_entities.Write(s)
        self.stain_frozen.Write(s)
        self.reaction_audio_amount.Write(s)
        self.convert_same_material.Write(s)
        self.from_material_array.Write(s)
        self.to_material_array.Write(s)
        self.mRadius.Write(s)

