from dataclasses import dataclass, field
from BasicNoitaTypes import NoitaBool
from BasicNoitaTypes import NoitaString
from BasicNoitaTypes import NoitaInt
from BasicNoitaTypes import NoitaUInt
from BasicNoitaTypes import NoitaFloat
from BasicNoitaTypes import NoitaCVector2
from BasicNoitaTypes import NoitaFloat
from GeneratedClasses.ValueRange import ValueRange
from BasicNoitaTypes import NoitaLensValue
from BasicNoitaTypes import NoitaInt

from NoitaStream import NoitaStream
@dataclass
class ParticleEmitterComponent:
    Deleted:NoitaBool = field(default_factory=NoitaBool)
    Enabled:NoitaBool = field(default_factory=NoitaBool)
    Tags:NoitaString = field(default_factory=NoitaString)
    emitted_material_name:NoitaString = field(default_factory=NoitaString)
    create_real_particles:NoitaBool = field(default_factory=NoitaBool)
    emit_real_particles:NoitaBool = field(default_factory=NoitaBool)
    emit_cosmetic_particles:NoitaBool = field(default_factory=NoitaBool)
    cosmetic_force_create:NoitaBool = field(default_factory=NoitaBool)
    render_back:NoitaBool = field(default_factory=NoitaBool)
    render_ultrabright:NoitaBool = field(default_factory=NoitaBool)
    collide_with_grid:NoitaBool = field(default_factory=NoitaBool)
    collide_with_gas_and_fire:NoitaBool = field(default_factory=NoitaBool)
    particle_single_width:NoitaBool = field(default_factory=NoitaBool)
    emit_only_if_there_is_space:NoitaBool = field(default_factory=NoitaBool)
    emitter_lifetime_frames:NoitaInt = field(default_factory=NoitaInt)
    fire_cells_dont_ignite_damagemodel:NoitaBool = field(default_factory=NoitaBool)
    color_is_based_on_pos:NoitaBool = field(default_factory=NoitaBool)
    color:NoitaUInt = field(default_factory=NoitaUInt)
    custom_alpha:NoitaFloat = field(default_factory=NoitaFloat)
    offset:NoitaCVector2 = field(default_factory=lambda: NoitaCVector2(NoitaFloat))
    x_pos_offset_min:NoitaFloat = field(default_factory=NoitaFloat)
    y_pos_offset_min:NoitaFloat = field(default_factory=NoitaFloat)
    x_pos_offset_max:NoitaFloat = field(default_factory=NoitaFloat)
    y_pos_offset_max:NoitaFloat = field(default_factory=NoitaFloat)
    area_circle_radius:ValueRange = field(default_factory=ValueRange)
    area_circle_sector_degrees:NoitaFloat = field(default_factory=NoitaFloat)
    x_vel_min:NoitaFloat = field(default_factory=NoitaFloat)
    x_vel_max:NoitaFloat = field(default_factory=NoitaFloat)
    y_vel_min:NoitaFloat = field(default_factory=NoitaFloat)
    y_vel_max:NoitaFloat = field(default_factory=NoitaFloat)
    direction_random_deg:NoitaFloat = field(default_factory=NoitaFloat)
    gravity:NoitaCVector2 = field(default_factory=lambda: NoitaCVector2(NoitaFloat))
    velocity_always_away_from_center:NoitaFloat = field(default_factory=NoitaFloat)
    lifetime_min:NoitaFloat = field(default_factory=NoitaFloat)
    lifetime_max:NoitaFloat = field(default_factory=NoitaFloat)
    airflow_force:NoitaFloat = field(default_factory=NoitaFloat)
    airflow_time:NoitaFloat = field(default_factory=NoitaFloat)
    airflow_scale:NoitaFloat = field(default_factory=NoitaFloat)
    friction:NoitaFloat = field(default_factory=NoitaFloat)
    attractor_force:NoitaFloat = field(default_factory=NoitaFloat)
    count_min:NoitaLensValue = field(default_factory=lambda: NoitaLensValue(NoitaInt))
    count_max:NoitaLensValue = field(default_factory=lambda: NoitaLensValue(NoitaInt))
    emission_interval_min_frames:NoitaInt = field(default_factory=NoitaInt)
    emission_interval_max_frames:NoitaInt = field(default_factory=NoitaInt)
    emission_chance:NoitaInt = field(default_factory=NoitaInt)
    custom_style:NoitaUInt = field(default_factory=NoitaUInt)
    delay_frames:NoitaInt = field(default_factory=NoitaInt)
    is_emitting:NoitaBool = field(default_factory=NoitaBool)
    use_material_inventory:NoitaBool = field(default_factory=NoitaBool)
    is_trail:NoitaBool = field(default_factory=NoitaBool)
    trail_gap:NoitaFloat = field(default_factory=NoitaFloat)
    render_on_grid:NoitaBool = field(default_factory=NoitaBool)
    fade_based_on_lifetime:NoitaBool = field(default_factory=NoitaBool)
    draw_as_long:NoitaBool = field(default_factory=NoitaBool)
    b2_force:NoitaFloat = field(default_factory=NoitaFloat)
    set_magic_creation:NoitaBool = field(default_factory=NoitaBool)
    image_animation_file:NoitaString = field(default_factory=NoitaString)
    image_animation_colors_file:NoitaString = field(default_factory=NoitaString)
    image_animation_speed:NoitaFloat = field(default_factory=NoitaFloat)
    image_animation_loop:NoitaBool = field(default_factory=NoitaBool)
    image_animation_phase:NoitaFloat = field(default_factory=NoitaFloat)
    image_animation_emission_probability:NoitaFloat = field(default_factory=NoitaFloat)
    image_animation_raytrace_from_center:NoitaBool = field(default_factory=NoitaBool)
    image_animation_use_entity_rotation:NoitaBool = field(default_factory=NoitaBool)
    ignore_transform_updated_msg:NoitaBool = field(default_factory=NoitaBool)
    
    def Read(self, s:NoitaStream):
        self.Deleted.Read(s)
        self.Enabled.Read(s)
        self.Tags.Read(s)
        self.emitted_material_name.Read(s)
        self.create_real_particles.Read(s)
        self.emit_real_particles.Read(s)
        self.emit_cosmetic_particles.Read(s)
        self.cosmetic_force_create.Read(s)
        self.render_back.Read(s)
        self.render_ultrabright.Read(s)
        self.collide_with_grid.Read(s)
        self.collide_with_gas_and_fire.Read(s)
        self.particle_single_width.Read(s)
        self.emit_only_if_there_is_space.Read(s)
        self.emitter_lifetime_frames.Read(s)
        self.fire_cells_dont_ignite_damagemodel.Read(s)
        self.color_is_based_on_pos.Read(s)
        self.color.Read(s)
        self.custom_alpha.Read(s)
        self.offset.Read(s)
        self.x_pos_offset_min.Read(s)
        self.y_pos_offset_min.Read(s)
        self.x_pos_offset_max.Read(s)
        self.y_pos_offset_max.Read(s)
        self.area_circle_radius.Read(s)
        self.area_circle_sector_degrees.Read(s)
        self.x_vel_min.Read(s)
        self.x_vel_max.Read(s)
        self.y_vel_min.Read(s)
        self.y_vel_max.Read(s)
        self.direction_random_deg.Read(s)
        self.gravity.Read(s)
        self.velocity_always_away_from_center.Read(s)
        self.lifetime_min.Read(s)
        self.lifetime_max.Read(s)
        self.airflow_force.Read(s)
        self.airflow_time.Read(s)
        self.airflow_scale.Read(s)
        self.friction.Read(s)
        self.attractor_force.Read(s)
        self.count_min.Read(s)
        self.count_max.Read(s)
        self.emission_interval_min_frames.Read(s)
        self.emission_interval_max_frames.Read(s)
        self.emission_chance.Read(s)
        self.custom_style.Read(s)
        self.delay_frames.Read(s)
        self.is_emitting.Read(s)
        self.use_material_inventory.Read(s)
        self.is_trail.Read(s)
        self.trail_gap.Read(s)
        self.render_on_grid.Read(s)
        self.fade_based_on_lifetime.Read(s)
        self.draw_as_long.Read(s)
        self.b2_force.Read(s)
        self.set_magic_creation.Read(s)
        self.image_animation_file.Read(s)
        self.image_animation_colors_file.Read(s)
        self.image_animation_speed.Read(s)
        self.image_animation_loop.Read(s)
        self.image_animation_phase.Read(s)
        self.image_animation_emission_probability.Read(s)
        self.image_animation_raytrace_from_center.Read(s)
        self.image_animation_use_entity_rotation.Read(s)
        self.ignore_transform_updated_msg.Read(s)
    
    def Write(self, s:NoitaStream):
        self.Deleted.Write(s)
        self.Enabled.Write(s)
        self.Tags.Write(s)
        self.emitted_material_name.Write(s)
        self.create_real_particles.Write(s)
        self.emit_real_particles.Write(s)
        self.emit_cosmetic_particles.Write(s)
        self.cosmetic_force_create.Write(s)
        self.render_back.Write(s)
        self.render_ultrabright.Write(s)
        self.collide_with_grid.Write(s)
        self.collide_with_gas_and_fire.Write(s)
        self.particle_single_width.Write(s)
        self.emit_only_if_there_is_space.Write(s)
        self.emitter_lifetime_frames.Write(s)
        self.fire_cells_dont_ignite_damagemodel.Write(s)
        self.color_is_based_on_pos.Write(s)
        self.color.Write(s)
        self.custom_alpha.Write(s)
        self.offset.Write(s)
        self.x_pos_offset_min.Write(s)
        self.y_pos_offset_min.Write(s)
        self.x_pos_offset_max.Write(s)
        self.y_pos_offset_max.Write(s)
        self.area_circle_radius.Write(s)
        self.area_circle_sector_degrees.Write(s)
        self.x_vel_min.Write(s)
        self.x_vel_max.Write(s)
        self.y_vel_min.Write(s)
        self.y_vel_max.Write(s)
        self.direction_random_deg.Write(s)
        self.gravity.Write(s)
        self.velocity_always_away_from_center.Write(s)
        self.lifetime_min.Write(s)
        self.lifetime_max.Write(s)
        self.airflow_force.Write(s)
        self.airflow_time.Write(s)
        self.airflow_scale.Write(s)
        self.friction.Write(s)
        self.attractor_force.Write(s)
        self.count_min.Write(s)
        self.count_max.Write(s)
        self.emission_interval_min_frames.Write(s)
        self.emission_interval_max_frames.Write(s)
        self.emission_chance.Write(s)
        self.custom_style.Write(s)
        self.delay_frames.Write(s)
        self.is_emitting.Write(s)
        self.use_material_inventory.Write(s)
        self.is_trail.Write(s)
        self.trail_gap.Write(s)
        self.render_on_grid.Write(s)
        self.fade_based_on_lifetime.Write(s)
        self.draw_as_long.Write(s)
        self.b2_force.Write(s)
        self.set_magic_creation.Write(s)
        self.image_animation_file.Write(s)
        self.image_animation_colors_file.Write(s)
        self.image_animation_speed.Write(s)
        self.image_animation_loop.Write(s)
        self.image_animation_phase.Write(s)
        self.image_animation_emission_probability.Write(s)
        self.image_animation_raytrace_from_center.Write(s)
        self.image_animation_use_entity_rotation.Write(s)
        self.ignore_transform_updated_msg.Write(s)

