from dataclasses import dataclass, field
from BasicNoitaTypes import NoitaBool
from BasicNoitaTypes import NoitaString
from BasicNoitaTypes import NoitaInt
from BasicNoitaTypes import NoitaFloat
from BasicNoitaTypes import NoitaVector
from GeneratedClasses.PathFindingJumpParams import PathFindingJumpParams

from NoitaStream import NoitaStream
@dataclass
class PathFindingComponent:
    Deleted:NoitaBool = field(default_factory=NoitaBool)
    Enabled:NoitaBool = field(default_factory=NoitaBool)
    Tags:NoitaString = field(default_factory=NoitaString)
    search_depth_max_no_goal:NoitaInt = field(default_factory=NoitaInt)
    iterations_max_no_goal:NoitaInt = field(default_factory=NoitaInt)
    search_depth_max_with_goal:NoitaInt = field(default_factory=NoitaInt)
    iterations_max_with_goal:NoitaInt = field(default_factory=NoitaInt)
    cost_of_flying:NoitaFloat = field(default_factory=NoitaFloat)
    distance_to_reach_node_x:NoitaInt = field(default_factory=NoitaInt)
    distance_to_reach_node_y:NoitaInt = field(default_factory=NoitaInt)
    frames_to_get_stuck:NoitaInt = field(default_factory=NoitaInt)
    frames_between_searches:NoitaInt = field(default_factory=NoitaInt)
    y_walking_compensation:NoitaFloat = field(default_factory=NoitaFloat)
    can_fly:NoitaBool = field(default_factory=NoitaBool)
    can_walk:NoitaBool = field(default_factory=NoitaBool)
    can_jump:NoitaBool = field(default_factory=NoitaBool)
    can_dive:NoitaBool = field(default_factory=NoitaBool)
    can_swim_on_surface:NoitaBool = field(default_factory=NoitaBool)
    never_consider_line_of_sight:NoitaBool = field(default_factory=NoitaBool)
    space_required:NoitaFloat = field(default_factory=NoitaFloat)
    max_jump_distance_from_camera:NoitaFloat = field(default_factory=NoitaFloat)
    jump_speed:NoitaFloat = field(default_factory=NoitaFloat)
    initial_jump_lob:NoitaFloat = field(default_factory=NoitaFloat)
    initial_jump_max_distance_x:NoitaFloat = field(default_factory=NoitaFloat)
    initial_jump_max_distance_y:NoitaFloat = field(default_factory=NoitaFloat)
    jump_trajectories:NoitaVector = field(default_factory=lambda: NoitaVector(PathFindingJumpParams))
    read_state:NoitaInt = field(default_factory=NoitaInt)
    
    def Read(self, s:NoitaStream):
        self.Deleted.Read(s)
        self.Enabled.Read(s)
        self.Tags.Read(s)
        self.search_depth_max_no_goal.Read(s)
        self.iterations_max_no_goal.Read(s)
        self.search_depth_max_with_goal.Read(s)
        self.iterations_max_with_goal.Read(s)
        self.cost_of_flying.Read(s)
        self.distance_to_reach_node_x.Read(s)
        self.distance_to_reach_node_y.Read(s)
        self.frames_to_get_stuck.Read(s)
        self.frames_between_searches.Read(s)
        self.y_walking_compensation.Read(s)
        self.can_fly.Read(s)
        self.can_walk.Read(s)
        self.can_jump.Read(s)
        self.can_dive.Read(s)
        self.can_swim_on_surface.Read(s)
        self.never_consider_line_of_sight.Read(s)
        self.space_required.Read(s)
        self.max_jump_distance_from_camera.Read(s)
        self.jump_speed.Read(s)
        self.initial_jump_lob.Read(s)
        self.initial_jump_max_distance_x.Read(s)
        self.initial_jump_max_distance_y.Read(s)
        self.jump_trajectories.Read(s)
        self.read_state.Read(s)
    
    def Write(self, s:NoitaStream):
        self.Deleted.Write(s)
        self.Enabled.Write(s)
        self.Tags.Write(s)
        self.search_depth_max_no_goal.Write(s)
        self.iterations_max_no_goal.Write(s)
        self.search_depth_max_with_goal.Write(s)
        self.iterations_max_with_goal.Write(s)
        self.cost_of_flying.Write(s)
        self.distance_to_reach_node_x.Write(s)
        self.distance_to_reach_node_y.Write(s)
        self.frames_to_get_stuck.Write(s)
        self.frames_between_searches.Write(s)
        self.y_walking_compensation.Write(s)
        self.can_fly.Write(s)
        self.can_walk.Write(s)
        self.can_jump.Write(s)
        self.can_dive.Write(s)
        self.can_swim_on_surface.Write(s)
        self.never_consider_line_of_sight.Write(s)
        self.space_required.Write(s)
        self.max_jump_distance_from_camera.Write(s)
        self.jump_speed.Write(s)
        self.initial_jump_lob.Write(s)
        self.initial_jump_max_distance_x.Write(s)
        self.initial_jump_max_distance_y.Write(s)
        self.jump_trajectories.Write(s)
        self.read_state.Write(s)

