from dataclasses import dataclass, field
from BasicNoitaTypes import NoitaBool
from BasicNoitaTypes import NoitaString
from BasicNoitaTypes import NoitaFloat
from BasicNoitaTypes import NoitaInt

from NoitaStream import NoitaStream
@dataclass
class PhysicsAIComponent:
    Deleted:NoitaBool = field(default_factory=NoitaBool)
    Enabled:NoitaBool = field(default_factory=NoitaBool)
    Tags:NoitaString = field(default_factory=NoitaString)
    target_vec_max_len:NoitaFloat = field(default_factory=NoitaFloat)
    force_coeff:NoitaFloat = field(default_factory=NoitaFloat)
    force_balancing_coeff:NoitaFloat = field(default_factory=NoitaFloat)
    force_max:NoitaFloat = field(default_factory=NoitaFloat)
    torque_coeff:NoitaFloat = field(default_factory=NoitaFloat)
    torque_balancing_coeff:NoitaFloat = field(default_factory=NoitaFloat)
    torque_max:NoitaFloat = field(default_factory=NoitaFloat)
    torque_damaged_max:NoitaFloat = field(default_factory=NoitaFloat)
    torque_jump_random:NoitaFloat = field(default_factory=NoitaFloat)
    damage_deactivation_probability:NoitaInt = field(default_factory=NoitaInt)
    damage_deactivation_time_min:NoitaInt = field(default_factory=NoitaInt)
    damage_deactivation_time_max:NoitaInt = field(default_factory=NoitaInt)
    die_on_remaining_mass_percentage:NoitaFloat = field(default_factory=NoitaFloat)
    levitate:NoitaBool = field(default_factory=NoitaBool)
    v0_jump_logic:NoitaBool = field(default_factory=NoitaBool)
    v0_swim_logic:NoitaBool = field(default_factory=NoitaBool)
    v0_body_id_logic:NoitaBool = field(default_factory=NoitaBool)
    swim_check_y_min:NoitaInt = field(default_factory=NoitaInt)
    swim_check_y_max:NoitaInt = field(default_factory=NoitaInt)
    swim_check_side_x:NoitaInt = field(default_factory=NoitaInt)
    swim_check_side_y:NoitaInt = field(default_factory=NoitaInt)
    keep_inside_world:NoitaBool = field(default_factory=NoitaBool)
    free_if_static:NoitaBool = field(default_factory=NoitaBool)
    
    def Read(self, s:NoitaStream):
        self.Deleted.Read(s)
        self.Enabled.Read(s)
        self.Tags.Read(s)
        self.target_vec_max_len.Read(s)
        self.force_coeff.Read(s)
        self.force_balancing_coeff.Read(s)
        self.force_max.Read(s)
        self.torque_coeff.Read(s)
        self.torque_balancing_coeff.Read(s)
        self.torque_max.Read(s)
        self.torque_damaged_max.Read(s)
        self.torque_jump_random.Read(s)
        self.damage_deactivation_probability.Read(s)
        self.damage_deactivation_time_min.Read(s)
        self.damage_deactivation_time_max.Read(s)
        self.die_on_remaining_mass_percentage.Read(s)
        self.levitate.Read(s)
        self.v0_jump_logic.Read(s)
        self.v0_swim_logic.Read(s)
        self.v0_body_id_logic.Read(s)
        self.swim_check_y_min.Read(s)
        self.swim_check_y_max.Read(s)
        self.swim_check_side_x.Read(s)
        self.swim_check_side_y.Read(s)
        self.keep_inside_world.Read(s)
        self.free_if_static.Read(s)
    
    def Write(self, s:NoitaStream):
        self.Deleted.Write(s)
        self.Enabled.Write(s)
        self.Tags.Write(s)
        self.target_vec_max_len.Write(s)
        self.force_coeff.Write(s)
        self.force_balancing_coeff.Write(s)
        self.force_max.Write(s)
        self.torque_coeff.Write(s)
        self.torque_balancing_coeff.Write(s)
        self.torque_max.Write(s)
        self.torque_damaged_max.Write(s)
        self.torque_jump_random.Write(s)
        self.damage_deactivation_probability.Write(s)
        self.damage_deactivation_time_min.Write(s)
        self.damage_deactivation_time_max.Write(s)
        self.die_on_remaining_mass_percentage.Write(s)
        self.levitate.Write(s)
        self.v0_jump_logic.Write(s)
        self.v0_swim_logic.Write(s)
        self.v0_body_id_logic.Write(s)
        self.swim_check_y_min.Write(s)
        self.swim_check_y_max.Write(s)
        self.swim_check_side_x.Write(s)
        self.swim_check_side_y.Write(s)
        self.keep_inside_world.Write(s)
        self.free_if_static.Write(s)

