from dataclasses import dataclass, field
from BasicNoitaTypes import NoitaBool
from BasicNoitaTypes import NoitaString
from BasicNoitaTypes import NoitaInt
from BasicNoitaTypes import NoitaFloat
from BasicNoitaTypes import NoitaCVector2
from BasicNoitaTypes import NoitaFloat

from NoitaStream import NoitaStream
@dataclass
class PhysicsBodyComponent:
    Deleted:NoitaBool = field(default_factory=NoitaBool)
    Enabled:NoitaBool = field(default_factory=NoitaBool)
    Tags:NoitaString = field(default_factory=NoitaString)
    is_external:NoitaBool = field(default_factory=NoitaBool)
    hax_fix_going_through_ground:NoitaBool = field(default_factory=NoitaBool)
    hax_fix_going_through_sand:NoitaBool = field(default_factory=NoitaBool)
    hax_wait_till_pixel_scenes_loaded:NoitaBool = field(default_factory=NoitaBool)
    uid:NoitaInt = field(default_factory=NoitaInt)
    is_enabled:NoitaBool = field(default_factory=NoitaBool)
    linear_damping:NoitaFloat = field(default_factory=NoitaFloat)
    angular_damping:NoitaFloat = field(default_factory=NoitaFloat)
    allow_sleep:NoitaBool = field(default_factory=NoitaBool)
    fixed_rotation:NoitaBool = field(default_factory=NoitaBool)
    buoyancy:NoitaFloat = field(default_factory=NoitaFloat)
    gravity_scale_if_has_no_image_shapes:NoitaFloat = field(default_factory=NoitaFloat)
    is_bullet:NoitaBool = field(default_factory=NoitaBool)
    is_static:NoitaBool = field(default_factory=NoitaBool)
    is_kinematic:NoitaBool = field(default_factory=NoitaBool)
    is_character:NoitaBool = field(default_factory=NoitaBool)
    go_through_sand:NoitaBool = field(default_factory=NoitaBool)
    gridworld_box2d:NoitaBool = field(default_factory=NoitaBool)
    auto_clean:NoitaBool = field(default_factory=NoitaBool)
    on_death_leave_physics_body:NoitaBool = field(default_factory=NoitaBool)
    on_death_really_leave_body:NoitaBool = field(default_factory=NoitaBool)
    update_entity_transform:NoitaBool = field(default_factory=NoitaBool)
    force_add_update_areas:NoitaBool = field(default_factory=NoitaBool)
    kills_entity:NoitaBool = field(default_factory=NoitaBool)
    projectiles_rotate_toward_velocity:NoitaBool = field(default_factory=NoitaBool)
    initial_velocity:NoitaCVector2 = field(default_factory=lambda: NoitaCVector2(NoitaFloat))
    randomize_init_velocity:NoitaBool = field(default_factory=NoitaBool)
    mActiveState:NoitaBool = field(default_factory=NoitaBool)
    
    def Read(self, s:NoitaStream):
        self.Deleted.Read(s)
        self.Enabled.Read(s)
        self.Tags.Read(s)
        self.is_external.Read(s)
        self.hax_fix_going_through_ground.Read(s)
        self.hax_fix_going_through_sand.Read(s)
        self.hax_wait_till_pixel_scenes_loaded.Read(s)
        self.uid.Read(s)
        self.is_enabled.Read(s)
        self.linear_damping.Read(s)
        self.angular_damping.Read(s)
        self.allow_sleep.Read(s)
        self.fixed_rotation.Read(s)
        self.buoyancy.Read(s)
        self.gravity_scale_if_has_no_image_shapes.Read(s)
        self.is_bullet.Read(s)
        self.is_static.Read(s)
        self.is_kinematic.Read(s)
        self.is_character.Read(s)
        self.go_through_sand.Read(s)
        self.gridworld_box2d.Read(s)
        self.auto_clean.Read(s)
        self.on_death_leave_physics_body.Read(s)
        self.on_death_really_leave_body.Read(s)
        self.update_entity_transform.Read(s)
        self.force_add_update_areas.Read(s)
        self.kills_entity.Read(s)
        self.projectiles_rotate_toward_velocity.Read(s)
        self.initial_velocity.Read(s)
        self.randomize_init_velocity.Read(s)
        self.mActiveState.Read(s)
    
    def Write(self, s:NoitaStream):
        self.Deleted.Write(s)
        self.Enabled.Write(s)
        self.Tags.Write(s)
        self.is_external.Write(s)
        self.hax_fix_going_through_ground.Write(s)
        self.hax_fix_going_through_sand.Write(s)
        self.hax_wait_till_pixel_scenes_loaded.Write(s)
        self.uid.Write(s)
        self.is_enabled.Write(s)
        self.linear_damping.Write(s)
        self.angular_damping.Write(s)
        self.allow_sleep.Write(s)
        self.fixed_rotation.Write(s)
        self.buoyancy.Write(s)
        self.gravity_scale_if_has_no_image_shapes.Write(s)
        self.is_bullet.Write(s)
        self.is_static.Write(s)
        self.is_kinematic.Write(s)
        self.is_character.Write(s)
        self.go_through_sand.Write(s)
        self.gridworld_box2d.Write(s)
        self.auto_clean.Write(s)
        self.on_death_leave_physics_body.Write(s)
        self.on_death_really_leave_body.Write(s)
        self.update_entity_transform.Write(s)
        self.force_add_update_areas.Write(s)
        self.kills_entity.Write(s)
        self.projectiles_rotate_toward_velocity.Write(s)
        self.initial_velocity.Write(s)
        self.randomize_init_velocity.Write(s)
        self.mActiveState.Write(s)

