from dataclasses import dataclass, field
from BasicNoitaTypes import NoitaBool
from BasicNoitaTypes import NoitaString
from BasicNoitaTypes import NoitaUInt64
from BasicNoitaTypes import NoitaFloat
from BasicNoitaTypes import NoitaCVector2
from BasicNoitaTypes import NoitaFloat
from BasicNoitaTypes import NoitaUInt

from NoitaStream import NoitaStream
@dataclass
class PhysicsBody2Component:
    Deleted:NoitaBool = field(default_factory=NoitaBool)
    Enabled:NoitaBool = field(default_factory=NoitaBool)
    Tags:NoitaString = field(default_factory=NoitaString)
    mBodyId:NoitaUInt64 = field(default_factory=NoitaUInt64)
    linear_damping:NoitaFloat = field(default_factory=NoitaFloat)
    angular_damping:NoitaFloat = field(default_factory=NoitaFloat)
    allow_sleep:NoitaBool = field(default_factory=NoitaBool)
    fixed_rotation:NoitaBool = field(default_factory=NoitaBool)
    is_bullet:NoitaBool = field(default_factory=NoitaBool)
    is_static:NoitaBool = field(default_factory=NoitaBool)
    buoyancy:NoitaFloat = field(default_factory=NoitaFloat)
    hax_fix_going_through_ground:NoitaBool = field(default_factory=NoitaBool)
    hax_fix_going_through_sand:NoitaBool = field(default_factory=NoitaBool)
    hax_wait_till_pixel_scenes_loaded:NoitaBool = field(default_factory=NoitaBool)
    go_through_sand:NoitaBool = field(default_factory=NoitaBool)
    auto_clean:NoitaBool = field(default_factory=NoitaBool)
    force_add_update_areas:NoitaBool = field(default_factory=NoitaBool)
    update_entity_transform:NoitaBool = field(default_factory=NoitaBool)
    kill_entity_if_body_destroyed:NoitaBool = field(default_factory=NoitaBool)
    kill_entity_after_initialized:NoitaBool = field(default_factory=NoitaBool)
    manual_init:NoitaBool = field(default_factory=NoitaBool)
    destroy_body_if_entity_destroyed:NoitaBool = field(default_factory=NoitaBool)
    root_offset_x:NoitaFloat = field(default_factory=NoitaFloat)
    root_offset_y:NoitaFloat = field(default_factory=NoitaFloat)
    init_offset_x:NoitaFloat = field(default_factory=NoitaFloat)
    init_offset_y:NoitaFloat = field(default_factory=NoitaFloat)
    mActiveState:NoitaBool = field(default_factory=NoitaBool)
    mLocalPosition:NoitaCVector2 = field(default_factory=lambda: NoitaCVector2(NoitaFloat))
    mPixelCountOrig:NoitaUInt = field(default_factory=NoitaUInt)
    
    def Read(self, s:NoitaStream):
        self.Deleted.Read(s)
        self.Enabled.Read(s)
        self.Tags.Read(s)
        self.mBodyId.Read(s)
        self.linear_damping.Read(s)
        self.angular_damping.Read(s)
        self.allow_sleep.Read(s)
        self.fixed_rotation.Read(s)
        self.is_bullet.Read(s)
        self.is_static.Read(s)
        self.buoyancy.Read(s)
        self.hax_fix_going_through_ground.Read(s)
        self.hax_fix_going_through_sand.Read(s)
        self.hax_wait_till_pixel_scenes_loaded.Read(s)
        self.go_through_sand.Read(s)
        self.auto_clean.Read(s)
        self.force_add_update_areas.Read(s)
        self.update_entity_transform.Read(s)
        self.kill_entity_if_body_destroyed.Read(s)
        self.kill_entity_after_initialized.Read(s)
        self.manual_init.Read(s)
        self.destroy_body_if_entity_destroyed.Read(s)
        self.root_offset_x.Read(s)
        self.root_offset_y.Read(s)
        self.init_offset_x.Read(s)
        self.init_offset_y.Read(s)
        self.mActiveState.Read(s)
        self.mLocalPosition.Read(s)
        self.mPixelCountOrig.Read(s)
    
    def Write(self, s:NoitaStream):
        self.Deleted.Write(s)
        self.Enabled.Write(s)
        self.Tags.Write(s)
        self.mBodyId.Write(s)
        self.linear_damping.Write(s)
        self.angular_damping.Write(s)
        self.allow_sleep.Write(s)
        self.fixed_rotation.Write(s)
        self.is_bullet.Write(s)
        self.is_static.Write(s)
        self.buoyancy.Write(s)
        self.hax_fix_going_through_ground.Write(s)
        self.hax_fix_going_through_sand.Write(s)
        self.hax_wait_till_pixel_scenes_loaded.Write(s)
        self.go_through_sand.Write(s)
        self.auto_clean.Write(s)
        self.force_add_update_areas.Write(s)
        self.update_entity_transform.Write(s)
        self.kill_entity_if_body_destroyed.Write(s)
        self.kill_entity_after_initialized.Write(s)
        self.manual_init.Write(s)
        self.destroy_body_if_entity_destroyed.Write(s)
        self.root_offset_x.Write(s)
        self.root_offset_y.Write(s)
        self.init_offset_x.Write(s)
        self.init_offset_y.Write(s)
        self.mActiveState.Write(s)
        self.mLocalPosition.Write(s)
        self.mPixelCountOrig.Write(s)

