from dataclasses import dataclass, field
from BasicNoitaTypes import NoitaBool
from BasicNoitaTypes import NoitaString
from BasicNoitaTypes import NoitaUInt
from BasicNoitaTypes import NoitaInt
from GeneratedClasses.ConfigGunActionInfo import ConfigGunActionInfo
from BasicNoitaTypes import NoitaFloat
from BasicNoitaTypes import NoitaCVector2
from BasicNoitaTypes import NoitaFloat
from GeneratedClasses.ConfigExplosion import ConfigExplosion
from GeneratedClasses.ConfigDamagesByType import ConfigDamagesByType
from GeneratedClasses.ConfigDamageCritical import ConfigDamageCritical

from NoitaStream import NoitaStream
@dataclass
class ProjectileComponent:
    Deleted:NoitaBool = field(default_factory=NoitaBool)
    Enabled:NoitaBool = field(default_factory=NoitaBool)
    Tags:NoitaString = field(default_factory=NoitaString)
    projectile_type:NoitaUInt = field(default_factory=NoitaUInt)
    lifetime:NoitaInt = field(default_factory=NoitaInt)
    lifetime_randomness:NoitaInt = field(default_factory=NoitaInt)
    on_lifetime_out_explode:NoitaBool = field(default_factory=NoitaBool)
    collide_with_world:NoitaBool = field(default_factory=NoitaBool)
    config:ConfigGunActionInfo = field(default_factory=ConfigGunActionInfo)
    speed_min:NoitaFloat = field(default_factory=NoitaFloat)
    speed_max:NoitaFloat = field(default_factory=NoitaFloat)
    friction:NoitaFloat = field(default_factory=NoitaFloat)
    direction_random_rad:NoitaFloat = field(default_factory=NoitaFloat)
    direction_nonrandom_rad:NoitaFloat = field(default_factory=NoitaFloat)
    lob_min:NoitaFloat = field(default_factory=NoitaFloat)
    lob_max:NoitaFloat = field(default_factory=NoitaFloat)
    camera_shake_when_shot:NoitaFloat = field(default_factory=NoitaFloat)
    shoot_light_flash_radius:NoitaFloat = field(default_factory=NoitaFloat)
    shoot_light_flash_r:NoitaUInt = field(default_factory=NoitaUInt)
    shoot_light_flash_g:NoitaUInt = field(default_factory=NoitaUInt)
    shoot_light_flash_b:NoitaUInt = field(default_factory=NoitaUInt)
    create_shell_casing:NoitaBool = field(default_factory=NoitaBool)
    shell_casing_material:NoitaString = field(default_factory=NoitaString)
    shell_casing_offset:NoitaCVector2 = field(default_factory=lambda: NoitaCVector2(NoitaFloat))
    muzzle_flash_file:NoitaString = field(default_factory=NoitaString)
    bounces_left:NoitaInt = field(default_factory=NoitaInt)
    bounce_energy:NoitaFloat = field(default_factory=NoitaFloat)
    bounce_always:NoitaBool = field(default_factory=NoitaBool)
    bounce_at_any_angle:NoitaBool = field(default_factory=NoitaBool)
    attach_to_parent_trigger:NoitaBool = field(default_factory=NoitaBool)
    bounce_fx_file:NoitaString = field(default_factory=NoitaString)
    angular_velocity:NoitaFloat = field(default_factory=NoitaFloat)
    velocity_sets_rotation:NoitaBool = field(default_factory=NoitaBool)
    velocity_sets_scale:NoitaBool = field(default_factory=NoitaBool)
    velocity_sets_scale_coeff:NoitaFloat = field(default_factory=NoitaFloat)
    velocity_sets_y_flip:NoitaBool = field(default_factory=NoitaBool)
    velocity_updates_animation:NoitaFloat = field(default_factory=NoitaFloat)
    ground_penetration_coeff:NoitaFloat = field(default_factory=NoitaFloat)
    ground_penetration_max_durability_to_destroy:NoitaInt = field(default_factory=NoitaInt)
    go_through_this_material:NoitaString = field(default_factory=NoitaString)
    do_moveto_update:NoitaBool = field(default_factory=NoitaBool)
    on_death_duplicate_remaining:NoitaInt = field(default_factory=NoitaInt)
    on_death_gfx_leave_sprite:NoitaBool = field(default_factory=NoitaBool)
    on_death_explode:NoitaBool = field(default_factory=NoitaBool)
    on_death_emit_particle:NoitaBool = field(default_factory=NoitaBool)
    on_death_emit_particle_count:NoitaInt = field(default_factory=NoitaInt)
    die_on_liquid_collision:NoitaBool = field(default_factory=NoitaBool)
    die_on_low_velocity:NoitaBool = field(default_factory=NoitaBool)
    die_on_low_velocity_limit:NoitaFloat = field(default_factory=NoitaFloat)
    on_death_emit_particle_type:NoitaString = field(default_factory=NoitaString)
    on_death_particle_check_concrete:NoitaBool = field(default_factory=NoitaBool)
    ground_collision_fx:NoitaBool = field(default_factory=NoitaBool)
    explosion_dont_damage_shooter:NoitaBool = field(default_factory=NoitaBool)
    config_explosion:ConfigExplosion = field(default_factory=ConfigExplosion)
    on_death_item_pickable_radius:NoitaFloat = field(default_factory=NoitaFloat)
    penetrate_world:NoitaBool = field(default_factory=NoitaBool)
    penetrate_world_velocity_coeff:NoitaFloat = field(default_factory=NoitaFloat)
    penetrate_entities:NoitaBool = field(default_factory=NoitaBool)
    on_collision_die:NoitaBool = field(default_factory=NoitaBool)
    on_collision_remove_projectile:NoitaBool = field(default_factory=NoitaBool)
    on_collision_spawn_entity:NoitaBool = field(default_factory=NoitaBool)
    spawn_entity:NoitaString = field(default_factory=NoitaString)
    spawn_entity_is_projectile:NoitaBool = field(default_factory=NoitaBool)
    physics_impulse_coeff:NoitaFloat = field(default_factory=NoitaFloat)
    damage_every_x_frames:NoitaInt = field(default_factory=NoitaInt)
    damage_scaled_by_speed:NoitaBool = field(default_factory=NoitaBool)
    damage_scale_max_speed:NoitaFloat = field(default_factory=NoitaFloat)
    ragdoll_fx_on_collision:NoitaUInt = field(default_factory=NoitaUInt)
    collide_with_entities:NoitaBool = field(default_factory=NoitaBool)
    collide_with_tag:NoitaString = field(default_factory=NoitaString)
    dont_collide_with_tag:NoitaString = field(default_factory=NoitaString)
    collide_with_shooter_frames:NoitaInt = field(default_factory=NoitaInt)
    friendly_fire:NoitaBool = field(default_factory=NoitaBool)
    damage:NoitaFloat = field(default_factory=NoitaFloat)
    damage_by_type:ConfigDamagesByType = field(default_factory=ConfigDamagesByType)
    damage_critical:ConfigDamageCritical = field(default_factory=ConfigDamageCritical)
    knockback_force:NoitaFloat = field(default_factory=NoitaFloat)
    ragdoll_force_multiplier:NoitaFloat = field(default_factory=NoitaFloat)
    hit_particle_force_multiplier:NoitaFloat = field(default_factory=NoitaFloat)
    blood_count_multiplier:NoitaFloat = field(default_factory=NoitaFloat)
    damage_game_effect_entities:NoitaString = field(default_factory=NoitaString)
    never_hit_player:NoitaBool = field(default_factory=NoitaBool)
    collect_materials_to_shooter:NoitaBool = field(default_factory=NoitaBool)
    play_damage_sounds:NoitaBool = field(default_factory=NoitaBool)
    mLastFrameDamaged:NoitaInt = field(default_factory=NoitaInt)
    
    def Read(self, s:NoitaStream):
        self.Deleted.Read(s)
        self.Enabled.Read(s)
        self.Tags.Read(s)
        self.projectile_type.Read(s)
        self.lifetime.Read(s)
        self.lifetime_randomness.Read(s)
        self.on_lifetime_out_explode.Read(s)
        self.collide_with_world.Read(s)
        self.config.Read(s)
        self.speed_min.Read(s)
        self.speed_max.Read(s)
        self.friction.Read(s)
        self.direction_random_rad.Read(s)
        self.direction_nonrandom_rad.Read(s)
        self.lob_min.Read(s)
        self.lob_max.Read(s)
        self.camera_shake_when_shot.Read(s)
        self.shoot_light_flash_radius.Read(s)
        self.shoot_light_flash_r.Read(s)
        self.shoot_light_flash_g.Read(s)
        self.shoot_light_flash_b.Read(s)
        self.create_shell_casing.Read(s)
        self.shell_casing_material.Read(s)
        self.shell_casing_offset.Read(s)
        self.muzzle_flash_file.Read(s)
        self.bounces_left.Read(s)
        self.bounce_energy.Read(s)
        self.bounce_always.Read(s)
        self.bounce_at_any_angle.Read(s)
        self.attach_to_parent_trigger.Read(s)
        self.bounce_fx_file.Read(s)
        self.angular_velocity.Read(s)
        self.velocity_sets_rotation.Read(s)
        self.velocity_sets_scale.Read(s)
        self.velocity_sets_scale_coeff.Read(s)
        self.velocity_sets_y_flip.Read(s)
        self.velocity_updates_animation.Read(s)
        self.ground_penetration_coeff.Read(s)
        self.ground_penetration_max_durability_to_destroy.Read(s)
        self.go_through_this_material.Read(s)
        self.do_moveto_update.Read(s)
        self.on_death_duplicate_remaining.Read(s)
        self.on_death_gfx_leave_sprite.Read(s)
        self.on_death_explode.Read(s)
        self.on_death_emit_particle.Read(s)
        self.on_death_emit_particle_count.Read(s)
        self.die_on_liquid_collision.Read(s)
        self.die_on_low_velocity.Read(s)
        self.die_on_low_velocity_limit.Read(s)
        self.on_death_emit_particle_type.Read(s)
        self.on_death_particle_check_concrete.Read(s)
        self.ground_collision_fx.Read(s)
        self.explosion_dont_damage_shooter.Read(s)
        self.config_explosion.Read(s)
        self.on_death_item_pickable_radius.Read(s)
        self.penetrate_world.Read(s)
        self.penetrate_world_velocity_coeff.Read(s)
        self.penetrate_entities.Read(s)
        self.on_collision_die.Read(s)
        self.on_collision_remove_projectile.Read(s)
        self.on_collision_spawn_entity.Read(s)
        self.spawn_entity.Read(s)
        self.spawn_entity_is_projectile.Read(s)
        self.physics_impulse_coeff.Read(s)
        self.damage_every_x_frames.Read(s)
        self.damage_scaled_by_speed.Read(s)
        self.damage_scale_max_speed.Read(s)
        self.ragdoll_fx_on_collision.Read(s)
        self.collide_with_entities.Read(s)
        self.collide_with_tag.Read(s)
        self.dont_collide_with_tag.Read(s)
        self.collide_with_shooter_frames.Read(s)
        self.friendly_fire.Read(s)
        self.damage.Read(s)
        self.damage_by_type.Read(s)
        self.damage_critical.Read(s)
        self.knockback_force.Read(s)
        self.ragdoll_force_multiplier.Read(s)
        self.hit_particle_force_multiplier.Read(s)
        self.blood_count_multiplier.Read(s)
        self.damage_game_effect_entities.Read(s)
        self.never_hit_player.Read(s)
        self.collect_materials_to_shooter.Read(s)
        self.play_damage_sounds.Read(s)
        self.mLastFrameDamaged.Read(s)
    
    def Write(self, s:NoitaStream):
        self.Deleted.Write(s)
        self.Enabled.Write(s)
        self.Tags.Write(s)
        self.projectile_type.Write(s)
        self.lifetime.Write(s)
        self.lifetime_randomness.Write(s)
        self.on_lifetime_out_explode.Write(s)
        self.collide_with_world.Write(s)
        self.config.Write(s)
        self.speed_min.Write(s)
        self.speed_max.Write(s)
        self.friction.Write(s)
        self.direction_random_rad.Write(s)
        self.direction_nonrandom_rad.Write(s)
        self.lob_min.Write(s)
        self.lob_max.Write(s)
        self.camera_shake_when_shot.Write(s)
        self.shoot_light_flash_radius.Write(s)
        self.shoot_light_flash_r.Write(s)
        self.shoot_light_flash_g.Write(s)
        self.shoot_light_flash_b.Write(s)
        self.create_shell_casing.Write(s)
        self.shell_casing_material.Write(s)
        self.shell_casing_offset.Write(s)
        self.muzzle_flash_file.Write(s)
        self.bounces_left.Write(s)
        self.bounce_energy.Write(s)
        self.bounce_always.Write(s)
        self.bounce_at_any_angle.Write(s)
        self.attach_to_parent_trigger.Write(s)
        self.bounce_fx_file.Write(s)
        self.angular_velocity.Write(s)
        self.velocity_sets_rotation.Write(s)
        self.velocity_sets_scale.Write(s)
        self.velocity_sets_scale_coeff.Write(s)
        self.velocity_sets_y_flip.Write(s)
        self.velocity_updates_animation.Write(s)
        self.ground_penetration_coeff.Write(s)
        self.ground_penetration_max_durability_to_destroy.Write(s)
        self.go_through_this_material.Write(s)
        self.do_moveto_update.Write(s)
        self.on_death_duplicate_remaining.Write(s)
        self.on_death_gfx_leave_sprite.Write(s)
        self.on_death_explode.Write(s)
        self.on_death_emit_particle.Write(s)
        self.on_death_emit_particle_count.Write(s)
        self.die_on_liquid_collision.Write(s)
        self.die_on_low_velocity.Write(s)
        self.die_on_low_velocity_limit.Write(s)
        self.on_death_emit_particle_type.Write(s)
        self.on_death_particle_check_concrete.Write(s)
        self.ground_collision_fx.Write(s)
        self.explosion_dont_damage_shooter.Write(s)
        self.config_explosion.Write(s)
        self.on_death_item_pickable_radius.Write(s)
        self.penetrate_world.Write(s)
        self.penetrate_world_velocity_coeff.Write(s)
        self.penetrate_entities.Write(s)
        self.on_collision_die.Write(s)
        self.on_collision_remove_projectile.Write(s)
        self.on_collision_spawn_entity.Write(s)
        self.spawn_entity.Write(s)
        self.spawn_entity_is_projectile.Write(s)
        self.physics_impulse_coeff.Write(s)
        self.damage_every_x_frames.Write(s)
        self.damage_scaled_by_speed.Write(s)
        self.damage_scale_max_speed.Write(s)
        self.ragdoll_fx_on_collision.Write(s)
        self.collide_with_entities.Write(s)
        self.collide_with_tag.Write(s)
        self.dont_collide_with_tag.Write(s)
        self.collide_with_shooter_frames.Write(s)
        self.friendly_fire.Write(s)
        self.damage.Write(s)
        self.damage_by_type.Write(s)
        self.damage_critical.Write(s)
        self.knockback_force.Write(s)
        self.ragdoll_force_multiplier.Write(s)
        self.hit_particle_force_multiplier.Write(s)
        self.blood_count_multiplier.Write(s)
        self.damage_game_effect_entities.Write(s)
        self.never_hit_player.Write(s)
        self.collect_materials_to_shooter.Write(s)
        self.play_damage_sounds.Write(s)
        self.mLastFrameDamaged.Write(s)

