from dataclasses import dataclass, field
from BasicNoitaTypes import NoitaBool
from BasicNoitaTypes import NoitaString
from BasicNoitaTypes import NoitaFloat
from BasicNoitaTypes import NoitaCVector2
from BasicNoitaTypes import NoitaFloat

from NoitaStream import NoitaStream
@dataclass
class SpriteComponent:
    Deleted:NoitaBool = field(default_factory=NoitaBool)
    Enabled:NoitaBool = field(default_factory=NoitaBool)
    Tags:NoitaString = field(default_factory=NoitaString)
    image_file:NoitaString = field(default_factory=NoitaString)
    ui_is_parent:NoitaBool = field(default_factory=NoitaBool)
    is_text_sprite:NoitaBool = field(default_factory=NoitaBool)
    offset_x:NoitaFloat = field(default_factory=NoitaFloat)
    offset_y:NoitaFloat = field(default_factory=NoitaFloat)
    transform_offset:NoitaCVector2 = field(default_factory=lambda: NoitaCVector2(NoitaFloat))
    offset_animator_offset:NoitaCVector2 = field(default_factory=lambda: NoitaCVector2(NoitaFloat))
    alpha:NoitaFloat = field(default_factory=NoitaFloat)
    visible:NoitaBool = field(default_factory=NoitaBool)
    emissive:NoitaBool = field(default_factory=NoitaBool)
    additive:NoitaBool = field(default_factory=NoitaBool)
    fog_of_war_hole:NoitaBool = field(default_factory=NoitaBool)
    smooth_filtering:NoitaBool = field(default_factory=NoitaBool)
    rect_animation:NoitaString = field(default_factory=NoitaString)
    next_rect_animation:NoitaString = field(default_factory=NoitaString)
    text:NoitaString = field(default_factory=NoitaString)
    z_index:NoitaFloat = field(default_factory=NoitaFloat)
    update_transform:NoitaBool = field(default_factory=NoitaBool)
    update_transform_rotation:NoitaBool = field(default_factory=NoitaBool)
    kill_entity_after_finished:NoitaBool = field(default_factory=NoitaBool)
    has_special_scale:NoitaBool = field(default_factory=NoitaBool)
    special_scale_x:NoitaFloat = field(default_factory=NoitaFloat)
    special_scale_y:NoitaFloat = field(default_factory=NoitaFloat)
    never_ragdollify_on_death:NoitaBool = field(default_factory=NoitaBool)
    
    def Read(self, s:NoitaStream):
        self.Deleted.Read(s)
        self.Enabled.Read(s)
        self.Tags.Read(s)
        self.image_file.Read(s)
        self.ui_is_parent.Read(s)
        self.is_text_sprite.Read(s)
        self.offset_x.Read(s)
        self.offset_y.Read(s)
        self.transform_offset.Read(s)
        self.offset_animator_offset.Read(s)
        self.alpha.Read(s)
        self.visible.Read(s)
        self.emissive.Read(s)
        self.additive.Read(s)
        self.fog_of_war_hole.Read(s)
        self.smooth_filtering.Read(s)
        self.rect_animation.Read(s)
        self.next_rect_animation.Read(s)
        self.text.Read(s)
        self.z_index.Read(s)
        self.update_transform.Read(s)
        self.update_transform_rotation.Read(s)
        self.kill_entity_after_finished.Read(s)
        self.has_special_scale.Read(s)
        self.special_scale_x.Read(s)
        self.special_scale_y.Read(s)
        self.never_ragdollify_on_death.Read(s)
    
    def Write(self, s:NoitaStream):
        self.Deleted.Write(s)
        self.Enabled.Write(s)
        self.Tags.Write(s)
        self.image_file.Write(s)
        self.ui_is_parent.Write(s)
        self.is_text_sprite.Write(s)
        self.offset_x.Write(s)
        self.offset_y.Write(s)
        self.transform_offset.Write(s)
        self.offset_animator_offset.Write(s)
        self.alpha.Write(s)
        self.visible.Write(s)
        self.emissive.Write(s)
        self.additive.Write(s)
        self.fog_of_war_hole.Write(s)
        self.smooth_filtering.Write(s)
        self.rect_animation.Write(s)
        self.next_rect_animation.Write(s)
        self.text.Write(s)
        self.z_index.Write(s)
        self.update_transform.Write(s)
        self.update_transform_rotation.Write(s)
        self.kill_entity_after_finished.Write(s)
        self.has_special_scale.Write(s)
        self.special_scale_x.Write(s)
        self.special_scale_y.Write(s)
        self.never_ragdollify_on_death.Write(s)

