from dataclasses import dataclass, field
from BasicNoitaTypes import NoitaBool
from BasicNoitaTypes import NoitaString
from BasicNoitaTypes import NoitaFloat
from GeneratedClasses.ceng_CColorFloat import ceng_CColorFloat
from BasicNoitaTypes import NoitaCVector2
from BasicNoitaTypes import NoitaFloat
from GeneratedClasses.ValueRange import ValueRange
from GeneratedClasses.types_aabb import types_aabb
from BasicNoitaTypes import NoitaInt

from NoitaStream import NoitaStream
@dataclass
class SpriteParticleEmitterComponent:
    Deleted:NoitaBool = field(default_factory=NoitaBool)
    Enabled:NoitaBool = field(default_factory=NoitaBool)
    Tags:NoitaString = field(default_factory=NoitaString)
    sprite_file:NoitaString = field(default_factory=NoitaString)
    sprite_centered:NoitaBool = field(default_factory=NoitaBool)
    sprite_random_rotation:NoitaBool = field(default_factory=NoitaBool)
    render_back:NoitaBool = field(default_factory=NoitaBool)
    delay:NoitaFloat = field(default_factory=NoitaFloat)
    lifetime:NoitaFloat = field(default_factory=NoitaFloat)
    color:ceng_CColorFloat = field(default_factory=ceng_CColorFloat)
    color_change:ceng_CColorFloat = field(default_factory=ceng_CColorFloat)
    additive:NoitaBool = field(default_factory=NoitaBool)
    emissive:NoitaBool = field(default_factory=NoitaBool)
    velocity:NoitaCVector2 = field(default_factory=lambda: NoitaCVector2(NoitaFloat))
    gravity:NoitaCVector2 = field(default_factory=lambda: NoitaCVector2(NoitaFloat))
    velocity_slowdown:NoitaFloat = field(default_factory=NoitaFloat)
    rotation:NoitaFloat = field(default_factory=NoitaFloat)
    angular_velocity:NoitaFloat = field(default_factory=NoitaFloat)
    use_velocity_as_rotation:NoitaBool = field(default_factory=NoitaBool)
    use_rotation_from_velocity_component:NoitaBool = field(default_factory=NoitaBool)
    use_rotation_from_entity:NoitaBool = field(default_factory=NoitaBool)
    entity_velocity_multiplier:NoitaFloat = field(default_factory=NoitaFloat)
    scale:NoitaCVector2 = field(default_factory=lambda: NoitaCVector2(NoitaFloat))
    scale_velocity:NoitaCVector2 = field(default_factory=lambda: NoitaCVector2(NoitaFloat))
    z_index:NoitaFloat = field(default_factory=NoitaFloat)
    randomize_lifetime:ValueRange = field(default_factory=ValueRange)
    randomize_position:types_aabb = field(default_factory=types_aabb)
    randomize_position_inside_hitbox:NoitaBool = field(default_factory=NoitaBool)
    randomize_velocity:types_aabb = field(default_factory=types_aabb)
    randomize_scale:types_aabb = field(default_factory=types_aabb)
    randomize_rotation:ValueRange = field(default_factory=ValueRange)
    randomize_angular_velocity:ValueRange = field(default_factory=ValueRange)
    randomize_alpha:ValueRange = field(default_factory=ValueRange)
    randomize_animation_speed_coeff:ValueRange = field(default_factory=ValueRange)
    velocity_always_away_from_center:NoitaBool = field(default_factory=NoitaBool)
    expand_randomize_position:NoitaCVector2 = field(default_factory=lambda: NoitaCVector2(NoitaFloat))
    camera_bound:NoitaBool = field(default_factory=NoitaBool)
    camera_distance:NoitaFloat = field(default_factory=NoitaFloat)
    is_emitting:NoitaBool = field(default_factory=NoitaBool)
    count_min:NoitaInt = field(default_factory=NoitaInt)
    count_max:NoitaInt = field(default_factory=NoitaInt)
    emission_interval_min_frames:NoitaInt = field(default_factory=NoitaInt)
    emission_interval_max_frames:NoitaInt = field(default_factory=NoitaInt)
    entity_file:NoitaString = field(default_factory=NoitaString)
    
    def Read(self, s:NoitaStream):
        self.Deleted.Read(s)
        self.Enabled.Read(s)
        self.Tags.Read(s)
        self.sprite_file.Read(s)
        self.sprite_centered.Read(s)
        self.sprite_random_rotation.Read(s)
        self.render_back.Read(s)
        self.delay.Read(s)
        self.lifetime.Read(s)
        self.color.Read(s)
        self.color_change.Read(s)
        self.additive.Read(s)
        self.emissive.Read(s)
        self.velocity.Read(s)
        self.gravity.Read(s)
        self.velocity_slowdown.Read(s)
        self.rotation.Read(s)
        self.angular_velocity.Read(s)
        self.use_velocity_as_rotation.Read(s)
        self.use_rotation_from_velocity_component.Read(s)
        self.use_rotation_from_entity.Read(s)
        self.entity_velocity_multiplier.Read(s)
        self.scale.Read(s)
        self.scale_velocity.Read(s)
        self.z_index.Read(s)
        self.randomize_lifetime.Read(s)
        self.randomize_position.Read(s)
        self.randomize_position_inside_hitbox.Read(s)
        self.randomize_velocity.Read(s)
        self.randomize_scale.Read(s)
        self.randomize_rotation.Read(s)
        self.randomize_angular_velocity.Read(s)
        self.randomize_alpha.Read(s)
        self.randomize_animation_speed_coeff.Read(s)
        self.velocity_always_away_from_center.Read(s)
        self.expand_randomize_position.Read(s)
        self.camera_bound.Read(s)
        self.camera_distance.Read(s)
        self.is_emitting.Read(s)
        self.count_min.Read(s)
        self.count_max.Read(s)
        self.emission_interval_min_frames.Read(s)
        self.emission_interval_max_frames.Read(s)
        self.entity_file.Read(s)
    
    def Write(self, s:NoitaStream):
        self.Deleted.Write(s)
        self.Enabled.Write(s)
        self.Tags.Write(s)
        self.sprite_file.Write(s)
        self.sprite_centered.Write(s)
        self.sprite_random_rotation.Write(s)
        self.render_back.Write(s)
        self.delay.Write(s)
        self.lifetime.Write(s)
        self.color.Write(s)
        self.color_change.Write(s)
        self.additive.Write(s)
        self.emissive.Write(s)
        self.velocity.Write(s)
        self.gravity.Write(s)
        self.velocity_slowdown.Write(s)
        self.rotation.Write(s)
        self.angular_velocity.Write(s)
        self.use_velocity_as_rotation.Write(s)
        self.use_rotation_from_velocity_component.Write(s)
        self.use_rotation_from_entity.Write(s)
        self.entity_velocity_multiplier.Write(s)
        self.scale.Write(s)
        self.scale_velocity.Write(s)
        self.z_index.Write(s)
        self.randomize_lifetime.Write(s)
        self.randomize_position.Write(s)
        self.randomize_position_inside_hitbox.Write(s)
        self.randomize_velocity.Write(s)
        self.randomize_scale.Write(s)
        self.randomize_rotation.Write(s)
        self.randomize_angular_velocity.Write(s)
        self.randomize_alpha.Write(s)
        self.randomize_animation_speed_coeff.Write(s)
        self.velocity_always_away_from_center.Write(s)
        self.expand_randomize_position.Write(s)
        self.camera_bound.Write(s)
        self.camera_distance.Write(s)
        self.is_emitting.Write(s)
        self.count_min.Write(s)
        self.count_max.Write(s)
        self.emission_interval_min_frames.Write(s)
        self.emission_interval_max_frames.Write(s)
        self.entity_file.Write(s)

