from dataclasses import dataclass, field
from BasicNoitaTypes import NoitaBool
from BasicNoitaTypes import NoitaString
from BasicNoitaTypes import NoitaInt
from BasicNoitaTypes import NoitaUInt
from BasicNoitaTypes import NoitaFloat
from BasicNoitaTypes import NoitaCVector2
from BasicNoitaTypes import NoitaFloat
from BasicNoitaTypes import NoitaUintArrayInline

from NoitaStream import NoitaStream
@dataclass
class VerletPhysicsComponent:
    Deleted:NoitaBool = field(default_factory=NoitaBool)
    Enabled:NoitaBool = field(default_factory=NoitaBool)
    Tags:NoitaString = field(default_factory=NoitaString)
    num_points:NoitaInt = field(default_factory=NoitaInt)
    num_links:NoitaInt = field(default_factory=NoitaInt)
    width:NoitaInt = field(default_factory=NoitaInt)
    type:NoitaUInt = field(default_factory=NoitaUInt)
    resting_distance:NoitaFloat = field(default_factory=NoitaFloat)
    mass_min:NoitaFloat = field(default_factory=NoitaFloat)
    mass_max:NoitaFloat = field(default_factory=NoitaFloat)
    stiffness:NoitaFloat = field(default_factory=NoitaFloat)
    velocity_dampening:NoitaFloat = field(default_factory=NoitaFloat)
    liquid_damping:NoitaFloat = field(default_factory=NoitaFloat)
    gets_entity_velocity_coeff:NoitaFloat = field(default_factory=NoitaFloat)
    collide_with_cells:NoitaBool = field(default_factory=NoitaBool)
    simulate_gravity:NoitaBool = field(default_factory=NoitaBool)
    simulate_wind:NoitaBool = field(default_factory=NoitaBool)
    wind_change_speed:NoitaFloat = field(default_factory=NoitaFloat)
    constrain_stretching:NoitaBool = field(default_factory=NoitaBool)
    pixelate_sprite_transforms:NoitaBool = field(default_factory=NoitaBool)
    scale_sprite_x:NoitaBool = field(default_factory=NoitaBool)
    follow_entity_transform:NoitaBool = field(default_factory=NoitaBool)
    animation_target_offset:NoitaCVector2 = field(default_factory=lambda: NoitaCVector2(NoitaFloat))
    animation_amount:NoitaFloat = field(default_factory=NoitaFloat)
    animation_speed:NoitaFloat = field(default_factory=NoitaFloat)
    animation_energy:NoitaFloat = field(default_factory=NoitaFloat)
    cloth_sprite_z_index:NoitaFloat = field(default_factory=NoitaFloat)
    stain_cells_probability:NoitaInt = field(default_factory=NoitaInt)
    cloth_color_edge:NoitaUInt = field(default_factory=NoitaUInt)
    cloth_color:NoitaUInt = field(default_factory=NoitaUInt)
    m_position_previous:NoitaCVector2 = field(default_factory=lambda: NoitaCVector2(NoitaFloat))
    m_is_culled_previous:NoitaBool = field(default_factory=NoitaBool)
    colors:NoitaUintArrayInline = field(default_factory=NoitaUintArrayInline)
    materials:NoitaUintArrayInline = field(default_factory=NoitaUintArrayInline)
    
    def Read(self, s:NoitaStream):
        self.Deleted.Read(s)
        self.Enabled.Read(s)
        self.Tags.Read(s)
        self.num_points.Read(s)
        self.num_links.Read(s)
        self.width.Read(s)
        self.type.Read(s)
        self.resting_distance.Read(s)
        self.mass_min.Read(s)
        self.mass_max.Read(s)
        self.stiffness.Read(s)
        self.velocity_dampening.Read(s)
        self.liquid_damping.Read(s)
        self.gets_entity_velocity_coeff.Read(s)
        self.collide_with_cells.Read(s)
        self.simulate_gravity.Read(s)
        self.simulate_wind.Read(s)
        self.wind_change_speed.Read(s)
        self.constrain_stretching.Read(s)
        self.pixelate_sprite_transforms.Read(s)
        self.scale_sprite_x.Read(s)
        self.follow_entity_transform.Read(s)
        self.animation_target_offset.Read(s)
        self.animation_amount.Read(s)
        self.animation_speed.Read(s)
        self.animation_energy.Read(s)
        self.cloth_sprite_z_index.Read(s)
        self.stain_cells_probability.Read(s)
        self.cloth_color_edge.Read(s)
        self.cloth_color.Read(s)
        self.m_position_previous.Read(s)
        self.m_is_culled_previous.Read(s)
        self.colors.Read(s)
        self.materials.Read(s)
    
    def Write(self, s:NoitaStream):
        self.Deleted.Write(s)
        self.Enabled.Write(s)
        self.Tags.Write(s)
        self.num_points.Write(s)
        self.num_links.Write(s)
        self.width.Write(s)
        self.type.Write(s)
        self.resting_distance.Write(s)
        self.mass_min.Write(s)
        self.mass_max.Write(s)
        self.stiffness.Write(s)
        self.velocity_dampening.Write(s)
        self.liquid_damping.Write(s)
        self.gets_entity_velocity_coeff.Write(s)
        self.collide_with_cells.Write(s)
        self.simulate_gravity.Write(s)
        self.simulate_wind.Write(s)
        self.wind_change_speed.Write(s)
        self.constrain_stretching.Write(s)
        self.pixelate_sprite_transforms.Write(s)
        self.scale_sprite_x.Write(s)
        self.follow_entity_transform.Write(s)
        self.animation_target_offset.Write(s)
        self.animation_amount.Write(s)
        self.animation_speed.Write(s)
        self.animation_energy.Write(s)
        self.cloth_sprite_z_index.Write(s)
        self.stain_cells_probability.Write(s)
        self.cloth_color_edge.Write(s)
        self.cloth_color.Write(s)
        self.m_position_previous.Write(s)
        self.m_is_culled_previous.Write(s)
        self.colors.Write(s)
        self.materials.Write(s)

