from dataclasses import dataclass, field
from BasicNoitaTypes import NoitaBool
from BasicNoitaTypes import NoitaString
from BasicNoitaTypes import NoitaFloat
from BasicNoitaTypes import NoitaInt
from BasicNoitaTypes import NoitaCVector2
from BasicNoitaTypes import NoitaFloat
from BasicNoitaTypes import NoitaVector
from BasicNoitaTypes import MissingClassConfigPendingPortal
from BasicNoitaTypes import NoitaUInt
from BasicNoitaTypes import NoitaVector
from BasicNoitaTypes import MissingClassConfigNpcParty
from BasicNoitaTypes import NoitaVector
from BasicNoitaTypes import MissingClassConfigCutThroughWorld
from BasicNoitaTypes import NoitaLensValue
from BasicNoitaTypes import NoitaInt

from NoitaStream import NoitaStream
@dataclass
class WorldStateComponent:
    Deleted:NoitaBool = field(default_factory=NoitaBool)
    Enabled:NoitaBool = field(default_factory=NoitaBool)
    Tags:NoitaString = field(default_factory=NoitaString)
    is_initialized:NoitaBool = field(default_factory=NoitaBool)
    time:NoitaFloat = field(default_factory=NoitaFloat)
    time_total:NoitaFloat = field(default_factory=NoitaFloat)
    time_dt:NoitaFloat = field(default_factory=NoitaFloat)
    day_count:NoitaInt = field(default_factory=NoitaInt)
    rain:NoitaFloat = field(default_factory=NoitaFloat)
    rain_target:NoitaFloat = field(default_factory=NoitaFloat)
    fog:NoitaFloat = field(default_factory=NoitaFloat)
    fog_target:NoitaFloat = field(default_factory=NoitaFloat)
    intro_weather:NoitaBool = field(default_factory=NoitaBool)
    wind:NoitaFloat = field(default_factory=NoitaFloat)
    wind_speed:NoitaFloat = field(default_factory=NoitaFloat)
    wind_speed_sin_t:NoitaFloat = field(default_factory=NoitaFloat)
    wind_speed_sin:NoitaFloat = field(default_factory=NoitaFloat)
    clouds_01_target:NoitaFloat = field(default_factory=NoitaFloat)
    clouds_02_target:NoitaFloat = field(default_factory=NoitaFloat)
    gradient_sky_alpha_target:NoitaFloat = field(default_factory=NoitaFloat)
    sky_sunset_alpha_target:NoitaFloat = field(default_factory=NoitaFloat)
    lightning_count:NoitaInt = field(default_factory=NoitaInt)
    player_spawn_location:NoitaCVector2 = field(default_factory=lambda: NoitaCVector2(NoitaFloat))
    pending_portals:NoitaVector = field(default_factory=lambda: NoitaVector(MissingClassConfigPendingPortal))
    next_portal_id:NoitaUInt = field(default_factory=NoitaUInt)
    apparitions_per_level:NoitaVector = field(default_factory=lambda: NoitaVector(NoitaInt))
    npc_parties:NoitaVector = field(default_factory=lambda: NoitaVector(MissingClassConfigNpcParty))
    session_stat_file:NoitaString = field(default_factory=NoitaString)
    orbs_found_thisrun:NoitaVector = field(default_factory=lambda: NoitaVector(NoitaInt))
    flags:NoitaVector = field(default_factory=lambda: NoitaVector(NoitaString))
    changed_materials:NoitaVector = field(default_factory=lambda: NoitaVector(NoitaString))
    player_polymorph_count:NoitaInt = field(default_factory=NoitaInt)
    player_polymorph_random_count:NoitaInt = field(default_factory=NoitaInt)
    player_did_infinite_spell_count:NoitaInt = field(default_factory=NoitaInt)
    player_did_damage_over_1milj:NoitaInt = field(default_factory=NoitaInt)
    player_living_with_minus_hp:NoitaInt = field(default_factory=NoitaInt)
    global_genome_relations_modifier:NoitaFloat = field(default_factory=NoitaFloat)
    mods_have_been_active_during_this_run:NoitaBool = field(default_factory=NoitaBool)
    twitch_has_been_active_during_this_run:NoitaBool = field(default_factory=NoitaBool)
    next_cut_through_world_id:NoitaUInt = field(default_factory=NoitaUInt)
    cuts_through_world:NoitaVector = field(default_factory=lambda: NoitaVector(MissingClassConfigCutThroughWorld))
    gore_multiplier:NoitaLensValue = field(default_factory=lambda: NoitaLensValue(NoitaInt))
    trick_kill_gold_multiplier:NoitaLensValue = field(default_factory=lambda: NoitaLensValue(NoitaInt))
    damage_flash_multiplier:NoitaLensValue = field(default_factory=lambda: NoitaLensValue(NoitaFloat))
    open_fog_of_war_everywhere:NoitaLensValue = field(default_factory=lambda: NoitaLensValue(NoitaBool))
    consume_actions:NoitaLensValue = field(default_factory=lambda: NoitaLensValue(NoitaBool))
    perk_infinite_spells:NoitaBool = field(default_factory=NoitaBool)
    perk_trick_kills_blood_money:NoitaBool = field(default_factory=NoitaBool)
    perk_hp_drop_chance:NoitaInt = field(default_factory=NoitaInt)
    perk_gold_is_forever:NoitaBool = field(default_factory=NoitaBool)
    perk_rats_player_friendly:NoitaBool = field(default_factory=NoitaBool)
    EVERYTHING_TO_GOLD:NoitaBool = field(default_factory=NoitaBool)
    material_everything_to_gold:NoitaString = field(default_factory=NoitaString)
    material_everything_to_gold_static:NoitaString = field(default_factory=NoitaString)
    INFINITE_GOLD_HAPPENING:NoitaBool = field(default_factory=NoitaBool)
    ENDING_HAPPINESS_HAPPENING:NoitaBool = field(default_factory=NoitaBool)
    ENDING_HAPPINESS_FRAMES:NoitaInt = field(default_factory=NoitaInt)
    ENDING_HAPPINESS:NoitaBool = field(default_factory=NoitaBool)
    mFlashAlpha:NoitaFloat = field(default_factory=NoitaFloat)
    DEBUG_LOADED_FROM_AUTOSAVE:NoitaInt = field(default_factory=NoitaInt)
    DEBUG_LOADED_FROM_OLD_VERSION:NoitaInt = field(default_factory=NoitaInt)
    
    def Read(self, s:NoitaStream):
        self.Deleted.Read(s)
        self.Enabled.Read(s)
        self.Tags.Read(s)
        self.is_initialized.Read(s)
        self.time.Read(s)
        self.time_total.Read(s)
        self.time_dt.Read(s)
        self.day_count.Read(s)
        self.rain.Read(s)
        self.rain_target.Read(s)
        self.fog.Read(s)
        self.fog_target.Read(s)
        self.intro_weather.Read(s)
        self.wind.Read(s)
        self.wind_speed.Read(s)
        self.wind_speed_sin_t.Read(s)
        self.wind_speed_sin.Read(s)
        self.clouds_01_target.Read(s)
        self.clouds_02_target.Read(s)
        self.gradient_sky_alpha_target.Read(s)
        self.sky_sunset_alpha_target.Read(s)
        self.lightning_count.Read(s)
        self.player_spawn_location.Read(s)
        self.pending_portals.Read(s)
        self.next_portal_id.Read(s)
        self.apparitions_per_level.Read(s)
        self.npc_parties.Read(s)
        self.session_stat_file.Read(s)
        self.orbs_found_thisrun.Read(s)
        self.flags.Read(s)
        self.changed_materials.Read(s)
        self.player_polymorph_count.Read(s)
        self.player_polymorph_random_count.Read(s)
        self.player_did_infinite_spell_count.Read(s)
        self.player_did_damage_over_1milj.Read(s)
        self.player_living_with_minus_hp.Read(s)
        self.global_genome_relations_modifier.Read(s)
        self.mods_have_been_active_during_this_run.Read(s)
        self.twitch_has_been_active_during_this_run.Read(s)
        self.next_cut_through_world_id.Read(s)
        self.cuts_through_world.Read(s)
        self.gore_multiplier.Read(s)
        self.trick_kill_gold_multiplier.Read(s)
        self.damage_flash_multiplier.Read(s)
        self.open_fog_of_war_everywhere.Read(s)
        self.consume_actions.Read(s)
        self.perk_infinite_spells.Read(s)
        self.perk_trick_kills_blood_money.Read(s)
        self.perk_hp_drop_chance.Read(s)
        self.perk_gold_is_forever.Read(s)
        self.perk_rats_player_friendly.Read(s)
        self.EVERYTHING_TO_GOLD.Read(s)
        self.material_everything_to_gold.Read(s)
        self.material_everything_to_gold_static.Read(s)
        self.INFINITE_GOLD_HAPPENING.Read(s)
        self.ENDING_HAPPINESS_HAPPENING.Read(s)
        self.ENDING_HAPPINESS_FRAMES.Read(s)
        self.ENDING_HAPPINESS.Read(s)
        self.mFlashAlpha.Read(s)
        self.DEBUG_LOADED_FROM_AUTOSAVE.Read(s)
        self.DEBUG_LOADED_FROM_OLD_VERSION.Read(s)
    
    def Write(self, s:NoitaStream):
        self.Deleted.Write(s)
        self.Enabled.Write(s)
        self.Tags.Write(s)
        self.is_initialized.Write(s)
        self.time.Write(s)
        self.time_total.Write(s)
        self.time_dt.Write(s)
        self.day_count.Write(s)
        self.rain.Write(s)
        self.rain_target.Write(s)
        self.fog.Write(s)
        self.fog_target.Write(s)
        self.intro_weather.Write(s)
        self.wind.Write(s)
        self.wind_speed.Write(s)
        self.wind_speed_sin_t.Write(s)
        self.wind_speed_sin.Write(s)
        self.clouds_01_target.Write(s)
        self.clouds_02_target.Write(s)
        self.gradient_sky_alpha_target.Write(s)
        self.sky_sunset_alpha_target.Write(s)
        self.lightning_count.Write(s)
        self.player_spawn_location.Write(s)
        self.pending_portals.Write(s)
        self.next_portal_id.Write(s)
        self.apparitions_per_level.Write(s)
        self.npc_parties.Write(s)
        self.session_stat_file.Write(s)
        self.orbs_found_thisrun.Write(s)
        self.flags.Write(s)
        self.changed_materials.Write(s)
        self.player_polymorph_count.Write(s)
        self.player_polymorph_random_count.Write(s)
        self.player_did_infinite_spell_count.Write(s)
        self.player_did_damage_over_1milj.Write(s)
        self.player_living_with_minus_hp.Write(s)
        self.global_genome_relations_modifier.Write(s)
        self.mods_have_been_active_during_this_run.Write(s)
        self.twitch_has_been_active_during_this_run.Write(s)
        self.next_cut_through_world_id.Write(s)
        self.cuts_through_world.Write(s)
        self.gore_multiplier.Write(s)
        self.trick_kill_gold_multiplier.Write(s)
        self.damage_flash_multiplier.Write(s)
        self.open_fog_of_war_everywhere.Write(s)
        self.consume_actions.Write(s)
        self.perk_infinite_spells.Write(s)
        self.perk_trick_kills_blood_money.Write(s)
        self.perk_hp_drop_chance.Write(s)
        self.perk_gold_is_forever.Write(s)
        self.perk_rats_player_friendly.Write(s)
        self.EVERYTHING_TO_GOLD.Write(s)
        self.material_everything_to_gold.Write(s)
        self.material_everything_to_gold_static.Write(s)
        self.INFINITE_GOLD_HAPPENING.Write(s)
        self.ENDING_HAPPINESS_HAPPENING.Write(s)
        self.ENDING_HAPPINESS_FRAMES.Write(s)
        self.ENDING_HAPPINESS.Write(s)
        self.mFlashAlpha.Write(s)
        self.DEBUG_LOADED_FROM_AUTOSAVE.Write(s)
        self.DEBUG_LOADED_FROM_OLD_VERSION.Write(s)

