namespace GeneratedNoitaClasses;
public class ConfigGunActionInfo{
	public string action_id{ get; set; }
	public string action_name{ get; set; }
	public string action_description{ get; set; }
	public string action_sprite_filename{ get; set; }
	public string action_unidentified_sprite_filename{ get; set; }
	public int action_type{ get; set; }
	public string action_spawn_level{ get; set; }
	public string action_spawn_probability{ get; set; }
	public string action_spawn_requires_flag{ get; set; }
	public bool action_spawn_manual_unlock{ get; set; }
	public int action_max_uses{ get; set; }
	public string custom_xml_file{ get; set; }
	public float action_mana_drain{ get; set; }
	public bool action_is_dangerous_blast{ get; set; }
	public int action_draw_many_count{ get; set; }
	public bool action_ai_never_uses{ get; set; }
	public bool action_never_unlimited{ get; set; }
	public bool state_shuffled{ get; set; }
	public int state_cards_drawn{ get; set; }
	public bool state_discarded_action{ get; set; }
	public bool state_destroyed_action{ get; set; }
	public int fire_rate_wait{ get; set; }
	public float speed_multiplier{ get; set; }
	public float child_speed_multiplier{ get; set; }
	public float dampening{ get; set; }
	public float explosion_radius{ get; set; }
	public float spread_degrees{ get; set; }
	public float pattern_degrees{ get; set; }
	public float screenshake{ get; set; }
	public float recoil{ get; set; }
	public float damage_melee_add{ get; set; }
	public float damage_projectile_add{ get; set; }
	public float damage_electricity_add{ get; set; }
	public float damage_fire_add{ get; set; }
	public float damage_explosion_add{ get; set; }
	public float damage_ice_add{ get; set; }
	public float damage_slice_add{ get; set; }
	public float damage_healing_add{ get; set; }
	public float damage_curse_add{ get; set; }
	public float damage_drill_add{ get; set; }
	public float damage_null_all{ get; set; }
	public int damage_critical_chance{ get; set; }
	public float damage_critical_multiplier{ get; set; }
	public float explosion_damage_to_materials{ get; set; }
	public float knockback_force{ get; set; }
	public int reload_time{ get; set; }
	public int lightning_count{ get; set; }
	public string material{ get; set; }
	public int material_amount{ get; set; }
	public string trail_material{ get; set; }
	public int trail_material_amount{ get; set; }
	public int bounces{ get; set; }
	public float gravity{ get; set; }
	public float light{ get; set; }
	public float blood_count_multiplier{ get; set; }
	public int gore_particles{ get; set; }
	public int ragdoll_fx{ get; set; }
	public bool friendly_fire{ get; set; }
	public float physics_impulse_coeff{ get; set; }
	public int lifetime_add{ get; set; }
	public string sprite{ get; set; }
	public string extra_entities{ get; set; }
	public string game_effect_entities{ get; set; }
	public string sound_loop_tag{ get; set; }
	public string projectile_file{ get; set; }

}