namespace GeneratedNoitaClasses;
public class ConfigGunActionInfo :  iNoitaType<ConfigGunActionInfo>{
	public NoitaString action_id { get; set; } = new();
	public NoitaString action_name { get; set; } = new();
	public NoitaString action_description { get; set; } = new();
	public NoitaString action_sprite_filename { get; set; } = new();
	public NoitaString action_unidentified_sprite_filename { get; set; } = new();
	public NoitaInt action_type { get; set; } = new();
	public NoitaString action_spawn_level { get; set; } = new();
	public NoitaString action_spawn_probability { get; set; } = new();
	public NoitaString action_spawn_requires_flag { get; set; } = new();
	public NoitaBool action_spawn_manual_unlock { get; set; } = new();
	public NoitaInt action_max_uses { get; set; } = new();
	public NoitaString custom_xml_file { get; set; } = new();
	public NoitaFloat action_mana_drain { get; set; } = new();
	public NoitaBool action_is_dangerous_blast { get; set; } = new();
	public NoitaInt action_draw_many_count { get; set; } = new();
	public NoitaBool action_ai_never_uses { get; set; } = new();
	public NoitaBool action_never_unlimited { get; set; } = new();
	public NoitaBool state_shuffled { get; set; } = new();
	public NoitaInt state_cards_drawn { get; set; } = new();
	public NoitaBool state_discarded_action { get; set; } = new();
	public NoitaBool state_destroyed_action { get; set; } = new();
	public NoitaInt fire_rate_wait { get; set; } = new();
	public NoitaFloat speed_multiplier { get; set; } = new();
	public NoitaFloat child_speed_multiplier { get; set; } = new();
	public NoitaFloat dampening { get; set; } = new();
	public NoitaFloat explosion_radius { get; set; } = new();
	public NoitaFloat spread_degrees { get; set; } = new();
	public NoitaFloat pattern_degrees { get; set; } = new();
	public NoitaFloat screenshake { get; set; } = new();
	public NoitaFloat recoil { get; set; } = new();
	public NoitaFloat damage_melee_add { get; set; } = new();
	public NoitaFloat damage_projectile_add { get; set; } = new();
	public NoitaFloat damage_electricity_add { get; set; } = new();
	public NoitaFloat damage_fire_add { get; set; } = new();
	public NoitaFloat damage_explosion_add { get; set; } = new();
	public NoitaFloat damage_ice_add { get; set; } = new();
	public NoitaFloat damage_slice_add { get; set; } = new();
	public NoitaFloat damage_healing_add { get; set; } = new();
	public NoitaFloat damage_curse_add { get; set; } = new();
	public NoitaFloat damage_drill_add { get; set; } = new();
	public NoitaFloat damage_null_all { get; set; } = new();
	public NoitaInt damage_critical_chance { get; set; } = new();
	public NoitaFloat damage_critical_multiplier { get; set; } = new();
	public NoitaFloat explosion_damage_to_materials { get; set; } = new();
	public NoitaFloat knockback_force { get; set; } = new();
	public NoitaInt reload_time { get; set; } = new();
	public NoitaInt lightning_count { get; set; } = new();
	public NoitaString material { get; set; } = new();
	public NoitaInt material_amount { get; set; } = new();
	public NoitaString trail_material { get; set; } = new();
	public NoitaInt trail_material_amount { get; set; } = new();
	public NoitaInt bounces { get; set; } = new();
	public NoitaFloat gravity { get; set; } = new();
	public NoitaFloat light { get; set; } = new();
	public NoitaFloat blood_count_multiplier { get; set; } = new();
	public NoitaInt gore_particles { get; set; } = new();
	public NoitaInt ragdoll_fx { get; set; } = new();
	public NoitaBool friendly_fire { get; set; } = new();
	public NoitaFloat physics_impulse_coeff { get; set; } = new();
	public NoitaInt lifetime_add { get; set; } = new();
	public NoitaString sprite { get; set; } = new();
	public NoitaString extra_entities { get; set; } = new();
	public NoitaString game_effect_entities { get; set; } = new();
	public NoitaString sound_loop_tag { get; set; } = new();
	public NoitaString projectile_file { get; set; } = new();

    public void Read(NoitaStream s){
		action_id.Read(s);
		action_name.Read(s);
		action_description.Read(s);
		action_sprite_filename.Read(s);
		action_unidentified_sprite_filename.Read(s);
		action_type.Read(s);
		action_spawn_level.Read(s);
		action_spawn_probability.Read(s);
		action_spawn_requires_flag.Read(s);
		action_spawn_manual_unlock.Read(s);
		action_max_uses.Read(s);
		custom_xml_file.Read(s);
		action_mana_drain.Read(s);
		action_is_dangerous_blast.Read(s);
		action_draw_many_count.Read(s);
		action_ai_never_uses.Read(s);
		action_never_unlimited.Read(s);
		state_shuffled.Read(s);
		state_cards_drawn.Read(s);
		state_discarded_action.Read(s);
		state_destroyed_action.Read(s);
		fire_rate_wait.Read(s);
		speed_multiplier.Read(s);
		child_speed_multiplier.Read(s);
		dampening.Read(s);
		explosion_radius.Read(s);
		spread_degrees.Read(s);
		pattern_degrees.Read(s);
		screenshake.Read(s);
		recoil.Read(s);
		damage_melee_add.Read(s);
		damage_projectile_add.Read(s);
		damage_electricity_add.Read(s);
		damage_fire_add.Read(s);
		damage_explosion_add.Read(s);
		damage_ice_add.Read(s);
		damage_slice_add.Read(s);
		damage_healing_add.Read(s);
		damage_curse_add.Read(s);
		damage_drill_add.Read(s);
		damage_null_all.Read(s);
		damage_critical_chance.Read(s);
		damage_critical_multiplier.Read(s);
		explosion_damage_to_materials.Read(s);
		knockback_force.Read(s);
		reload_time.Read(s);
		lightning_count.Read(s);
		material.Read(s);
		material_amount.Read(s);
		trail_material.Read(s);
		trail_material_amount.Read(s);
		bounces.Read(s);
		gravity.Read(s);
		light.Read(s);
		blood_count_multiplier.Read(s);
		gore_particles.Read(s);
		ragdoll_fx.Read(s);
		friendly_fire.Read(s);
		physics_impulse_coeff.Read(s);
		lifetime_add.Read(s);
		sprite.Read(s);
		extra_entities.Read(s);
		game_effect_entities.Read(s);
		sound_loop_tag.Read(s);
		projectile_file.Read(s);

    }
    public void Write(NoitaStream s){
		action_id.Write(s);
		action_name.Write(s);
		action_description.Write(s);
		action_sprite_filename.Write(s);
		action_unidentified_sprite_filename.Write(s);
		action_type.Write(s);
		action_spawn_level.Write(s);
		action_spawn_probability.Write(s);
		action_spawn_requires_flag.Write(s);
		action_spawn_manual_unlock.Write(s);
		action_max_uses.Write(s);
		custom_xml_file.Write(s);
		action_mana_drain.Write(s);
		action_is_dangerous_blast.Write(s);
		action_draw_many_count.Write(s);
		action_ai_never_uses.Write(s);
		action_never_unlimited.Write(s);
		state_shuffled.Write(s);
		state_cards_drawn.Write(s);
		state_discarded_action.Write(s);
		state_destroyed_action.Write(s);
		fire_rate_wait.Write(s);
		speed_multiplier.Write(s);
		child_speed_multiplier.Write(s);
		dampening.Write(s);
		explosion_radius.Write(s);
		spread_degrees.Write(s);
		pattern_degrees.Write(s);
		screenshake.Write(s);
		recoil.Write(s);
		damage_melee_add.Write(s);
		damage_projectile_add.Write(s);
		damage_electricity_add.Write(s);
		damage_fire_add.Write(s);
		damage_explosion_add.Write(s);
		damage_ice_add.Write(s);
		damage_slice_add.Write(s);
		damage_healing_add.Write(s);
		damage_curse_add.Write(s);
		damage_drill_add.Write(s);
		damage_null_all.Write(s);
		damage_critical_chance.Write(s);
		damage_critical_multiplier.Write(s);
		explosion_damage_to_materials.Write(s);
		knockback_force.Write(s);
		reload_time.Write(s);
		lightning_count.Write(s);
		material.Write(s);
		material_amount.Write(s);
		trail_material.Write(s);
		trail_material_amount.Write(s);
		bounces.Write(s);
		gravity.Write(s);
		light.Write(s);
		blood_count_multiplier.Write(s);
		gore_particles.Write(s);
		ragdoll_fx.Write(s);
		friendly_fire.Write(s);
		physics_impulse_coeff.Write(s);
		lifetime_add.Write(s);
		sprite.Write(s);
		extra_entities.Write(s);
		game_effect_entities.Write(s);
		sound_loop_tag.Write(s);
		projectile_file.Write(s);

    }
}