namespace GeneratedNoitaClasses;
public class ConfigExplosion{
	public bool never_cache{ get; set; }
	public float explosion_radius{ get; set; }
	public string explosion_sprite{ get; set; }
	public bool explosion_sprite_emissive{ get; set; }
	public bool explosion_sprite_additive{ get; set; }
	public bool explosion_sprite_random_rotation{ get; set; }
	public float explosion_sprite_lifetime{ get; set; }
	public float damage{ get; set; }
	public ConfigDamageCritical damage_critical{ get; set; }
	public float camera_shake{ get; set; }
	public bool particle_effect{ get; set; }
	public string load_this_entity{ get; set; }
	public bool light_enabled{ get; set; }
	public float light_fade_time{ get; set; }
	public UInt32 light_r{ get; set; }
	public UInt32 light_g{ get; set; }
	public UInt32 light_b{ get; set; }
	public float light_radius_coeff{ get; set; }
	public bool hole_enabled{ get; set; }
	public bool destroy_non_platform_solid_enabled{ get; set; }
	public int electricity_count{ get; set; }
	public int min_radius_for_cracks{ get; set; }
	public int crack_count{ get; set; }
	public float knockback_force{ get; set; }
	public bool hole_destroy_liquid{ get; set; }
	public bool hole_destroy_physics_dynamic{ get; set; }
	public string create_cell_material{ get; set; }
	public int create_cell_probability{ get; set; }
	public int background_lightning_count{ get; set; }
	public string spark_material{ get; set; }
	public int material_sparks_min_hp{ get; set; }
	public int material_sparks_probability{ get; set; }
	public int material_sparks_count_min{ get; set; }
	public int material_sparks_count_max{ get; set; }
	public bool material_sparks_enabled{ get; set; }
	public bool material_sparks_real{ get; set; }
	public bool material_sparks_scale_with_hp{ get; set; }
	public bool sparks_enabled{ get; set; }
	public int sparks_count_min{ get; set; }
	public int sparks_count_max{ get; set; }
	public float sparks_inner_radius_coeff{ get; set; }
	public bool stains_enabled{ get; set; }
	public float stains_radius{ get; set; }
	public int ray_energy{ get; set; }
	public int max_durability_to_destroy{ get; set; }
	public int gore_particle_count{ get; set; }
	public bool shake_vegetation{ get; set; }
	public bool damage_mortals{ get; set; }
	public bool physics_throw_enabled{ get; set; }
	public ValueRange physics_explosion_power{ get; set; }
	public float physics_multiplier_ragdoll_force{ get; set; }
	public float cell_explosion_power{ get; set; }
	public float cell_explosion_radius_min{ get; set; }
	public float cell_explosion_radius_max{ get; set; }
	public float cell_explosion_velocity_min{ get; set; }
	public float cell_explosion_damage_required{ get; set; }
	public float cell_explosion_probability{ get; set; }
	public float cell_explosion_power_ragdoll_coeff{ get; set; }
	public bool pixel_sprites_enabled{ get; set; }
	public bool is_digger{ get; set; }
	public bool audio_enabled{ get; set; }
	public string audio_event_name{ get; set; }
	public float audio_liquid_amount_normalized{ get; set; }
	public ValueRangeInt delay{ get; set; }
	public int explosion_delay_id{ get; set; }
	public bool not_scaled_by_gamefx{ get; set; }

}