namespace GeneratedNoitaClasses;
public class ConfigExplosion :  iNoitaType<ConfigExplosion>{
	public NoitaBool never_cache { get; set; } = new();
	public NoitaFloat explosion_radius { get; set; } = new();
	public NoitaString explosion_sprite { get; set; } = new();
	public NoitaBool explosion_sprite_emissive { get; set; } = new();
	public NoitaBool explosion_sprite_additive { get; set; } = new();
	public NoitaBool explosion_sprite_random_rotation { get; set; } = new();
	public NoitaFloat explosion_sprite_lifetime { get; set; } = new();
	public NoitaFloat damage { get; set; } = new();
	public ConfigDamageCritical damage_critical { get; set; } = new();
	public NoitaFloat camera_shake { get; set; } = new();
	public NoitaBool particle_effect { get; set; } = new();
	public NoitaString load_this_entity { get; set; } = new();
	public NoitaBool light_enabled { get; set; } = new();
	public NoitaFloat light_fade_time { get; set; } = new();
	public NoitaUInt light_r { get; set; } = new();
	public NoitaUInt light_g { get; set; } = new();
	public NoitaUInt light_b { get; set; } = new();
	public NoitaFloat light_radius_coeff { get; set; } = new();
	public NoitaBool hole_enabled { get; set; } = new();
	public NoitaBool destroy_non_platform_solid_enabled { get; set; } = new();
	public NoitaInt electricity_count { get; set; } = new();
	public NoitaInt min_radius_for_cracks { get; set; } = new();
	public NoitaInt crack_count { get; set; } = new();
	public NoitaFloat knockback_force { get; set; } = new();
	public NoitaBool hole_destroy_liquid { get; set; } = new();
	public NoitaBool hole_destroy_physics_dynamic { get; set; } = new();
	public NoitaString create_cell_material { get; set; } = new();
	public NoitaInt create_cell_probability { get; set; } = new();
	public NoitaInt background_lightning_count { get; set; } = new();
	public NoitaString spark_material { get; set; } = new();
	public NoitaInt material_sparks_min_hp { get; set; } = new();
	public NoitaInt material_sparks_probability { get; set; } = new();
	public NoitaInt material_sparks_count_min { get; set; } = new();
	public NoitaInt material_sparks_count_max { get; set; } = new();
	public NoitaBool material_sparks_enabled { get; set; } = new();
	public NoitaBool material_sparks_real { get; set; } = new();
	public NoitaBool material_sparks_scale_with_hp { get; set; } = new();
	public NoitaBool sparks_enabled { get; set; } = new();
	public NoitaInt sparks_count_min { get; set; } = new();
	public NoitaInt sparks_count_max { get; set; } = new();
	public NoitaFloat sparks_inner_radius_coeff { get; set; } = new();
	public NoitaBool stains_enabled { get; set; } = new();
	public NoitaFloat stains_radius { get; set; } = new();
	public NoitaInt ray_energy { get; set; } = new();
	public NoitaInt max_durability_to_destroy { get; set; } = new();
	public NoitaInt gore_particle_count { get; set; } = new();
	public NoitaBool shake_vegetation { get; set; } = new();
	public NoitaBool damage_mortals { get; set; } = new();
	public NoitaBool physics_throw_enabled { get; set; } = new();
	public ValueRange physics_explosion_power { get; set; } = new();
	public NoitaFloat physics_multiplier_ragdoll_force { get; set; } = new();
	public NoitaFloat cell_explosion_power { get; set; } = new();
	public NoitaFloat cell_explosion_radius_min { get; set; } = new();
	public NoitaFloat cell_explosion_radius_max { get; set; } = new();
	public NoitaFloat cell_explosion_velocity_min { get; set; } = new();
	public NoitaFloat cell_explosion_damage_required { get; set; } = new();
	public NoitaFloat cell_explosion_probability { get; set; } = new();
	public NoitaFloat cell_explosion_power_ragdoll_coeff { get; set; } = new();
	public NoitaBool pixel_sprites_enabled { get; set; } = new();
	public NoitaBool is_digger { get; set; } = new();
	public NoitaBool audio_enabled { get; set; } = new();
	public NoitaString audio_event_name { get; set; } = new();
	public NoitaFloat audio_liquid_amount_normalized { get; set; } = new();
	public ValueRangeInt delay { get; set; } = new();
	public NoitaInt explosion_delay_id { get; set; } = new();
	public NoitaBool not_scaled_by_gamefx { get; set; } = new();

    public void Read(NoitaStream s){
		never_cache.Read(s);
		explosion_radius.Read(s);
		explosion_sprite.Read(s);
		explosion_sprite_emissive.Read(s);
		explosion_sprite_additive.Read(s);
		explosion_sprite_random_rotation.Read(s);
		explosion_sprite_lifetime.Read(s);
		damage.Read(s);
		damage_critical.Read(s);
		camera_shake.Read(s);
		particle_effect.Read(s);
		load_this_entity.Read(s);
		light_enabled.Read(s);
		light_fade_time.Read(s);
		light_r.Read(s);
		light_g.Read(s);
		light_b.Read(s);
		light_radius_coeff.Read(s);
		hole_enabled.Read(s);
		destroy_non_platform_solid_enabled.Read(s);
		electricity_count.Read(s);
		min_radius_for_cracks.Read(s);
		crack_count.Read(s);
		knockback_force.Read(s);
		hole_destroy_liquid.Read(s);
		hole_destroy_physics_dynamic.Read(s);
		create_cell_material.Read(s);
		create_cell_probability.Read(s);
		background_lightning_count.Read(s);
		spark_material.Read(s);
		material_sparks_min_hp.Read(s);
		material_sparks_probability.Read(s);
		material_sparks_count_min.Read(s);
		material_sparks_count_max.Read(s);
		material_sparks_enabled.Read(s);
		material_sparks_real.Read(s);
		material_sparks_scale_with_hp.Read(s);
		sparks_enabled.Read(s);
		sparks_count_min.Read(s);
		sparks_count_max.Read(s);
		sparks_inner_radius_coeff.Read(s);
		stains_enabled.Read(s);
		stains_radius.Read(s);
		ray_energy.Read(s);
		max_durability_to_destroy.Read(s);
		gore_particle_count.Read(s);
		shake_vegetation.Read(s);
		damage_mortals.Read(s);
		physics_throw_enabled.Read(s);
		physics_explosion_power.Read(s);
		physics_multiplier_ragdoll_force.Read(s);
		cell_explosion_power.Read(s);
		cell_explosion_radius_min.Read(s);
		cell_explosion_radius_max.Read(s);
		cell_explosion_velocity_min.Read(s);
		cell_explosion_damage_required.Read(s);
		cell_explosion_probability.Read(s);
		cell_explosion_power_ragdoll_coeff.Read(s);
		pixel_sprites_enabled.Read(s);
		is_digger.Read(s);
		audio_enabled.Read(s);
		audio_event_name.Read(s);
		audio_liquid_amount_normalized.Read(s);
		delay.Read(s);
		explosion_delay_id.Read(s);
		not_scaled_by_gamefx.Read(s);

    }
    public void Write(NoitaStream s){
		never_cache.Write(s);
		explosion_radius.Write(s);
		explosion_sprite.Write(s);
		explosion_sprite_emissive.Write(s);
		explosion_sprite_additive.Write(s);
		explosion_sprite_random_rotation.Write(s);
		explosion_sprite_lifetime.Write(s);
		damage.Write(s);
		damage_critical.Write(s);
		camera_shake.Write(s);
		particle_effect.Write(s);
		load_this_entity.Write(s);
		light_enabled.Write(s);
		light_fade_time.Write(s);
		light_r.Write(s);
		light_g.Write(s);
		light_b.Write(s);
		light_radius_coeff.Write(s);
		hole_enabled.Write(s);
		destroy_non_platform_solid_enabled.Write(s);
		electricity_count.Write(s);
		min_radius_for_cracks.Write(s);
		crack_count.Write(s);
		knockback_force.Write(s);
		hole_destroy_liquid.Write(s);
		hole_destroy_physics_dynamic.Write(s);
		create_cell_material.Write(s);
		create_cell_probability.Write(s);
		background_lightning_count.Write(s);
		spark_material.Write(s);
		material_sparks_min_hp.Write(s);
		material_sparks_probability.Write(s);
		material_sparks_count_min.Write(s);
		material_sparks_count_max.Write(s);
		material_sparks_enabled.Write(s);
		material_sparks_real.Write(s);
		material_sparks_scale_with_hp.Write(s);
		sparks_enabled.Write(s);
		sparks_count_min.Write(s);
		sparks_count_max.Write(s);
		sparks_inner_radius_coeff.Write(s);
		stains_enabled.Write(s);
		stains_radius.Write(s);
		ray_energy.Write(s);
		max_durability_to_destroy.Write(s);
		gore_particle_count.Write(s);
		shake_vegetation.Write(s);
		damage_mortals.Write(s);
		physics_throw_enabled.Write(s);
		physics_explosion_power.Write(s);
		physics_multiplier_ragdoll_force.Write(s);
		cell_explosion_power.Write(s);
		cell_explosion_radius_min.Write(s);
		cell_explosion_radius_max.Write(s);
		cell_explosion_velocity_min.Write(s);
		cell_explosion_damage_required.Write(s);
		cell_explosion_probability.Write(s);
		cell_explosion_power_ragdoll_coeff.Write(s);
		pixel_sprites_enabled.Write(s);
		is_digger.Write(s);
		audio_enabled.Write(s);
		audio_event_name.Write(s);
		audio_liquid_amount_normalized.Write(s);
		delay.Write(s);
		explosion_delay_id.Write(s);
		not_scaled_by_gamefx.Write(s);

    }
}