from dataclasses import dataclass, field
from BasicNoitaTypes import NoitaString
from BasicNoitaTypes import NoitaInt
from BasicNoitaTypes import NoitaBool
from BasicNoitaTypes import NoitaFloat

from NoitaStream import NoitaStream
@dataclass
class ConfigGunActionInfo:
    action_id:NoitaString = field(default_factory=NoitaString)
    action_name:NoitaString = field(default_factory=NoitaString)
    action_description:NoitaString = field(default_factory=NoitaString)
    action_sprite_filename:NoitaString = field(default_factory=NoitaString)
    action_unidentified_sprite_filename:NoitaString = field(default_factory=NoitaString)
    action_type:NoitaInt = field(default_factory=NoitaInt)
    action_spawn_level:NoitaString = field(default_factory=NoitaString)
    action_spawn_probability:NoitaString = field(default_factory=NoitaString)
    action_spawn_requires_flag:NoitaString = field(default_factory=NoitaString)
    action_spawn_manual_unlock:NoitaBool = field(default_factory=NoitaBool)
    action_max_uses:NoitaInt = field(default_factory=NoitaInt)
    custom_xml_file:NoitaString = field(default_factory=NoitaString)
    action_mana_drain:NoitaFloat = field(default_factory=NoitaFloat)
    action_is_dangerous_blast:NoitaBool = field(default_factory=NoitaBool)
    action_draw_many_count:NoitaInt = field(default_factory=NoitaInt)
    action_ai_never_uses:NoitaBool = field(default_factory=NoitaBool)
    action_never_unlimited:NoitaBool = field(default_factory=NoitaBool)
    state_shuffled:NoitaBool = field(default_factory=NoitaBool)
    state_cards_drawn:NoitaInt = field(default_factory=NoitaInt)
    state_discarded_action:NoitaBool = field(default_factory=NoitaBool)
    state_destroyed_action:NoitaBool = field(default_factory=NoitaBool)
    fire_rate_wait:NoitaInt = field(default_factory=NoitaInt)
    speed_multiplier:NoitaFloat = field(default_factory=NoitaFloat)
    child_speed_multiplier:NoitaFloat = field(default_factory=NoitaFloat)
    dampening:NoitaFloat = field(default_factory=NoitaFloat)
    explosion_radius:NoitaFloat = field(default_factory=NoitaFloat)
    spread_degrees:NoitaFloat = field(default_factory=NoitaFloat)
    pattern_degrees:NoitaFloat = field(default_factory=NoitaFloat)
    screenshake:NoitaFloat = field(default_factory=NoitaFloat)
    recoil:NoitaFloat = field(default_factory=NoitaFloat)
    damage_melee_add:NoitaFloat = field(default_factory=NoitaFloat)
    damage_projectile_add:NoitaFloat = field(default_factory=NoitaFloat)
    damage_electricity_add:NoitaFloat = field(default_factory=NoitaFloat)
    damage_fire_add:NoitaFloat = field(default_factory=NoitaFloat)
    damage_explosion_add:NoitaFloat = field(default_factory=NoitaFloat)
    damage_ice_add:NoitaFloat = field(default_factory=NoitaFloat)
    damage_slice_add:NoitaFloat = field(default_factory=NoitaFloat)
    damage_healing_add:NoitaFloat = field(default_factory=NoitaFloat)
    damage_curse_add:NoitaFloat = field(default_factory=NoitaFloat)
    damage_drill_add:NoitaFloat = field(default_factory=NoitaFloat)
    damage_null_all:NoitaFloat = field(default_factory=NoitaFloat)
    damage_critical_chance:NoitaInt = field(default_factory=NoitaInt)
    damage_critical_multiplier:NoitaFloat = field(default_factory=NoitaFloat)
    explosion_damage_to_materials:NoitaFloat = field(default_factory=NoitaFloat)
    knockback_force:NoitaFloat = field(default_factory=NoitaFloat)
    reload_time:NoitaInt = field(default_factory=NoitaInt)
    lightning_count:NoitaInt = field(default_factory=NoitaInt)
    material:NoitaString = field(default_factory=NoitaString)
    material_amount:NoitaInt = field(default_factory=NoitaInt)
    trail_material:NoitaString = field(default_factory=NoitaString)
    trail_material_amount:NoitaInt = field(default_factory=NoitaInt)
    bounces:NoitaInt = field(default_factory=NoitaInt)
    gravity:NoitaFloat = field(default_factory=NoitaFloat)
    light:NoitaFloat = field(default_factory=NoitaFloat)
    blood_count_multiplier:NoitaFloat = field(default_factory=NoitaFloat)
    gore_particles:NoitaInt = field(default_factory=NoitaInt)
    ragdoll_fx:NoitaInt = field(default_factory=NoitaInt)
    friendly_fire:NoitaBool = field(default_factory=NoitaBool)
    physics_impulse_coeff:NoitaFloat = field(default_factory=NoitaFloat)
    lifetime_add:NoitaInt = field(default_factory=NoitaInt)
    sprite:NoitaString = field(default_factory=NoitaString)
    extra_entities:NoitaString = field(default_factory=NoitaString)
    game_effect_entities:NoitaString = field(default_factory=NoitaString)
    sound_loop_tag:NoitaString = field(default_factory=NoitaString)
    projectile_file:NoitaString = field(default_factory=NoitaString)
    
    def Read(self, s:NoitaStream):
        self.action_id.Read(s)
        self.action_name.Read(s)
        self.action_description.Read(s)
        self.action_sprite_filename.Read(s)
        self.action_unidentified_sprite_filename.Read(s)
        self.action_type.Read(s)
        self.action_spawn_level.Read(s)
        self.action_spawn_probability.Read(s)
        self.action_spawn_requires_flag.Read(s)
        self.action_spawn_manual_unlock.Read(s)
        self.action_max_uses.Read(s)
        self.custom_xml_file.Read(s)
        self.action_mana_drain.Read(s)
        self.action_is_dangerous_blast.Read(s)
        self.action_draw_many_count.Read(s)
        self.action_ai_never_uses.Read(s)
        self.action_never_unlimited.Read(s)
        self.state_shuffled.Read(s)
        self.state_cards_drawn.Read(s)
        self.state_discarded_action.Read(s)
        self.state_destroyed_action.Read(s)
        self.fire_rate_wait.Read(s)
        self.speed_multiplier.Read(s)
        self.child_speed_multiplier.Read(s)
        self.dampening.Read(s)
        self.explosion_radius.Read(s)
        self.spread_degrees.Read(s)
        self.pattern_degrees.Read(s)
        self.screenshake.Read(s)
        self.recoil.Read(s)
        self.damage_melee_add.Read(s)
        self.damage_projectile_add.Read(s)
        self.damage_electricity_add.Read(s)
        self.damage_fire_add.Read(s)
        self.damage_explosion_add.Read(s)
        self.damage_ice_add.Read(s)
        self.damage_slice_add.Read(s)
        self.damage_healing_add.Read(s)
        self.damage_curse_add.Read(s)
        self.damage_drill_add.Read(s)
        self.damage_null_all.Read(s)
        self.damage_critical_chance.Read(s)
        self.damage_critical_multiplier.Read(s)
        self.explosion_damage_to_materials.Read(s)
        self.knockback_force.Read(s)
        self.reload_time.Read(s)
        self.lightning_count.Read(s)
        self.material.Read(s)
        self.material_amount.Read(s)
        self.trail_material.Read(s)
        self.trail_material_amount.Read(s)
        self.bounces.Read(s)
        self.gravity.Read(s)
        self.light.Read(s)
        self.blood_count_multiplier.Read(s)
        self.gore_particles.Read(s)
        self.ragdoll_fx.Read(s)
        self.friendly_fire.Read(s)
        self.physics_impulse_coeff.Read(s)
        self.lifetime_add.Read(s)
        self.sprite.Read(s)
        self.extra_entities.Read(s)
        self.game_effect_entities.Read(s)
        self.sound_loop_tag.Read(s)
        self.projectile_file.Read(s)
    
    def Write(self, s:NoitaStream):
        self.action_id.Write(s)
        self.action_name.Write(s)
        self.action_description.Write(s)
        self.action_sprite_filename.Write(s)
        self.action_unidentified_sprite_filename.Write(s)
        self.action_type.Write(s)
        self.action_spawn_level.Write(s)
        self.action_spawn_probability.Write(s)
        self.action_spawn_requires_flag.Write(s)
        self.action_spawn_manual_unlock.Write(s)
        self.action_max_uses.Write(s)
        self.custom_xml_file.Write(s)
        self.action_mana_drain.Write(s)
        self.action_is_dangerous_blast.Write(s)
        self.action_draw_many_count.Write(s)
        self.action_ai_never_uses.Write(s)
        self.action_never_unlimited.Write(s)
        self.state_shuffled.Write(s)
        self.state_cards_drawn.Write(s)
        self.state_discarded_action.Write(s)
        self.state_destroyed_action.Write(s)
        self.fire_rate_wait.Write(s)
        self.speed_multiplier.Write(s)
        self.child_speed_multiplier.Write(s)
        self.dampening.Write(s)
        self.explosion_radius.Write(s)
        self.spread_degrees.Write(s)
        self.pattern_degrees.Write(s)
        self.screenshake.Write(s)
        self.recoil.Write(s)
        self.damage_melee_add.Write(s)
        self.damage_projectile_add.Write(s)
        self.damage_electricity_add.Write(s)
        self.damage_fire_add.Write(s)
        self.damage_explosion_add.Write(s)
        self.damage_ice_add.Write(s)
        self.damage_slice_add.Write(s)
        self.damage_healing_add.Write(s)
        self.damage_curse_add.Write(s)
        self.damage_drill_add.Write(s)
        self.damage_null_all.Write(s)
        self.damage_critical_chance.Write(s)
        self.damage_critical_multiplier.Write(s)
        self.explosion_damage_to_materials.Write(s)
        self.knockback_force.Write(s)
        self.reload_time.Write(s)
        self.lightning_count.Write(s)
        self.material.Write(s)
        self.material_amount.Write(s)
        self.trail_material.Write(s)
        self.trail_material_amount.Write(s)
        self.bounces.Write(s)
        self.gravity.Write(s)
        self.light.Write(s)
        self.blood_count_multiplier.Write(s)
        self.gore_particles.Write(s)
        self.ragdoll_fx.Write(s)
        self.friendly_fire.Write(s)
        self.physics_impulse_coeff.Write(s)
        self.lifetime_add.Write(s)
        self.sprite.Write(s)
        self.extra_entities.Write(s)
        self.game_effect_entities.Write(s)
        self.sound_loop_tag.Write(s)
        self.projectile_file.Write(s)

