from dataclasses import dataclass, field
from BasicNoitaTypes import NoitaBool
from BasicNoitaTypes import NoitaFloat
from BasicNoitaTypes import NoitaString
from GeneratedClasses.ConfigDamageCritical import ConfigDamageCritical
from BasicNoitaTypes import NoitaUInt
from BasicNoitaTypes import NoitaInt
from GeneratedClasses.ValueRange import ValueRange
from GeneratedClasses.ValueRangeInt import ValueRangeInt

from NoitaStream import NoitaStream
@dataclass
class ConfigExplosion:
    never_cache:NoitaBool = field(default_factory=NoitaBool)
    explosion_radius:NoitaFloat = field(default_factory=NoitaFloat)
    explosion_sprite:NoitaString = field(default_factory=NoitaString)
    explosion_sprite_emissive:NoitaBool = field(default_factory=NoitaBool)
    explosion_sprite_additive:NoitaBool = field(default_factory=NoitaBool)
    explosion_sprite_random_rotation:NoitaBool = field(default_factory=NoitaBool)
    explosion_sprite_lifetime:NoitaFloat = field(default_factory=NoitaFloat)
    damage:NoitaFloat = field(default_factory=NoitaFloat)
    damage_critical:ConfigDamageCritical = field(default_factory=ConfigDamageCritical)
    camera_shake:NoitaFloat = field(default_factory=NoitaFloat)
    particle_effect:NoitaBool = field(default_factory=NoitaBool)
    load_this_entity:NoitaString = field(default_factory=NoitaString)
    light_enabled:NoitaBool = field(default_factory=NoitaBool)
    light_fade_time:NoitaFloat = field(default_factory=NoitaFloat)
    light_r:NoitaUInt = field(default_factory=NoitaUInt)
    light_g:NoitaUInt = field(default_factory=NoitaUInt)
    light_b:NoitaUInt = field(default_factory=NoitaUInt)
    light_radius_coeff:NoitaFloat = field(default_factory=NoitaFloat)
    hole_enabled:NoitaBool = field(default_factory=NoitaBool)
    destroy_non_platform_solid_enabled:NoitaBool = field(default_factory=NoitaBool)
    electricity_count:NoitaInt = field(default_factory=NoitaInt)
    min_radius_for_cracks:NoitaInt = field(default_factory=NoitaInt)
    crack_count:NoitaInt = field(default_factory=NoitaInt)
    knockback_force:NoitaFloat = field(default_factory=NoitaFloat)
    hole_destroy_liquid:NoitaBool = field(default_factory=NoitaBool)
    hole_destroy_physics_dynamic:NoitaBool = field(default_factory=NoitaBool)
    create_cell_material:NoitaString = field(default_factory=NoitaString)
    create_cell_probability:NoitaInt = field(default_factory=NoitaInt)
    background_lightning_count:NoitaInt = field(default_factory=NoitaInt)
    spark_material:NoitaString = field(default_factory=NoitaString)
    material_sparks_min_hp:NoitaInt = field(default_factory=NoitaInt)
    material_sparks_probability:NoitaInt = field(default_factory=NoitaInt)
    material_sparks_count_min:NoitaInt = field(default_factory=NoitaInt)
    material_sparks_count_max:NoitaInt = field(default_factory=NoitaInt)
    material_sparks_enabled:NoitaBool = field(default_factory=NoitaBool)
    material_sparks_real:NoitaBool = field(default_factory=NoitaBool)
    material_sparks_scale_with_hp:NoitaBool = field(default_factory=NoitaBool)
    sparks_enabled:NoitaBool = field(default_factory=NoitaBool)
    sparks_count_min:NoitaInt = field(default_factory=NoitaInt)
    sparks_count_max:NoitaInt = field(default_factory=NoitaInt)
    sparks_inner_radius_coeff:NoitaFloat = field(default_factory=NoitaFloat)
    stains_enabled:NoitaBool = field(default_factory=NoitaBool)
    stains_radius:NoitaFloat = field(default_factory=NoitaFloat)
    ray_energy:NoitaInt = field(default_factory=NoitaInt)
    max_durability_to_destroy:NoitaInt = field(default_factory=NoitaInt)
    gore_particle_count:NoitaInt = field(default_factory=NoitaInt)
    shake_vegetation:NoitaBool = field(default_factory=NoitaBool)
    damage_mortals:NoitaBool = field(default_factory=NoitaBool)
    physics_throw_enabled:NoitaBool = field(default_factory=NoitaBool)
    physics_explosion_power:ValueRange = field(default_factory=ValueRange)
    physics_multiplier_ragdoll_force:NoitaFloat = field(default_factory=NoitaFloat)
    cell_explosion_power:NoitaFloat = field(default_factory=NoitaFloat)
    cell_explosion_radius_min:NoitaFloat = field(default_factory=NoitaFloat)
    cell_explosion_radius_max:NoitaFloat = field(default_factory=NoitaFloat)
    cell_explosion_velocity_min:NoitaFloat = field(default_factory=NoitaFloat)
    cell_explosion_damage_required:NoitaFloat = field(default_factory=NoitaFloat)
    cell_explosion_probability:NoitaFloat = field(default_factory=NoitaFloat)
    cell_explosion_power_ragdoll_coeff:NoitaFloat = field(default_factory=NoitaFloat)
    pixel_sprites_enabled:NoitaBool = field(default_factory=NoitaBool)
    is_digger:NoitaBool = field(default_factory=NoitaBool)
    audio_enabled:NoitaBool = field(default_factory=NoitaBool)
    audio_event_name:NoitaString = field(default_factory=NoitaString)
    audio_liquid_amount_normalized:NoitaFloat = field(default_factory=NoitaFloat)
    delay:ValueRangeInt = field(default_factory=ValueRangeInt)
    explosion_delay_id:NoitaInt = field(default_factory=NoitaInt)
    not_scaled_by_gamefx:NoitaBool = field(default_factory=NoitaBool)
    
    def Read(self, s:NoitaStream):
        self.never_cache.Read(s)
        self.explosion_radius.Read(s)
        self.explosion_sprite.Read(s)
        self.explosion_sprite_emissive.Read(s)
        self.explosion_sprite_additive.Read(s)
        self.explosion_sprite_random_rotation.Read(s)
        self.explosion_sprite_lifetime.Read(s)
        self.damage.Read(s)
        self.damage_critical.Read(s)
        self.camera_shake.Read(s)
        self.particle_effect.Read(s)
        self.load_this_entity.Read(s)
        self.light_enabled.Read(s)
        self.light_fade_time.Read(s)
        self.light_r.Read(s)
        self.light_g.Read(s)
        self.light_b.Read(s)
        self.light_radius_coeff.Read(s)
        self.hole_enabled.Read(s)
        self.destroy_non_platform_solid_enabled.Read(s)
        self.electricity_count.Read(s)
        self.min_radius_for_cracks.Read(s)
        self.crack_count.Read(s)
        self.knockback_force.Read(s)
        self.hole_destroy_liquid.Read(s)
        self.hole_destroy_physics_dynamic.Read(s)
        self.create_cell_material.Read(s)
        self.create_cell_probability.Read(s)
        self.background_lightning_count.Read(s)
        self.spark_material.Read(s)
        self.material_sparks_min_hp.Read(s)
        self.material_sparks_probability.Read(s)
        self.material_sparks_count_min.Read(s)
        self.material_sparks_count_max.Read(s)
        self.material_sparks_enabled.Read(s)
        self.material_sparks_real.Read(s)
        self.material_sparks_scale_with_hp.Read(s)
        self.sparks_enabled.Read(s)
        self.sparks_count_min.Read(s)
        self.sparks_count_max.Read(s)
        self.sparks_inner_radius_coeff.Read(s)
        self.stains_enabled.Read(s)
        self.stains_radius.Read(s)
        self.ray_energy.Read(s)
        self.max_durability_to_destroy.Read(s)
        self.gore_particle_count.Read(s)
        self.shake_vegetation.Read(s)
        self.damage_mortals.Read(s)
        self.physics_throw_enabled.Read(s)
        self.physics_explosion_power.Read(s)
        self.physics_multiplier_ragdoll_force.Read(s)
        self.cell_explosion_power.Read(s)
        self.cell_explosion_radius_min.Read(s)
        self.cell_explosion_radius_max.Read(s)
        self.cell_explosion_velocity_min.Read(s)
        self.cell_explosion_damage_required.Read(s)
        self.cell_explosion_probability.Read(s)
        self.cell_explosion_power_ragdoll_coeff.Read(s)
        self.pixel_sprites_enabled.Read(s)
        self.is_digger.Read(s)
        self.audio_enabled.Read(s)
        self.audio_event_name.Read(s)
        self.audio_liquid_amount_normalized.Read(s)
        self.delay.Read(s)
        self.explosion_delay_id.Read(s)
        self.not_scaled_by_gamefx.Read(s)
    
    def Write(self, s:NoitaStream):
        self.never_cache.Write(s)
        self.explosion_radius.Write(s)
        self.explosion_sprite.Write(s)
        self.explosion_sprite_emissive.Write(s)
        self.explosion_sprite_additive.Write(s)
        self.explosion_sprite_random_rotation.Write(s)
        self.explosion_sprite_lifetime.Write(s)
        self.damage.Write(s)
        self.damage_critical.Write(s)
        self.camera_shake.Write(s)
        self.particle_effect.Write(s)
        self.load_this_entity.Write(s)
        self.light_enabled.Write(s)
        self.light_fade_time.Write(s)
        self.light_r.Write(s)
        self.light_g.Write(s)
        self.light_b.Write(s)
        self.light_radius_coeff.Write(s)
        self.hole_enabled.Write(s)
        self.destroy_non_platform_solid_enabled.Write(s)
        self.electricity_count.Write(s)
        self.min_radius_for_cracks.Write(s)
        self.crack_count.Write(s)
        self.knockback_force.Write(s)
        self.hole_destroy_liquid.Write(s)
        self.hole_destroy_physics_dynamic.Write(s)
        self.create_cell_material.Write(s)
        self.create_cell_probability.Write(s)
        self.background_lightning_count.Write(s)
        self.spark_material.Write(s)
        self.material_sparks_min_hp.Write(s)
        self.material_sparks_probability.Write(s)
        self.material_sparks_count_min.Write(s)
        self.material_sparks_count_max.Write(s)
        self.material_sparks_enabled.Write(s)
        self.material_sparks_real.Write(s)
        self.material_sparks_scale_with_hp.Write(s)
        self.sparks_enabled.Write(s)
        self.sparks_count_min.Write(s)
        self.sparks_count_max.Write(s)
        self.sparks_inner_radius_coeff.Write(s)
        self.stains_enabled.Write(s)
        self.stains_radius.Write(s)
        self.ray_energy.Write(s)
        self.max_durability_to_destroy.Write(s)
        self.gore_particle_count.Write(s)
        self.shake_vegetation.Write(s)
        self.damage_mortals.Write(s)
        self.physics_throw_enabled.Write(s)
        self.physics_explosion_power.Write(s)
        self.physics_multiplier_ragdoll_force.Write(s)
        self.cell_explosion_power.Write(s)
        self.cell_explosion_radius_min.Write(s)
        self.cell_explosion_radius_max.Write(s)
        self.cell_explosion_velocity_min.Write(s)
        self.cell_explosion_damage_required.Write(s)
        self.cell_explosion_probability.Write(s)
        self.cell_explosion_power_ragdoll_coeff.Write(s)
        self.pixel_sprites_enabled.Write(s)
        self.is_digger.Write(s)
        self.audio_enabled.Write(s)
        self.audio_event_name.Write(s)
        self.audio_liquid_amount_normalized.Write(s)
        self.delay.Write(s)
        self.explosion_delay_id.Write(s)
        self.not_scaled_by_gamefx.Write(s)

