namespace GeneratedNoitaClasses;
public class AnimalAIComponent : NoitaComponentBase,  iNoitaType<AnimalAIComponent>{
	public NoitaBool Deleted { get; set; } = new();
	public NoitaBool Enabled { get; set; } = new();
	public NoitaString Tags { get; set; } = new();
	public NoitaInt ai_state { get; set; } = new();
	public NoitaInt ai_state_timer { get; set; } = new();
	public NoitaBool keep_state_alive_when_enabled { get; set; } = new();
	public NoitaString preferred_job { get; set; } = new();
	public NoitaInt escape_if_damaged_probability { get; set; } = new();
	public NoitaInt attack_if_damaged_probability { get; set; } = new();
	public NoitaInt eye_offset_x { get; set; } = new();
	public NoitaInt eye_offset_y { get; set; } = new();
	public NoitaBool attack_only_if_attacked { get; set; } = new();
	public NoitaBool dont_counter_attack_own_herd { get; set; } = new();
	public NoitaFloat creature_detection_range_x { get; set; } = new();
	public NoitaFloat creature_detection_range_y { get; set; } = new();
	public NoitaFloat creature_detection_angular_range_deg { get; set; } = new();
	public NoitaInt creature_detection_check_every_x_frames { get; set; } = new();
	public NoitaFloat max_distance_to_cam_to_start_hunting { get; set; } = new();
	public NoitaInt pathfinding_max_depth_no_target { get; set; } = new();
	public NoitaInt pathfinding_max_depth_has_target { get; set; } = new();
	public NoitaFloat aggressiveness_min { get; set; } = new();
	public NoitaFloat aggressiveness_max { get; set; } = new();
	public NoitaBool tries_to_ranged_attack_friends { get; set; } = new();
	public NoitaBool attack_melee_enabled { get; set; } = new();
	public NoitaBool attack_dash_enabled { get; set; } = new();
	public NoitaBool attack_landing_ranged_enabled { get; set; } = new();
	public NoitaBool attack_ranged_enabled { get; set; } = new();
	public NoitaFloat attack_knockback_multiplier { get; set; } = new();
	public NoitaBool is_static_turret { get; set; } = new();
	public NoitaInt attack_melee_max_distance { get; set; } = new();
	public NoitaInt attack_melee_action_frame { get; set; } = new();
	public NoitaInt attack_melee_frames_between { get; set; } = new();
	public NoitaFloat attack_melee_damage_min { get; set; } = new();
	public NoitaFloat attack_melee_damage_max { get; set; } = new();
	public NoitaFloat attack_melee_impulse_vector_x { get; set; } = new();
	public NoitaFloat attack_melee_impulse_vector_y { get; set; } = new();
	public NoitaFloat attack_melee_impulse_multiplier { get; set; } = new();
	public NoitaFloat attack_melee_offset_x { get; set; } = new();
	public NoitaFloat attack_melee_offset_y { get; set; } = new();
	public NoitaBool attack_melee_finish_enabled { get; set; } = new();
	public ConfigExplosion attack_melee_finish_config_explosion { get; set; } = new();
	public NoitaInt attack_melee_finish_action_frame { get; set; } = new();
	public NoitaFloat attack_dash_distance { get; set; } = new();
	public NoitaInt attack_dash_frames_between { get; set; } = new();
	public NoitaFloat attack_dash_damage { get; set; } = new();
	public NoitaFloat attack_dash_speed { get; set; } = new();
	public NoitaFloat attack_dash_lob { get; set; } = new();
	public NoitaFloat attack_ranged_min_distance { get; set; } = new();
	public NoitaFloat attack_ranged_max_distance { get; set; } = new();
	public NoitaInt attack_ranged_action_frame { get; set; } = new();
	public NoitaLensValue<NoitaInt> attack_ranged_frames_between { get; set; } = new();
	public NoitaFloat attack_ranged_offset_x { get; set; } = new();
	public NoitaFloat attack_ranged_offset_y { get; set; } = new();
	public NoitaBool attack_ranged_use_message { get; set; } = new();
	public NoitaBool attack_ranged_predict { get; set; } = new();
	public NoitaString attack_ranged_entity_file { get; set; } = new();
	public NoitaInt attack_ranged_entity_count_min { get; set; } = new();
	public NoitaInt attack_ranged_entity_count_max { get; set; } = new();
	public NoitaBool attack_ranged_use_laser_sight { get; set; } = new();
	public NoitaBool attack_ranged_laser_sight_beam_kind { get; set; } = new();
	public NoitaBool attack_ranged_aim_rotation_enabled { get; set; } = new();
	public NoitaFloat attack_ranged_aim_rotation_speed { get; set; } = new();
	public NoitaFloat attack_ranged_aim_rotation_shooting_ok_angle_deg { get; set; } = new();
	public NoitaInt attack_ranged_state_duration_frames { get; set; } = new();
	public NoitaBool hide_from_prey { get; set; } = new();
	public NoitaFloat hide_from_prey_target_distance { get; set; } = new();
	public NoitaInt hide_from_prey_time { get; set; } = new();
	public NoitaInt food_material { get; set; } = new();
	public NoitaInt food_particle_effect_material { get; set; } = new();
	public NoitaBool food_eating_create_particles { get; set; } = new();
	public NoitaInt eating_area_radius_x { get; set; } = new();
	public NoitaInt eating_area_radius_y { get; set; } = new();
	public NoitaInt mouth_offset_x { get; set; } = new();
	public NoitaInt mouth_offset_y { get; set; } = new();
	public NoitaBool defecates_and_pees { get; set; } = new();
	public NoitaInt butt_offset_x { get; set; } = new();
	public NoitaInt butt_offset_y { get; set; } = new();
	public NoitaFloat pee_velocity_x { get; set; } = new();
	public NoitaFloat pee_velocity_y { get; set; } = new();
	public NoitaBool needs_food { get; set; } = new();
	public NoitaBool sense_creatures { get; set; } = new();
	public NoitaBool sense_creatures_through_walls { get; set; } = new();
	public NoitaBool can_fly { get; set; } = new();
	public NoitaBool can_walk { get; set; } = new();
	public NoitaInt path_distance_to_target_node_to_turn_around { get; set; } = new();
	public NoitaFloat path_cleanup_explosion_radius { get; set; } = new();
	public NoitaFloat max_distance_to_move_from_home { get; set; } = new();
	public NoitaLensValue<NoitaFloat> mAggression { get; set; } = new();

    public void Read(NoitaStream s){
		Deleted.Read(s);
		Enabled.Read(s);
		Tags.Read(s);
		ai_state.Read(s);
		ai_state_timer.Read(s);
		keep_state_alive_when_enabled.Read(s);
		preferred_job.Read(s);
		escape_if_damaged_probability.Read(s);
		attack_if_damaged_probability.Read(s);
		eye_offset_x.Read(s);
		eye_offset_y.Read(s);
		attack_only_if_attacked.Read(s);
		dont_counter_attack_own_herd.Read(s);
		creature_detection_range_x.Read(s);
		creature_detection_range_y.Read(s);
		creature_detection_angular_range_deg.Read(s);
		creature_detection_check_every_x_frames.Read(s);
		max_distance_to_cam_to_start_hunting.Read(s);
		pathfinding_max_depth_no_target.Read(s);
		pathfinding_max_depth_has_target.Read(s);
		aggressiveness_min.Read(s);
		aggressiveness_max.Read(s);
		tries_to_ranged_attack_friends.Read(s);
		attack_melee_enabled.Read(s);
		attack_dash_enabled.Read(s);
		attack_landing_ranged_enabled.Read(s);
		attack_ranged_enabled.Read(s);
		attack_knockback_multiplier.Read(s);
		is_static_turret.Read(s);
		attack_melee_max_distance.Read(s);
		attack_melee_action_frame.Read(s);
		attack_melee_frames_between.Read(s);
		attack_melee_damage_min.Read(s);
		attack_melee_damage_max.Read(s);
		attack_melee_impulse_vector_x.Read(s);
		attack_melee_impulse_vector_y.Read(s);
		attack_melee_impulse_multiplier.Read(s);
		attack_melee_offset_x.Read(s);
		attack_melee_offset_y.Read(s);
		attack_melee_finish_enabled.Read(s);
		attack_melee_finish_config_explosion.Read(s);
		attack_melee_finish_action_frame.Read(s);
		attack_dash_distance.Read(s);
		attack_dash_frames_between.Read(s);
		attack_dash_damage.Read(s);
		attack_dash_speed.Read(s);
		attack_dash_lob.Read(s);
		attack_ranged_min_distance.Read(s);
		attack_ranged_max_distance.Read(s);
		attack_ranged_action_frame.Read(s);
		attack_ranged_frames_between.Read(s);
		attack_ranged_offset_x.Read(s);
		attack_ranged_offset_y.Read(s);
		attack_ranged_use_message.Read(s);
		attack_ranged_predict.Read(s);
		attack_ranged_entity_file.Read(s);
		attack_ranged_entity_count_min.Read(s);
		attack_ranged_entity_count_max.Read(s);
		attack_ranged_use_laser_sight.Read(s);
		attack_ranged_laser_sight_beam_kind.Read(s);
		attack_ranged_aim_rotation_enabled.Read(s);
		attack_ranged_aim_rotation_speed.Read(s);
		attack_ranged_aim_rotation_shooting_ok_angle_deg.Read(s);
		attack_ranged_state_duration_frames.Read(s);
		hide_from_prey.Read(s);
		hide_from_prey_target_distance.Read(s);
		hide_from_prey_time.Read(s);
		food_material.Read(s);
		food_particle_effect_material.Read(s);
		food_eating_create_particles.Read(s);
		eating_area_radius_x.Read(s);
		eating_area_radius_y.Read(s);
		mouth_offset_x.Read(s);
		mouth_offset_y.Read(s);
		defecates_and_pees.Read(s);
		butt_offset_x.Read(s);
		butt_offset_y.Read(s);
		pee_velocity_x.Read(s);
		pee_velocity_y.Read(s);
		needs_food.Read(s);
		sense_creatures.Read(s);
		sense_creatures_through_walls.Read(s);
		can_fly.Read(s);
		can_walk.Read(s);
		path_distance_to_target_node_to_turn_around.Read(s);
		path_cleanup_explosion_radius.Read(s);
		max_distance_to_move_from_home.Read(s);
		mAggression.Read(s);

    }
    public void Write(NoitaStream s){
		Deleted.Write(s);
		Enabled.Write(s);
		Tags.Write(s);
		ai_state.Write(s);
		ai_state_timer.Write(s);
		keep_state_alive_when_enabled.Write(s);
		preferred_job.Write(s);
		escape_if_damaged_probability.Write(s);
		attack_if_damaged_probability.Write(s);
		eye_offset_x.Write(s);
		eye_offset_y.Write(s);
		attack_only_if_attacked.Write(s);
		dont_counter_attack_own_herd.Write(s);
		creature_detection_range_x.Write(s);
		creature_detection_range_y.Write(s);
		creature_detection_angular_range_deg.Write(s);
		creature_detection_check_every_x_frames.Write(s);
		max_distance_to_cam_to_start_hunting.Write(s);
		pathfinding_max_depth_no_target.Write(s);
		pathfinding_max_depth_has_target.Write(s);
		aggressiveness_min.Write(s);
		aggressiveness_max.Write(s);
		tries_to_ranged_attack_friends.Write(s);
		attack_melee_enabled.Write(s);
		attack_dash_enabled.Write(s);
		attack_landing_ranged_enabled.Write(s);
		attack_ranged_enabled.Write(s);
		attack_knockback_multiplier.Write(s);
		is_static_turret.Write(s);
		attack_melee_max_distance.Write(s);
		attack_melee_action_frame.Write(s);
		attack_melee_frames_between.Write(s);
		attack_melee_damage_min.Write(s);
		attack_melee_damage_max.Write(s);
		attack_melee_impulse_vector_x.Write(s);
		attack_melee_impulse_vector_y.Write(s);
		attack_melee_impulse_multiplier.Write(s);
		attack_melee_offset_x.Write(s);
		attack_melee_offset_y.Write(s);
		attack_melee_finish_enabled.Write(s);
		attack_melee_finish_config_explosion.Write(s);
		attack_melee_finish_action_frame.Write(s);
		attack_dash_distance.Write(s);
		attack_dash_frames_between.Write(s);
		attack_dash_damage.Write(s);
		attack_dash_speed.Write(s);
		attack_dash_lob.Write(s);
		attack_ranged_min_distance.Write(s);
		attack_ranged_max_distance.Write(s);
		attack_ranged_action_frame.Write(s);
		attack_ranged_frames_between.Write(s);
		attack_ranged_offset_x.Write(s);
		attack_ranged_offset_y.Write(s);
		attack_ranged_use_message.Write(s);
		attack_ranged_predict.Write(s);
		attack_ranged_entity_file.Write(s);
		attack_ranged_entity_count_min.Write(s);
		attack_ranged_entity_count_max.Write(s);
		attack_ranged_use_laser_sight.Write(s);
		attack_ranged_laser_sight_beam_kind.Write(s);
		attack_ranged_aim_rotation_enabled.Write(s);
		attack_ranged_aim_rotation_speed.Write(s);
		attack_ranged_aim_rotation_shooting_ok_angle_deg.Write(s);
		attack_ranged_state_duration_frames.Write(s);
		hide_from_prey.Write(s);
		hide_from_prey_target_distance.Write(s);
		hide_from_prey_time.Write(s);
		food_material.Write(s);
		food_particle_effect_material.Write(s);
		food_eating_create_particles.Write(s);
		eating_area_radius_x.Write(s);
		eating_area_radius_y.Write(s);
		mouth_offset_x.Write(s);
		mouth_offset_y.Write(s);
		defecates_and_pees.Write(s);
		butt_offset_x.Write(s);
		butt_offset_y.Write(s);
		pee_velocity_x.Write(s);
		pee_velocity_y.Write(s);
		needs_food.Write(s);
		sense_creatures.Write(s);
		sense_creatures_through_walls.Write(s);
		can_fly.Write(s);
		can_walk.Write(s);
		path_distance_to_target_node_to_turn_around.Write(s);
		path_cleanup_explosion_radius.Write(s);
		max_distance_to_move_from_home.Write(s);
		mAggression.Write(s);

    }
}