namespace GeneratedNoitaClasses;
public class AnimalAIComponent{
	public int ai_state{ get; set; }
	public int ai_state_timer{ get; set; }
	public bool keep_state_alive_when_enabled{ get; set; }
	public string preferred_job{ get; set; }
	public int escape_if_damaged_probability{ get; set; }
	public int attack_if_damaged_probability{ get; set; }
	public int eye_offset_x{ get; set; }
	public int eye_offset_y{ get; set; }
	public bool attack_only_if_attacked{ get; set; }
	public bool dont_counter_attack_own_herd{ get; set; }
	public float creature_detection_range_x{ get; set; }
	public float creature_detection_range_y{ get; set; }
	public float creature_detection_angular_range_deg{ get; set; }
	public int creature_detection_check_every_x_frames{ get; set; }
	public float max_distance_to_cam_to_start_hunting{ get; set; }
	public int pathfinding_max_depth_no_target{ get; set; }
	public int pathfinding_max_depth_has_target{ get; set; }
	public float aggressiveness_min{ get; set; }
	public float aggressiveness_max{ get; set; }
	public bool tries_to_ranged_attack_friends{ get; set; }
	public bool attack_melee_enabled{ get; set; }
	public bool attack_dash_enabled{ get; set; }
	public bool attack_landing_ranged_enabled{ get; set; }
	public bool attack_ranged_enabled{ get; set; }
	public float attack_knockback_multiplier{ get; set; }
	public bool is_static_turret{ get; set; }
	public int attack_melee_max_distance{ get; set; }
	public int attack_melee_action_frame{ get; set; }
	public int attack_melee_frames_between{ get; set; }
	public float attack_melee_damage_min{ get; set; }
	public float attack_melee_damage_max{ get; set; }
	public float attack_melee_impulse_vector_x{ get; set; }
	public float attack_melee_impulse_vector_y{ get; set; }
	public float attack_melee_impulse_multiplier{ get; set; }
	public float attack_melee_offset_x{ get; set; }
	public float attack_melee_offset_y{ get; set; }
	public bool attack_melee_finish_enabled{ get; set; }
	public ConfigExplosion attack_melee_finish_config_explosion{ get; set; }
	public int attack_melee_finish_action_frame{ get; set; }
	public float attack_dash_distance{ get; set; }
	public int attack_dash_frames_between{ get; set; }
	public float attack_dash_damage{ get; set; }
	public float attack_dash_speed{ get; set; }
	public float attack_dash_lob{ get; set; }
	public float attack_ranged_min_distance{ get; set; }
	public float attack_ranged_max_distance{ get; set; }
	public int attack_ranged_action_frame{ get; set; }
	public int attack_ranged_frames_between{ get; set; }
	public float attack_ranged_offset_x{ get; set; }
	public float attack_ranged_offset_y{ get; set; }
	public bool attack_ranged_use_message{ get; set; }
	public bool attack_ranged_predict{ get; set; }
	public string attack_ranged_entity_file{ get; set; }
	public int attack_ranged_entity_count_min{ get; set; }
	public int attack_ranged_entity_count_max{ get; set; }
	public bool attack_ranged_use_laser_sight{ get; set; }
	public bool attack_ranged_laser_sight_beam_kind{ get; set; }
	public bool attack_ranged_aim_rotation_enabled{ get; set; }
	public float attack_ranged_aim_rotation_speed{ get; set; }
	public float attack_ranged_aim_rotation_shooting_ok_angle_deg{ get; set; }
	public int attack_ranged_state_duration_frames{ get; set; }
	public bool hide_from_prey{ get; set; }
	public float hide_from_prey_target_distance{ get; set; }
	public int hide_from_prey_time{ get; set; }
	public int food_material{ get; set; }
	public int food_particle_effect_material{ get; set; }
	public bool food_eating_create_particles{ get; set; }
	public int eating_area_radius_x{ get; set; }
	public int eating_area_radius_y{ get; set; }
	public int mouth_offset_x{ get; set; }
	public int mouth_offset_y{ get; set; }
	public bool defecates_and_pees{ get; set; }
	public int butt_offset_x{ get; set; }
	public int butt_offset_y{ get; set; }
	public float pee_velocity_x{ get; set; }
	public float pee_velocity_y{ get; set; }
	public bool needs_food{ get; set; }
	public bool sense_creatures{ get; set; }
	public bool sense_creatures_through_walls{ get; set; }
	public bool can_fly{ get; set; }
	public bool can_walk{ get; set; }
	public int path_distance_to_target_node_to_turn_around{ get; set; }
	public float path_cleanup_explosion_radius{ get; set; }
	public float max_distance_to_move_from_home{ get; set; }
	public float mAggression{ get; set; }

}