namespace GeneratedNoitaClasses;
public class BossDragonComponent : NoitaComponentBase,  iNoitaType<BossDragonComponent>{
	public NoitaBool Deleted { get; set; } = new();
	public NoitaBool Enabled { get; set; } = new();
	public NoitaString Tags { get; set; } = new();
	public NoitaFloat speed { get; set; } = new();
	public NoitaFloat speed_hunt { get; set; } = new();
	public NoitaFloat acceleration { get; set; } = new();
	public NoitaFloat direction_adjust_speed { get; set; } = new();
	public NoitaFloat direction_adjust_speed_hunt { get; set; } = new();
	public NoitaFloat gravity { get; set; } = new();
	public NoitaFloat tail_gravity { get; set; } = new();
	public NoitaFloat part_distance { get; set; } = new();
	public NoitaInt ground_check_offset { get; set; } = new();
	public NoitaFloat eat_ground_radius { get; set; } = new();
	public NoitaBool eat_ground { get; set; } = new();
	public NoitaFloat hitbox_radius { get; set; } = new();
	public NoitaFloat bite_damage { get; set; } = new();
	public NoitaFloat target_kill_radius { get; set; } = new();
	public NoitaFloat target_kill_ragdoll_force { get; set; } = new();
	public NoitaFloat hunt_box_radius { get; set; } = new();
	public NoitaFloat random_target_box_radius { get; set; } = new();
	public NoitaInt new_hunt_target_check_every { get; set; } = new();
	public NoitaInt new_random_target_check_every { get; set; } = new();
	public NoitaFloat jump_cam_shake { get; set; } = new();
	public NoitaFloat jump_cam_shake_distance { get; set; } = new();
	public NoitaFloat eat_anim_wait_mult { get; set; } = new();
	public NoitaString projectile_1 { get; set; } = new();
	public NoitaInt projectile_1_count { get; set; } = new();
	public NoitaString projectile_2 { get; set; } = new();
	public NoitaInt projectile_2_count { get; set; } = new();
	public NoitaString ragdoll_filename { get; set; } = new();

    public void Read(NoitaStream s){
		Deleted.Read(s);
		Enabled.Read(s);
		Tags.Read(s);
		speed.Read(s);
		speed_hunt.Read(s);
		acceleration.Read(s);
		direction_adjust_speed.Read(s);
		direction_adjust_speed_hunt.Read(s);
		gravity.Read(s);
		tail_gravity.Read(s);
		part_distance.Read(s);
		ground_check_offset.Read(s);
		eat_ground_radius.Read(s);
		eat_ground.Read(s);
		hitbox_radius.Read(s);
		bite_damage.Read(s);
		target_kill_radius.Read(s);
		target_kill_ragdoll_force.Read(s);
		hunt_box_radius.Read(s);
		random_target_box_radius.Read(s);
		new_hunt_target_check_every.Read(s);
		new_random_target_check_every.Read(s);
		jump_cam_shake.Read(s);
		jump_cam_shake_distance.Read(s);
		eat_anim_wait_mult.Read(s);
		projectile_1.Read(s);
		projectile_1_count.Read(s);
		projectile_2.Read(s);
		projectile_2_count.Read(s);
		ragdoll_filename.Read(s);

    }
    public void Write(NoitaStream s){
		Deleted.Write(s);
		Enabled.Write(s);
		Tags.Write(s);
		speed.Write(s);
		speed_hunt.Write(s);
		acceleration.Write(s);
		direction_adjust_speed.Write(s);
		direction_adjust_speed_hunt.Write(s);
		gravity.Write(s);
		tail_gravity.Write(s);
		part_distance.Write(s);
		ground_check_offset.Write(s);
		eat_ground_radius.Write(s);
		eat_ground.Write(s);
		hitbox_radius.Write(s);
		bite_damage.Write(s);
		target_kill_radius.Write(s);
		target_kill_ragdoll_force.Write(s);
		hunt_box_radius.Write(s);
		random_target_box_radius.Write(s);
		new_hunt_target_check_every.Write(s);
		new_random_target_check_every.Write(s);
		jump_cam_shake.Write(s);
		jump_cam_shake_distance.Write(s);
		eat_anim_wait_mult.Write(s);
		projectile_1.Write(s);
		projectile_1_count.Write(s);
		projectile_2.Write(s);
		projectile_2_count.Write(s);
		ragdoll_filename.Write(s);

    }
}