namespace GeneratedNoitaClasses;
public class CharacterDataComponent : NoitaComponentBase,  iNoitaType<CharacterDataComponent>{
	public NoitaBool Deleted { get; set; } = new();
	public NoitaBool Enabled { get; set; } = new();
	public NoitaString Tags { get; set; } = new();
	public NoitaInt platforming_type { get; set; } = new();
	public NoitaLensValue<NoitaFloat> collision_aabb_min_x { get; set; } = new();
	public NoitaLensValue<NoitaFloat> collision_aabb_max_x { get; set; } = new();
	public NoitaLensValue<NoitaFloat> collision_aabb_min_y { get; set; } = new();
	public NoitaLensValue<NoitaFloat> collision_aabb_max_y { get; set; } = new();
	public NoitaFloat mass { get; set; } = new();
	public NoitaInt buoyancy_check_offset_y { get; set; } = new();
	public NoitaFloat liquid_velocity_coeff { get; set; } = new();
	public NoitaFloat gravity { get; set; } = new();
	public NoitaLensValue<NoitaFloat> fly_time_max { get; set; } = new();
	public NoitaFloat fly_recharge_spd { get; set; } = new();
	public NoitaFloat fly_recharge_spd_ground { get; set; } = new();
	public NoitaBool flying_needs_recharge { get; set; } = new();
	public NoitaInt flying_in_air_wait_frames { get; set; } = new();
	public NoitaInt flying_recharge_removal_frames { get; set; } = new();
	public NoitaInt climb_over_y { get; set; } = new();
	public NoitaInt check_collision_max_size_x { get; set; } = new();
	public NoitaInt check_collision_max_size_y { get; set; } = new();
	public NoitaBool is_on_ground { get; set; } = new();
	public NoitaBool is_on_slippery_ground { get; set; } = new();
	public NoitaFloat ground_stickyness { get; set; } = new();
	public NoitaBool effect_hit_ground { get; set; } = new();
	public NoitaInt eff_hg_damage_min { get; set; } = new();
	public NoitaInt eff_hg_damage_max { get; set; } = new();
	public NoitaFloat eff_hg_position_x { get; set; } = new();
	public NoitaFloat eff_hg_position_y { get; set; } = new();
	public NoitaFloat eff_hg_size_x { get; set; } = new();
	public NoitaFloat eff_hg_size_y { get; set; } = new();
	public NoitaFloat eff_hg_velocity_min_x { get; set; } = new();
	public NoitaFloat eff_hg_velocity_max_x { get; set; } = new();
	public NoitaFloat eff_hg_velocity_min_y { get; set; } = new();
	public NoitaFloat eff_hg_velocity_max_y { get; set; } = new();
	public NoitaFloat eff_hg_offset_y { get; set; } = new();
	public NoitaBool eff_hg_update_box2d { get; set; } = new();
	public NoitaFloat eff_hg_b2force_multiplier { get; set; } = new();
	public NoitaFloat destroy_ground { get; set; } = new();
	public NoitaBool send_transform_update_message { get; set; } = new();
	public NoitaBool dont_update_velocity_and_xform { get; set; } = new();
	public NoitaFloat mFlyingTimeLeft { get; set; } = new();

    public void Read(NoitaStream s){
		Deleted.Read(s);
		Enabled.Read(s);
		Tags.Read(s);
		platforming_type.Read(s);
		collision_aabb_min_x.Read(s);
		collision_aabb_max_x.Read(s);
		collision_aabb_min_y.Read(s);
		collision_aabb_max_y.Read(s);
		mass.Read(s);
		buoyancy_check_offset_y.Read(s);
		liquid_velocity_coeff.Read(s);
		gravity.Read(s);
		fly_time_max.Read(s);
		fly_recharge_spd.Read(s);
		fly_recharge_spd_ground.Read(s);
		flying_needs_recharge.Read(s);
		flying_in_air_wait_frames.Read(s);
		flying_recharge_removal_frames.Read(s);
		climb_over_y.Read(s);
		check_collision_max_size_x.Read(s);
		check_collision_max_size_y.Read(s);
		is_on_ground.Read(s);
		is_on_slippery_ground.Read(s);
		ground_stickyness.Read(s);
		effect_hit_ground.Read(s);
		eff_hg_damage_min.Read(s);
		eff_hg_damage_max.Read(s);
		eff_hg_position_x.Read(s);
		eff_hg_position_y.Read(s);
		eff_hg_size_x.Read(s);
		eff_hg_size_y.Read(s);
		eff_hg_velocity_min_x.Read(s);
		eff_hg_velocity_max_x.Read(s);
		eff_hg_velocity_min_y.Read(s);
		eff_hg_velocity_max_y.Read(s);
		eff_hg_offset_y.Read(s);
		eff_hg_update_box2d.Read(s);
		eff_hg_b2force_multiplier.Read(s);
		destroy_ground.Read(s);
		send_transform_update_message.Read(s);
		dont_update_velocity_and_xform.Read(s);
		mFlyingTimeLeft.Read(s);

    }
    public void Write(NoitaStream s){
		Deleted.Write(s);
		Enabled.Write(s);
		Tags.Write(s);
		platforming_type.Write(s);
		collision_aabb_min_x.Write(s);
		collision_aabb_max_x.Write(s);
		collision_aabb_min_y.Write(s);
		collision_aabb_max_y.Write(s);
		mass.Write(s);
		buoyancy_check_offset_y.Write(s);
		liquid_velocity_coeff.Write(s);
		gravity.Write(s);
		fly_time_max.Write(s);
		fly_recharge_spd.Write(s);
		fly_recharge_spd_ground.Write(s);
		flying_needs_recharge.Write(s);
		flying_in_air_wait_frames.Write(s);
		flying_recharge_removal_frames.Write(s);
		climb_over_y.Write(s);
		check_collision_max_size_x.Write(s);
		check_collision_max_size_y.Write(s);
		is_on_ground.Write(s);
		is_on_slippery_ground.Write(s);
		ground_stickyness.Write(s);
		effect_hit_ground.Write(s);
		eff_hg_damage_min.Write(s);
		eff_hg_damage_max.Write(s);
		eff_hg_position_x.Write(s);
		eff_hg_position_y.Write(s);
		eff_hg_size_x.Write(s);
		eff_hg_size_y.Write(s);
		eff_hg_velocity_min_x.Write(s);
		eff_hg_velocity_max_x.Write(s);
		eff_hg_velocity_min_y.Write(s);
		eff_hg_velocity_max_y.Write(s);
		eff_hg_offset_y.Write(s);
		eff_hg_update_box2d.Write(s);
		eff_hg_b2force_multiplier.Write(s);
		destroy_ground.Write(s);
		send_transform_update_message.Write(s);
		dont_update_velocity_and_xform.Write(s);
		mFlyingTimeLeft.Write(s);

    }
}