namespace GeneratedNoitaClasses;
public class DamageModelComponent{
	public double hp{ get; set; }
	public double max_hp{ get; set; }
	public double max_hp_cap{ get; set; }
	public double max_hp_old{ get; set; }
	public ConfigDamagesByType damage_multipliers{ get; set; }
	public float critical_damage_resistance{ get; set; }
	public int invincibility_frames{ get; set; }
	public bool falling_damages{ get; set; }
	public float falling_damage_height_min{ get; set; }
	public float falling_damage_height_max{ get; set; }
	public float falling_damage_damage_min{ get; set; }
	public float falling_damage_damage_max{ get; set; }
	public bool air_needed{ get; set; }
	public float air_in_lungs{ get; set; }
	public float air_in_lungs_max{ get; set; }
	public float air_lack_of_damage{ get; set; }
	public float minimum_knockback_force{ get; set; }
	public bool materials_damage{ get; set; }
	public int material_damage_min_cell_count{ get; set; }
	public string materials_that_damage{ get; set; }
	public string materials_how_much_damage{ get; set; }
	public bool materials_damage_proportional_to_maxhp{ get; set; }
	public bool physics_objects_damage{ get; set; }
	public bool materials_create_messages{ get; set; }
	public string materials_that_create_messages{ get; set; }
	public string ragdoll_filenames_file{ get; set; }
	public string ragdoll_material{ get; set; }
	public float ragdoll_offset_x{ get; set; }
	public float ragdoll_offset_y{ get; set; }
	public RAGDOLL_FX ragdoll_fx_forced{ get; set; }
	public string blood_material{ get; set; }
	public string blood_spray_material{ get; set; }
	public bool blood_spray_create_some_cosmetic{ get; set; }
	public float blood_multiplier{ get; set; }
	public int ragdoll_blood_amount_absolute{ get; set; }
	public string blood_sprite_directional{ get; set; }
	public string blood_sprite_large{ get; set; }
	public string healing_particle_effect_entity{ get; set; }
	public bool create_ragdoll{ get; set; }
	public bool ragdollify_child_entity_sprites{ get; set; }
	public float ragdollify_root_angular_damping{ get; set; }
	public bool ragdollify_disintegrate_nonroot{ get; set; }
	public bool wait_for_kill_flag_on_death{ get; set; }
	public bool kill_now{ get; set; }
	public bool drop_items_on_death{ get; set; }
	public bool ui_report_damage{ get; set; }
	public bool ui_force_report_damage{ get; set; }
	public int in_liquid_shooting_electrify_prob{ get; set; }
	public float wet_status_effect_damage{ get; set; }
	public bool is_on_fire{ get; set; }
	public float fire_probability_of_ignition{ get; set; }
	public int fire_how_much_fire_generates{ get; set; }
	public float fire_damage_ignited_amount{ get; set; }
	public float fire_damage_amount{ get; set; }
	public int mLastElectricityResistanceFrame{ get; set; }
	public int mLastFrameReportedBlock{ get; set; }
	public int mLastMaxHpChangeFrame{ get; set; }

}