namespace GeneratedNoitaClasses;
public class DamageModelComponent : NoitaComponentBase,  iNoitaType<DamageModelComponent>{
	public NoitaBool Deleted { get; set; } = new();
	public NoitaBool Enabled { get; set; } = new();
	public NoitaString Tags { get; set; } = new();
	public NoitaDouble hp { get; set; } = new();
	public NoitaDouble max_hp { get; set; } = new();
	public NoitaDouble max_hp_cap { get; set; } = new();
	public NoitaDouble max_hp_old { get; set; } = new();
	public ConfigDamagesByType damage_multipliers { get; set; } = new();
	public NoitaFloat critical_damage_resistance { get; set; } = new();
	public NoitaInt invincibility_frames { get; set; } = new();
	public NoitaBool falling_damages { get; set; } = new();
	public NoitaFloat falling_damage_height_min { get; set; } = new();
	public NoitaFloat falling_damage_height_max { get; set; } = new();
	public NoitaFloat falling_damage_damage_min { get; set; } = new();
	public NoitaFloat falling_damage_damage_max { get; set; } = new();
	public NoitaBool air_needed { get; set; } = new();
	public NoitaFloat air_in_lungs { get; set; } = new();
	public NoitaFloat air_in_lungs_max { get; set; } = new();
	public NoitaFloat air_lack_of_damage { get; set; } = new();
	public NoitaFloat minimum_knockback_force { get; set; } = new();
	public NoitaBool materials_damage { get; set; } = new();
	public NoitaInt material_damage_min_cell_count { get; set; } = new();
	public NoitaString materials_that_damage { get; set; } = new();
	public NoitaString materials_how_much_damage { get; set; } = new();
	public NoitaBool materials_damage_proportional_to_maxhp { get; set; } = new();
	public NoitaBool physics_objects_damage { get; set; } = new();
	public NoitaBool materials_create_messages { get; set; } = new();
	public NoitaString materials_that_create_messages { get; set; } = new();
	public NoitaString ragdoll_filenames_file { get; set; } = new();
	public NoitaString ragdoll_material { get; set; } = new();
	public NoitaFloat ragdoll_offset_x { get; set; } = new();
	public NoitaFloat ragdoll_offset_y { get; set; } = new();
	public NoitaUInt ragdoll_fx_forced { get; set; } = new();
	public NoitaString blood_material { get; set; } = new();
	public NoitaString blood_spray_material { get; set; } = new();
	public NoitaBool blood_spray_create_some_cosmetic { get; set; } = new();
	public NoitaFloat blood_multiplier { get; set; } = new();
	public NoitaInt ragdoll_blood_amount_absolute { get; set; } = new();
	public NoitaString blood_sprite_directional { get; set; } = new();
	public NoitaString blood_sprite_large { get; set; } = new();
	public NoitaString healing_particle_effect_entity { get; set; } = new();
	public NoitaBool create_ragdoll { get; set; } = new();
	public NoitaBool ragdollify_child_entity_sprites { get; set; } = new();
	public NoitaFloat ragdollify_root_angular_damping { get; set; } = new();
	public NoitaBool ragdollify_disintegrate_nonroot { get; set; } = new();
	public NoitaBool wait_for_kill_flag_on_death { get; set; } = new();
	public NoitaBool kill_now { get; set; } = new();
	public NoitaBool drop_items_on_death { get; set; } = new();
	public NoitaBool ui_report_damage { get; set; } = new();
	public NoitaBool ui_force_report_damage { get; set; } = new();
	public NoitaInt in_liquid_shooting_electrify_prob { get; set; } = new();
	public NoitaFloat wet_status_effect_damage { get; set; } = new();
	public NoitaBool is_on_fire { get; set; } = new();
	public NoitaFloat fire_probability_of_ignition { get; set; } = new();
	public NoitaInt fire_how_much_fire_generates { get; set; } = new();
	public NoitaFloat fire_damage_ignited_amount { get; set; } = new();
	public NoitaFloat fire_damage_amount { get; set; } = new();
	public NoitaInt mLastElectricityResistanceFrame { get; set; } = new();
	public NoitaInt mLastFrameReportedBlock { get; set; } = new();
	public NoitaInt mLastMaxHpChangeFrame { get; set; } = new();

    public void Read(NoitaStream s){
		Deleted.Read(s);
		Enabled.Read(s);
		Tags.Read(s);
		hp.Read(s);
		max_hp.Read(s);
		max_hp_cap.Read(s);
		max_hp_old.Read(s);
		damage_multipliers.Read(s);
		critical_damage_resistance.Read(s);
		invincibility_frames.Read(s);
		falling_damages.Read(s);
		falling_damage_height_min.Read(s);
		falling_damage_height_max.Read(s);
		falling_damage_damage_min.Read(s);
		falling_damage_damage_max.Read(s);
		air_needed.Read(s);
		air_in_lungs.Read(s);
		air_in_lungs_max.Read(s);
		air_lack_of_damage.Read(s);
		minimum_knockback_force.Read(s);
		materials_damage.Read(s);
		material_damage_min_cell_count.Read(s);
		materials_that_damage.Read(s);
		materials_how_much_damage.Read(s);
		materials_damage_proportional_to_maxhp.Read(s);
		physics_objects_damage.Read(s);
		materials_create_messages.Read(s);
		materials_that_create_messages.Read(s);
		ragdoll_filenames_file.Read(s);
		ragdoll_material.Read(s);
		ragdoll_offset_x.Read(s);
		ragdoll_offset_y.Read(s);
		ragdoll_fx_forced.Read(s);
		blood_material.Read(s);
		blood_spray_material.Read(s);
		blood_spray_create_some_cosmetic.Read(s);
		blood_multiplier.Read(s);
		ragdoll_blood_amount_absolute.Read(s);
		blood_sprite_directional.Read(s);
		blood_sprite_large.Read(s);
		healing_particle_effect_entity.Read(s);
		create_ragdoll.Read(s);
		ragdollify_child_entity_sprites.Read(s);
		ragdollify_root_angular_damping.Read(s);
		ragdollify_disintegrate_nonroot.Read(s);
		wait_for_kill_flag_on_death.Read(s);
		kill_now.Read(s);
		drop_items_on_death.Read(s);
		ui_report_damage.Read(s);
		ui_force_report_damage.Read(s);
		in_liquid_shooting_electrify_prob.Read(s);
		wet_status_effect_damage.Read(s);
		is_on_fire.Read(s);
		fire_probability_of_ignition.Read(s);
		fire_how_much_fire_generates.Read(s);
		fire_damage_ignited_amount.Read(s);
		fire_damage_amount.Read(s);
		mLastElectricityResistanceFrame.Read(s);
		mLastFrameReportedBlock.Read(s);
		mLastMaxHpChangeFrame.Read(s);

    }
    public void Write(NoitaStream s){
		Deleted.Write(s);
		Enabled.Write(s);
		Tags.Write(s);
		hp.Write(s);
		max_hp.Write(s);
		max_hp_cap.Write(s);
		max_hp_old.Write(s);
		damage_multipliers.Write(s);
		critical_damage_resistance.Write(s);
		invincibility_frames.Write(s);
		falling_damages.Write(s);
		falling_damage_height_min.Write(s);
		falling_damage_height_max.Write(s);
		falling_damage_damage_min.Write(s);
		falling_damage_damage_max.Write(s);
		air_needed.Write(s);
		air_in_lungs.Write(s);
		air_in_lungs_max.Write(s);
		air_lack_of_damage.Write(s);
		minimum_knockback_force.Write(s);
		materials_damage.Write(s);
		material_damage_min_cell_count.Write(s);
		materials_that_damage.Write(s);
		materials_how_much_damage.Write(s);
		materials_damage_proportional_to_maxhp.Write(s);
		physics_objects_damage.Write(s);
		materials_create_messages.Write(s);
		materials_that_create_messages.Write(s);
		ragdoll_filenames_file.Write(s);
		ragdoll_material.Write(s);
		ragdoll_offset_x.Write(s);
		ragdoll_offset_y.Write(s);
		ragdoll_fx_forced.Write(s);
		blood_material.Write(s);
		blood_spray_material.Write(s);
		blood_spray_create_some_cosmetic.Write(s);
		blood_multiplier.Write(s);
		ragdoll_blood_amount_absolute.Write(s);
		blood_sprite_directional.Write(s);
		blood_sprite_large.Write(s);
		healing_particle_effect_entity.Write(s);
		create_ragdoll.Write(s);
		ragdollify_child_entity_sprites.Write(s);
		ragdollify_root_angular_damping.Write(s);
		ragdollify_disintegrate_nonroot.Write(s);
		wait_for_kill_flag_on_death.Write(s);
		kill_now.Write(s);
		drop_items_on_death.Write(s);
		ui_report_damage.Write(s);
		ui_force_report_damage.Write(s);
		in_liquid_shooting_electrify_prob.Write(s);
		wet_status_effect_damage.Write(s);
		is_on_fire.Write(s);
		fire_probability_of_ignition.Write(s);
		fire_how_much_fire_generates.Write(s);
		fire_damage_ignited_amount.Write(s);
		fire_damage_amount.Write(s);
		mLastElectricityResistanceFrame.Write(s);
		mLastFrameReportedBlock.Write(s);
		mLastMaxHpChangeFrame.Write(s);

    }
}