namespace GeneratedNoitaClasses;
public class GameEffectComponent : NoitaComponentBase,  iNoitaType<GameEffectComponent>{
	public NoitaBool Deleted { get; set; } = new();
	public NoitaBool Enabled { get; set; } = new();
	public NoitaString Tags { get; set; } = new();
	public NoitaUInt effect { get; set; } = new();
	public NoitaString custom_effect_id { get; set; } = new();
	public NoitaInt frames { get; set; } = new();
	public NoitaInt exclusivity_group { get; set; } = new();
	public NoitaBool report_block_msg { get; set; } = new();
	public NoitaBool disable_movement { get; set; } = new();
	public NoitaUInt ragdoll_effect { get; set; } = new();
	public NoitaInt ragdoll_material { get; set; } = new();
	public NoitaString ragdoll_effect_custom_entity_file { get; set; } = new();
	public NoitaBool ragdoll_fx_custom_entity_apply_only_to_largest_body { get; set; } = new();
	public NoitaString polymorph_target { get; set; } = new();
	public NoitaString mSerializedData { get; set; } = new();
	public NoitaUInt mCaster { get; set; } = new();
	public NoitaInt mCasterHerdId { get; set; } = new();
	public NoitaInt teleportation_probability { get; set; } = new();
	public NoitaInt teleportation_delay_min_frames { get; set; } = new();
	public NoitaFloat teleportation_radius_min { get; set; } = new();
	public NoitaFloat teleportation_radius_max { get; set; } = new();
	public NoitaInt teleportations_num { get; set; } = new();
	public NoitaDouble no_heal_max_hp_cap { get; set; } = new();
	public NoitaUInt causing_status_effect { get; set; } = new();
	public NoitaBool caused_by_ingestion_status_effect { get; set; } = new();
	public NoitaBool caused_by_stains { get; set; } = new();
	public NoitaBool mCharmDisabledCameraBound { get; set; } = new();
	public NoitaBool mCharmEnabledTeleporting { get; set; } = new();
	public NoitaBool mInvisible { get; set; } = new();
	public NoitaInt mCounter { get; set; } = new();
	public NoitaInt mCooldown { get; set; } = new();
	public NoitaBool mIsExtension { get; set; } = new();
	public NoitaBool mIsSpent { get; set; } = new();

    public void Read(NoitaStream s){
		Deleted.Read(s);
		Enabled.Read(s);
		Tags.Read(s);
		effect.Read(s);
		custom_effect_id.Read(s);
		frames.Read(s);
		exclusivity_group.Read(s);
		report_block_msg.Read(s);
		disable_movement.Read(s);
		ragdoll_effect.Read(s);
		ragdoll_material.Read(s);
		ragdoll_effect_custom_entity_file.Read(s);
		ragdoll_fx_custom_entity_apply_only_to_largest_body.Read(s);
		polymorph_target.Read(s);
		mSerializedData.Read(s);
		mCaster.Read(s);
		mCasterHerdId.Read(s);
		teleportation_probability.Read(s);
		teleportation_delay_min_frames.Read(s);
		teleportation_radius_min.Read(s);
		teleportation_radius_max.Read(s);
		teleportations_num.Read(s);
		no_heal_max_hp_cap.Read(s);
		causing_status_effect.Read(s);
		caused_by_ingestion_status_effect.Read(s);
		caused_by_stains.Read(s);
		mCharmDisabledCameraBound.Read(s);
		mCharmEnabledTeleporting.Read(s);
		mInvisible.Read(s);
		mCounter.Read(s);
		mCooldown.Read(s);
		mIsExtension.Read(s);
		mIsSpent.Read(s);

    }
    public void Write(NoitaStream s){
		Deleted.Write(s);
		Enabled.Write(s);
		Tags.Write(s);
		effect.Write(s);
		custom_effect_id.Write(s);
		frames.Write(s);
		exclusivity_group.Write(s);
		report_block_msg.Write(s);
		disable_movement.Write(s);
		ragdoll_effect.Write(s);
		ragdoll_material.Write(s);
		ragdoll_effect_custom_entity_file.Write(s);
		ragdoll_fx_custom_entity_apply_only_to_largest_body.Write(s);
		polymorph_target.Write(s);
		mSerializedData.Write(s);
		mCaster.Write(s);
		mCasterHerdId.Write(s);
		teleportation_probability.Write(s);
		teleportation_delay_min_frames.Write(s);
		teleportation_radius_min.Write(s);
		teleportation_radius_max.Write(s);
		teleportations_num.Write(s);
		no_heal_max_hp_cap.Write(s);
		causing_status_effect.Write(s);
		caused_by_ingestion_status_effect.Write(s);
		caused_by_stains.Write(s);
		mCharmDisabledCameraBound.Write(s);
		mCharmEnabledTeleporting.Write(s);
		mInvisible.Write(s);
		mCounter.Write(s);
		mCooldown.Write(s);
		mIsExtension.Write(s);
		mIsSpent.Write(s);

    }
}