namespace GeneratedNoitaClasses;
public class ItemComponent : NoitaComponentBase,  iNoitaType<ItemComponent>{
	public NoitaBool Deleted { get; set; } = new();
	public NoitaBool Enabled { get; set; } = new();
	public NoitaString Tags { get; set; } = new();
	public NoitaString item_name { get; set; } = new();
	public NoitaBool is_stackable { get; set; } = new();
	public NoitaBool is_consumable { get; set; } = new();
	public NoitaBool stats_count_as_item_pick_up { get; set; } = new();
	public NoitaBool auto_pickup { get; set; } = new();
	public NoitaBool permanently_attached { get; set; } = new();
	public NoitaInt uses_remaining { get; set; } = new();
	public NoitaBool is_identified { get; set; } = new();
	public NoitaBool is_frozen { get; set; } = new();
	public NoitaBool collect_nondefault_actions { get; set; } = new();
	public NoitaBool remove_on_death { get; set; } = new();
	public NoitaBool remove_on_death_if_empty { get; set; } = new();
	public NoitaBool remove_default_child_actions_on_death { get; set; } = new();
	public NoitaBool play_hover_animation { get; set; } = new();
	public NoitaBool play_spinning_animation { get; set; } = new();
	public NoitaBool is_equipable_forced { get; set; } = new();
	public NoitaBool play_pick_sound { get; set; } = new();
	public NoitaBool drinkable { get; set; } = new();
	public NoitaCVector2<NoitaFloat> spawn_pos { get; set; } = new();
	public NoitaInt max_child_items { get; set; } = new();
	public NoitaString ui_sprite { get; set; } = new();
	public NoitaString ui_description { get; set; } = new();
	public NoitaUInt preferred_inventory { get; set; } = new();
	public NoitaBool enable_orb_hacks { get; set; } = new();
	public NoitaBool is_all_spells_book { get; set; } = new();
	public NoitaBool always_use_item_name_in_ui { get; set; } = new();
	public NoitaString custom_pickup_string { get; set; } = new();
	public NoitaBool ui_display_description_on_pick_up_hint { get; set; } = new();
	public NoitaCVector2<NoitaInt> inventory_slot { get; set; } = new();
	public NoitaInt next_frame_pickable { get; set; } = new();
	public NoitaInt npc_next_frame_pickable { get; set; } = new();
	public NoitaBool is_pickable { get; set; } = new();
	public NoitaBool is_hittable_always { get; set; } = new();
	public NoitaFloat item_pickup_radius { get; set; } = new();
	public NoitaFloat camera_max_distance { get; set; } = new();
	public NoitaFloat camera_smooth_speed_multiplier { get; set; } = new();
	public NoitaBool has_been_picked_by_player { get; set; } = new();
	public NoitaInt mFramePickedUp { get; set; } = new();

    public void Read(NoitaStream s){
		Deleted.Read(s);
		Enabled.Read(s);
		Tags.Read(s);
		item_name.Read(s);
		is_stackable.Read(s);
		is_consumable.Read(s);
		stats_count_as_item_pick_up.Read(s);
		auto_pickup.Read(s);
		permanently_attached.Read(s);
		uses_remaining.Read(s);
		is_identified.Read(s);
		is_frozen.Read(s);
		collect_nondefault_actions.Read(s);
		remove_on_death.Read(s);
		remove_on_death_if_empty.Read(s);
		remove_default_child_actions_on_death.Read(s);
		play_hover_animation.Read(s);
		play_spinning_animation.Read(s);
		is_equipable_forced.Read(s);
		play_pick_sound.Read(s);
		drinkable.Read(s);
		spawn_pos.Read(s);
		max_child_items.Read(s);
		ui_sprite.Read(s);
		ui_description.Read(s);
		preferred_inventory.Read(s);
		enable_orb_hacks.Read(s);
		is_all_spells_book.Read(s);
		always_use_item_name_in_ui.Read(s);
		custom_pickup_string.Read(s);
		ui_display_description_on_pick_up_hint.Read(s);
		inventory_slot.Read(s);
		next_frame_pickable.Read(s);
		npc_next_frame_pickable.Read(s);
		is_pickable.Read(s);
		is_hittable_always.Read(s);
		item_pickup_radius.Read(s);
		camera_max_distance.Read(s);
		camera_smooth_speed_multiplier.Read(s);
		has_been_picked_by_player.Read(s);
		mFramePickedUp.Read(s);

    }
    public void Write(NoitaStream s){
		Deleted.Write(s);
		Enabled.Write(s);
		Tags.Write(s);
		item_name.Write(s);
		is_stackable.Write(s);
		is_consumable.Write(s);
		stats_count_as_item_pick_up.Write(s);
		auto_pickup.Write(s);
		permanently_attached.Write(s);
		uses_remaining.Write(s);
		is_identified.Write(s);
		is_frozen.Write(s);
		collect_nondefault_actions.Write(s);
		remove_on_death.Write(s);
		remove_on_death_if_empty.Write(s);
		remove_default_child_actions_on_death.Write(s);
		play_hover_animation.Write(s);
		play_spinning_animation.Write(s);
		is_equipable_forced.Write(s);
		play_pick_sound.Write(s);
		drinkable.Write(s);
		spawn_pos.Write(s);
		max_child_items.Write(s);
		ui_sprite.Write(s);
		ui_description.Write(s);
		preferred_inventory.Write(s);
		enable_orb_hacks.Write(s);
		is_all_spells_book.Write(s);
		always_use_item_name_in_ui.Write(s);
		custom_pickup_string.Write(s);
		ui_display_description_on_pick_up_hint.Write(s);
		inventory_slot.Write(s);
		next_frame_pickable.Write(s);
		npc_next_frame_pickable.Write(s);
		is_pickable.Write(s);
		is_hittable_always.Write(s);
		item_pickup_radius.Write(s);
		camera_max_distance.Write(s);
		camera_smooth_speed_multiplier.Write(s);
		has_been_picked_by_player.Write(s);
		mFramePickedUp.Write(s);

    }
}