namespace GeneratedNoitaClasses;
public class LuaComponent : NoitaComponentBase,  iNoitaType<LuaComponent>{
	public NoitaBool Deleted { get; set; } = new();
	public NoitaBool Enabled { get; set; } = new();
	public NoitaString Tags { get; set; } = new();
	public NoitaString script_source_file { get; set; } = new();
	public NoitaUInt vm_type { get; set; } = new();
	public NoitaBool execute_on_added { get; set; } = new();
	public NoitaBool execute_on_removed { get; set; } = new();
	public NoitaInt execute_every_n_frame { get; set; } = new();
	public NoitaInt execute_times { get; set; } = new();
	public NoitaInt limit_how_many_times_per_frame { get; set; } = new();
	public NoitaInt limit_to_every_n_frame { get; set; } = new();
	public NoitaBool limit_all_callbacks { get; set; } = new();
	public NoitaBool remove_after_executed { get; set; } = new();
	public NoitaBool enable_coroutines { get; set; } = new();
	public NoitaBool call_init_function { get; set; } = new();
	public NoitaString script_enabled_changed { get; set; } = new();
	public NoitaString script_damage_received { get; set; } = new();
	public NoitaString script_damage_about_to_be_received { get; set; } = new();
	public NoitaString script_item_picked_up { get; set; } = new();
	public NoitaString script_shot { get; set; } = new();
	public NoitaString script_collision_trigger_hit { get; set; } = new();
	public NoitaString script_collision_trigger_timer_finished { get; set; } = new();
	public NoitaString script_physics_body_modified { get; set; } = new();
	public NoitaString script_pressure_plate_change { get; set; } = new();
	public NoitaString script_inhaled_material { get; set; } = new();
	public NoitaString script_death { get; set; } = new();
	public NoitaString script_throw_item { get; set; } = new();
	public NoitaString script_material_area_checker_failed { get; set; } = new();
	public NoitaString script_material_area_checker_success { get; set; } = new();
	public NoitaString script_electricity_receiver_switched { get; set; } = new();
	public NoitaString script_electricity_receiver_electrified { get; set; } = new();
	public NoitaString script_kick { get; set; } = new();
	public NoitaString script_interacting { get; set; } = new();
	public NoitaString script_audio_event_dead { get; set; } = new();
	public NoitaString script_wand_fired { get; set; } = new();
	public NoitaString script_teleported { get; set; } = new();
	public NoitaString script_portal_teleport_used { get; set; } = new();
	public NoitaString script_polymorphing_to { get; set; } = new();
	public NoitaString script_biome_entered { get; set; } = new();
	public NoitaInt mLastExecutionFrame { get; set; } = new();
	public NoitaInt mTimesExecutedThisFrame { get; set; } = new();
	public NoitaBool mModAppendsDone { get; set; } = new();

    public void Read(NoitaStream s){
		Deleted.Read(s);
		Enabled.Read(s);
		Tags.Read(s);
		script_source_file.Read(s);
		vm_type.Read(s);
		execute_on_added.Read(s);
		execute_on_removed.Read(s);
		execute_every_n_frame.Read(s);
		execute_times.Read(s);
		limit_how_many_times_per_frame.Read(s);
		limit_to_every_n_frame.Read(s);
		limit_all_callbacks.Read(s);
		remove_after_executed.Read(s);
		enable_coroutines.Read(s);
		call_init_function.Read(s);
		script_enabled_changed.Read(s);
		script_damage_received.Read(s);
		script_damage_about_to_be_received.Read(s);
		script_item_picked_up.Read(s);
		script_shot.Read(s);
		script_collision_trigger_hit.Read(s);
		script_collision_trigger_timer_finished.Read(s);
		script_physics_body_modified.Read(s);
		script_pressure_plate_change.Read(s);
		script_inhaled_material.Read(s);
		script_death.Read(s);
		script_throw_item.Read(s);
		script_material_area_checker_failed.Read(s);
		script_material_area_checker_success.Read(s);
		script_electricity_receiver_switched.Read(s);
		script_electricity_receiver_electrified.Read(s);
		script_kick.Read(s);
		script_interacting.Read(s);
		script_audio_event_dead.Read(s);
		script_wand_fired.Read(s);
		script_teleported.Read(s);
		script_portal_teleport_used.Read(s);
		script_polymorphing_to.Read(s);
		script_biome_entered.Read(s);
		mLastExecutionFrame.Read(s);
		mTimesExecutedThisFrame.Read(s);
		mModAppendsDone.Read(s);

    }
    public void Write(NoitaStream s){
		Deleted.Write(s);
		Enabled.Write(s);
		Tags.Write(s);
		script_source_file.Write(s);
		vm_type.Write(s);
		execute_on_added.Write(s);
		execute_on_removed.Write(s);
		execute_every_n_frame.Write(s);
		execute_times.Write(s);
		limit_how_many_times_per_frame.Write(s);
		limit_to_every_n_frame.Write(s);
		limit_all_callbacks.Write(s);
		remove_after_executed.Write(s);
		enable_coroutines.Write(s);
		call_init_function.Write(s);
		script_enabled_changed.Write(s);
		script_damage_received.Write(s);
		script_damage_about_to_be_received.Write(s);
		script_item_picked_up.Write(s);
		script_shot.Write(s);
		script_collision_trigger_hit.Write(s);
		script_collision_trigger_timer_finished.Write(s);
		script_physics_body_modified.Write(s);
		script_pressure_plate_change.Write(s);
		script_inhaled_material.Write(s);
		script_death.Write(s);
		script_throw_item.Write(s);
		script_material_area_checker_failed.Write(s);
		script_material_area_checker_success.Write(s);
		script_electricity_receiver_switched.Write(s);
		script_electricity_receiver_electrified.Write(s);
		script_kick.Write(s);
		script_interacting.Write(s);
		script_audio_event_dead.Write(s);
		script_wand_fired.Write(s);
		script_teleported.Write(s);
		script_portal_teleport_used.Write(s);
		script_polymorphing_to.Write(s);
		script_biome_entered.Write(s);
		mLastExecutionFrame.Write(s);
		mTimesExecutedThisFrame.Write(s);
		mModAppendsDone.Write(s);

    }
}