namespace GeneratedNoitaClasses;
public class ParticleEmitterComponent{
	public string emitted_material_name{ get; set; }
	public bool create_real_particles{ get; set; }
	public bool emit_real_particles{ get; set; }
	public bool emit_cosmetic_particles{ get; set; }
	public bool cosmetic_force_create{ get; set; }
	public bool render_back{ get; set; }
	public bool render_ultrabright{ get; set; }
	public bool collide_with_grid{ get; set; }
	public bool collide_with_gas_and_fire{ get; set; }
	public bool particle_single_width{ get; set; }
	public bool emit_only_if_there_is_space{ get; set; }
	public int emitter_lifetime_frames{ get; set; }
	public bool fire_cells_dont_ignite_damagemodel{ get; set; }
	public bool color_is_based_on_pos{ get; set; }
	public UInt32 color{ get; set; }
	public float custom_alpha{ get; set; }
	public List<float> offset{ get; set; }
	public float x_pos_offset_min{ get; set; }
	public float y_pos_offset_min{ get; set; }
	public float x_pos_offset_max{ get; set; }
	public float y_pos_offset_max{ get; set; }
	public ValueRange area_circle_radius{ get; set; }
	public float area_circle_sector_degrees{ get; set; }
	public float x_vel_min{ get; set; }
	public float x_vel_max{ get; set; }
	public float y_vel_min{ get; set; }
	public float y_vel_max{ get; set; }
	public float direction_random_deg{ get; set; }
	public List<float> gravity{ get; set; }
	public float velocity_always_away_from_center{ get; set; }
	public float lifetime_min{ get; set; }
	public float lifetime_max{ get; set; }
	public float airflow_force{ get; set; }
	public float airflow_time{ get; set; }
	public float airflow_scale{ get; set; }
	public float friction{ get; set; }
	public float attractor_force{ get; set; }
	public int count_min{ get; set; }
	public int count_max{ get; set; }
	public int emission_interval_min_frames{ get; set; }
	public int emission_interval_max_frames{ get; set; }
	public int emission_chance{ get; set; }
	public PARTICLE_EMITTER_CUSTOM_STYLE custom_style{ get; set; }
	public int delay_frames{ get; set; }
	public bool is_emitting{ get; set; }
	public bool use_material_inventory{ get; set; }
	public bool is_trail{ get; set; }
	public float trail_gap{ get; set; }
	public bool render_on_grid{ get; set; }
	public bool fade_based_on_lifetime{ get; set; }
	public bool draw_as_long{ get; set; }
	public float b2_force{ get; set; }
	public bool set_magic_creation{ get; set; }
	public string image_animation_file{ get; set; }
	public string image_animation_colors_file{ get; set; }
	public float image_animation_speed{ get; set; }
	public bool image_animation_loop{ get; set; }
	public float image_animation_phase{ get; set; }
	public float image_animation_emission_probability{ get; set; }
	public bool image_animation_raytrace_from_center{ get; set; }
	public bool image_animation_use_entity_rotation{ get; set; }
	public bool ignore_transform_updated_msg{ get; set; }

}