namespace GeneratedNoitaClasses;
public class PhysicsBodyComponent : NoitaComponentBase,  iNoitaType<PhysicsBodyComponent>{
	public NoitaBool Deleted { get; set; } = new();
	public NoitaBool Enabled { get; set; } = new();
	public NoitaString Tags { get; set; } = new();
	public NoitaBool is_external { get; set; } = new();
	public NoitaBool hax_fix_going_through_ground { get; set; } = new();
	public NoitaBool hax_fix_going_through_sand { get; set; } = new();
	public NoitaBool hax_wait_till_pixel_scenes_loaded { get; set; } = new();
	public NoitaInt uid { get; set; } = new();
	public NoitaBool is_enabled { get; set; } = new();
	public NoitaFloat linear_damping { get; set; } = new();
	public NoitaFloat angular_damping { get; set; } = new();
	public NoitaBool allow_sleep { get; set; } = new();
	public NoitaBool fixed_rotation { get; set; } = new();
	public NoitaFloat buoyancy { get; set; } = new();
	public NoitaFloat gravity_scale_if_has_no_image_shapes { get; set; } = new();
	public NoitaBool is_bullet { get; set; } = new();
	public NoitaBool is_static { get; set; } = new();
	public NoitaBool is_kinematic { get; set; } = new();
	public NoitaBool is_character { get; set; } = new();
	public NoitaBool go_through_sand { get; set; } = new();
	public NoitaBool gridworld_box2d { get; set; } = new();
	public NoitaBool auto_clean { get; set; } = new();
	public NoitaBool on_death_leave_physics_body { get; set; } = new();
	public NoitaBool on_death_really_leave_body { get; set; } = new();
	public NoitaBool update_entity_transform { get; set; } = new();
	public NoitaBool force_add_update_areas { get; set; } = new();
	public NoitaBool kills_entity { get; set; } = new();
	public NoitaBool projectiles_rotate_toward_velocity { get; set; } = new();
	public NoitaCVector2<NoitaFloat> initial_velocity { get; set; } = new();
	public NoitaBool randomize_init_velocity { get; set; } = new();
	public NoitaBool mActiveState { get; set; } = new();

    public void Read(NoitaStream s){
		Deleted.Read(s);
		Enabled.Read(s);
		Tags.Read(s);
		is_external.Read(s);
		hax_fix_going_through_ground.Read(s);
		hax_fix_going_through_sand.Read(s);
		hax_wait_till_pixel_scenes_loaded.Read(s);
		uid.Read(s);
		is_enabled.Read(s);
		linear_damping.Read(s);
		angular_damping.Read(s);
		allow_sleep.Read(s);
		fixed_rotation.Read(s);
		buoyancy.Read(s);
		gravity_scale_if_has_no_image_shapes.Read(s);
		is_bullet.Read(s);
		is_static.Read(s);
		is_kinematic.Read(s);
		is_character.Read(s);
		go_through_sand.Read(s);
		gridworld_box2d.Read(s);
		auto_clean.Read(s);
		on_death_leave_physics_body.Read(s);
		on_death_really_leave_body.Read(s);
		update_entity_transform.Read(s);
		force_add_update_areas.Read(s);
		kills_entity.Read(s);
		projectiles_rotate_toward_velocity.Read(s);
		initial_velocity.Read(s);
		randomize_init_velocity.Read(s);
		mActiveState.Read(s);

    }
    public void Write(NoitaStream s){
		Deleted.Write(s);
		Enabled.Write(s);
		Tags.Write(s);
		is_external.Write(s);
		hax_fix_going_through_ground.Write(s);
		hax_fix_going_through_sand.Write(s);
		hax_wait_till_pixel_scenes_loaded.Write(s);
		uid.Write(s);
		is_enabled.Write(s);
		linear_damping.Write(s);
		angular_damping.Write(s);
		allow_sleep.Write(s);
		fixed_rotation.Write(s);
		buoyancy.Write(s);
		gravity_scale_if_has_no_image_shapes.Write(s);
		is_bullet.Write(s);
		is_static.Write(s);
		is_kinematic.Write(s);
		is_character.Write(s);
		go_through_sand.Write(s);
		gridworld_box2d.Write(s);
		auto_clean.Write(s);
		on_death_leave_physics_body.Write(s);
		on_death_really_leave_body.Write(s);
		update_entity_transform.Write(s);
		force_add_update_areas.Write(s);
		kills_entity.Write(s);
		projectiles_rotate_toward_velocity.Write(s);
		initial_velocity.Write(s);
		randomize_init_velocity.Write(s);
		mActiveState.Write(s);

    }
}