namespace GeneratedNoitaClasses;
public class ProjectileComponent{
	public PROJECTILE_TYPE projectile_type{ get; set; }
	public int lifetime{ get; set; }
	public int lifetime_randomness{ get; set; }
	public bool on_lifetime_out_explode{ get; set; }
	public bool collide_with_world{ get; set; }
	public ConfigGunActionInfo config{ get; set; }
	public float speed_min{ get; set; }
	public float speed_max{ get; set; }
	public float friction{ get; set; }
	public float direction_random_rad{ get; set; }
	public float direction_nonrandom_rad{ get; set; }
	public float lob_min{ get; set; }
	public float lob_max{ get; set; }
	public float camera_shake_when_shot{ get; set; }
	public float shoot_light_flash_radius{ get; set; }
	public UInt32 shoot_light_flash_r{ get; set; }
	public UInt32 shoot_light_flash_g{ get; set; }
	public UInt32 shoot_light_flash_b{ get; set; }
	public bool create_shell_casing{ get; set; }
	public string shell_casing_material{ get; set; }
	public List<float> shell_casing_offset{ get; set; }
	public string muzzle_flash_file{ get; set; }
	public int bounces_left{ get; set; }
	public float bounce_energy{ get; set; }
	public bool bounce_always{ get; set; }
	public bool bounce_at_any_angle{ get; set; }
	public bool attach_to_parent_trigger{ get; set; }
	public string bounce_fx_file{ get; set; }
	public float angular_velocity{ get; set; }
	public bool velocity_sets_rotation{ get; set; }
	public bool velocity_sets_scale{ get; set; }
	public float velocity_sets_scale_coeff{ get; set; }
	public bool velocity_sets_y_flip{ get; set; }
	public float velocity_updates_animation{ get; set; }
	public float ground_penetration_coeff{ get; set; }
	public int ground_penetration_max_durability_to_destroy{ get; set; }
	public string go_through_this_material{ get; set; }
	public bool do_moveto_update{ get; set; }
	public int on_death_duplicate_remaining{ get; set; }
	public bool on_death_gfx_leave_sprite{ get; set; }
	public bool on_death_explode{ get; set; }
	public bool on_death_emit_particle{ get; set; }
	public int on_death_emit_particle_count{ get; set; }
	public bool die_on_liquid_collision{ get; set; }
	public bool die_on_low_velocity{ get; set; }
	public float die_on_low_velocity_limit{ get; set; }
	public string on_death_emit_particle_type{ get; set; }
	public bool on_death_particle_check_concrete{ get; set; }
	public bool ground_collision_fx{ get; set; }
	public bool explosion_dont_damage_shooter{ get; set; }
	public ConfigExplosion config_explosion{ get; set; }
	public float on_death_item_pickable_radius{ get; set; }
	public bool penetrate_world{ get; set; }
	public float penetrate_world_velocity_coeff{ get; set; }
	public bool penetrate_entities{ get; set; }
	public bool on_collision_die{ get; set; }
	public bool on_collision_remove_projectile{ get; set; }
	public bool on_collision_spawn_entity{ get; set; }
	public string spawn_entity{ get; set; }
	public bool spawn_entity_is_projectile{ get; set; }
	public float physics_impulse_coeff{ get; set; }
	public int damage_every_x_frames{ get; set; }
	public bool damage_scaled_by_speed{ get; set; }
	public float damage_scale_max_speed{ get; set; }
	public RAGDOLL_FX ragdoll_fx_on_collision{ get; set; }
	public bool collide_with_entities{ get; set; }
	public string collide_with_tag{ get; set; }
	public string dont_collide_with_tag{ get; set; }
	public int collide_with_shooter_frames{ get; set; }
	public bool friendly_fire{ get; set; }
	public float damage{ get; set; }
	public ConfigDamagesByType damage_by_type{ get; set; }
	public ConfigDamageCritical damage_critical{ get; set; }
	public float knockback_force{ get; set; }
	public float ragdoll_force_multiplier{ get; set; }
	public float hit_particle_force_multiplier{ get; set; }
	public float blood_count_multiplier{ get; set; }
	public string damage_game_effect_entities{ get; set; }
	public bool never_hit_player{ get; set; }
	public bool collect_materials_to_shooter{ get; set; }
	public bool play_damage_sounds{ get; set; }
	public int mLastFrameDamaged{ get; set; }

}