namespace GeneratedNoitaClasses;
public class ProjectileComponent : NoitaComponentBase,  iNoitaType<ProjectileComponent>{
	public NoitaBool Deleted { get; set; } = new();
	public NoitaBool Enabled { get; set; } = new();
	public NoitaString Tags { get; set; } = new();
	public NoitaUInt projectile_type { get; set; } = new();
	public NoitaInt lifetime { get; set; } = new();
	public NoitaInt lifetime_randomness { get; set; } = new();
	public NoitaBool on_lifetime_out_explode { get; set; } = new();
	public NoitaBool collide_with_world { get; set; } = new();
	public ConfigGunActionInfo config { get; set; } = new();
	public NoitaFloat speed_min { get; set; } = new();
	public NoitaFloat speed_max { get; set; } = new();
	public NoitaFloat friction { get; set; } = new();
	public NoitaFloat direction_random_rad { get; set; } = new();
	public NoitaFloat direction_nonrandom_rad { get; set; } = new();
	public NoitaFloat lob_min { get; set; } = new();
	public NoitaFloat lob_max { get; set; } = new();
	public NoitaFloat camera_shake_when_shot { get; set; } = new();
	public NoitaFloat shoot_light_flash_radius { get; set; } = new();
	public NoitaUInt shoot_light_flash_r { get; set; } = new();
	public NoitaUInt shoot_light_flash_g { get; set; } = new();
	public NoitaUInt shoot_light_flash_b { get; set; } = new();
	public NoitaBool create_shell_casing { get; set; } = new();
	public NoitaString shell_casing_material { get; set; } = new();
	public NoitaCVector2<NoitaFloat> shell_casing_offset { get; set; } = new();
	public NoitaString muzzle_flash_file { get; set; } = new();
	public NoitaInt bounces_left { get; set; } = new();
	public NoitaFloat bounce_energy { get; set; } = new();
	public NoitaBool bounce_always { get; set; } = new();
	public NoitaBool bounce_at_any_angle { get; set; } = new();
	public NoitaBool attach_to_parent_trigger { get; set; } = new();
	public NoitaString bounce_fx_file { get; set; } = new();
	public NoitaFloat angular_velocity { get; set; } = new();
	public NoitaBool velocity_sets_rotation { get; set; } = new();
	public NoitaBool velocity_sets_scale { get; set; } = new();
	public NoitaFloat velocity_sets_scale_coeff { get; set; } = new();
	public NoitaBool velocity_sets_y_flip { get; set; } = new();
	public NoitaFloat velocity_updates_animation { get; set; } = new();
	public NoitaFloat ground_penetration_coeff { get; set; } = new();
	public NoitaInt ground_penetration_max_durability_to_destroy { get; set; } = new();
	public NoitaString go_through_this_material { get; set; } = new();
	public NoitaBool do_moveto_update { get; set; } = new();
	public NoitaInt on_death_duplicate_remaining { get; set; } = new();
	public NoitaBool on_death_gfx_leave_sprite { get; set; } = new();
	public NoitaBool on_death_explode { get; set; } = new();
	public NoitaBool on_death_emit_particle { get; set; } = new();
	public NoitaInt on_death_emit_particle_count { get; set; } = new();
	public NoitaBool die_on_liquid_collision { get; set; } = new();
	public NoitaBool die_on_low_velocity { get; set; } = new();
	public NoitaFloat die_on_low_velocity_limit { get; set; } = new();
	public NoitaString on_death_emit_particle_type { get; set; } = new();
	public NoitaBool on_death_particle_check_concrete { get; set; } = new();
	public NoitaBool ground_collision_fx { get; set; } = new();
	public NoitaBool explosion_dont_damage_shooter { get; set; } = new();
	public ConfigExplosion config_explosion { get; set; } = new();
	public NoitaFloat on_death_item_pickable_radius { get; set; } = new();
	public NoitaBool penetrate_world { get; set; } = new();
	public NoitaFloat penetrate_world_velocity_coeff { get; set; } = new();
	public NoitaBool penetrate_entities { get; set; } = new();
	public NoitaBool on_collision_die { get; set; } = new();
	public NoitaBool on_collision_remove_projectile { get; set; } = new();
	public NoitaBool on_collision_spawn_entity { get; set; } = new();
	public NoitaString spawn_entity { get; set; } = new();
	public NoitaBool spawn_entity_is_projectile { get; set; } = new();
	public NoitaFloat physics_impulse_coeff { get; set; } = new();
	public NoitaInt damage_every_x_frames { get; set; } = new();
	public NoitaBool damage_scaled_by_speed { get; set; } = new();
	public NoitaFloat damage_scale_max_speed { get; set; } = new();
	public NoitaUInt ragdoll_fx_on_collision { get; set; } = new();
	public NoitaBool collide_with_entities { get; set; } = new();
	public NoitaString collide_with_tag { get; set; } = new();
	public NoitaString dont_collide_with_tag { get; set; } = new();
	public NoitaInt collide_with_shooter_frames { get; set; } = new();
	public NoitaBool friendly_fire { get; set; } = new();
	public NoitaFloat damage { get; set; } = new();
	public ConfigDamagesByType damage_by_type { get; set; } = new();
	public ConfigDamageCritical damage_critical { get; set; } = new();
	public NoitaFloat knockback_force { get; set; } = new();
	public NoitaFloat ragdoll_force_multiplier { get; set; } = new();
	public NoitaFloat hit_particle_force_multiplier { get; set; } = new();
	public NoitaFloat blood_count_multiplier { get; set; } = new();
	public NoitaString damage_game_effect_entities { get; set; } = new();
	public NoitaBool never_hit_player { get; set; } = new();
	public NoitaBool collect_materials_to_shooter { get; set; } = new();
	public NoitaBool play_damage_sounds { get; set; } = new();
	public NoitaInt mLastFrameDamaged { get; set; } = new();

    public void Read(NoitaStream s){
		Deleted.Read(s);
		Enabled.Read(s);
		Tags.Read(s);
		projectile_type.Read(s);
		lifetime.Read(s);
		lifetime_randomness.Read(s);
		on_lifetime_out_explode.Read(s);
		collide_with_world.Read(s);
		config.Read(s);
		speed_min.Read(s);
		speed_max.Read(s);
		friction.Read(s);
		direction_random_rad.Read(s);
		direction_nonrandom_rad.Read(s);
		lob_min.Read(s);
		lob_max.Read(s);
		camera_shake_when_shot.Read(s);
		shoot_light_flash_radius.Read(s);
		shoot_light_flash_r.Read(s);
		shoot_light_flash_g.Read(s);
		shoot_light_flash_b.Read(s);
		create_shell_casing.Read(s);
		shell_casing_material.Read(s);
		shell_casing_offset.Read(s);
		muzzle_flash_file.Read(s);
		bounces_left.Read(s);
		bounce_energy.Read(s);
		bounce_always.Read(s);
		bounce_at_any_angle.Read(s);
		attach_to_parent_trigger.Read(s);
		bounce_fx_file.Read(s);
		angular_velocity.Read(s);
		velocity_sets_rotation.Read(s);
		velocity_sets_scale.Read(s);
		velocity_sets_scale_coeff.Read(s);
		velocity_sets_y_flip.Read(s);
		velocity_updates_animation.Read(s);
		ground_penetration_coeff.Read(s);
		ground_penetration_max_durability_to_destroy.Read(s);
		go_through_this_material.Read(s);
		do_moveto_update.Read(s);
		on_death_duplicate_remaining.Read(s);
		on_death_gfx_leave_sprite.Read(s);
		on_death_explode.Read(s);
		on_death_emit_particle.Read(s);
		on_death_emit_particle_count.Read(s);
		die_on_liquid_collision.Read(s);
		die_on_low_velocity.Read(s);
		die_on_low_velocity_limit.Read(s);
		on_death_emit_particle_type.Read(s);
		on_death_particle_check_concrete.Read(s);
		ground_collision_fx.Read(s);
		explosion_dont_damage_shooter.Read(s);
		config_explosion.Read(s);
		on_death_item_pickable_radius.Read(s);
		penetrate_world.Read(s);
		penetrate_world_velocity_coeff.Read(s);
		penetrate_entities.Read(s);
		on_collision_die.Read(s);
		on_collision_remove_projectile.Read(s);
		on_collision_spawn_entity.Read(s);
		spawn_entity.Read(s);
		spawn_entity_is_projectile.Read(s);
		physics_impulse_coeff.Read(s);
		damage_every_x_frames.Read(s);
		damage_scaled_by_speed.Read(s);
		damage_scale_max_speed.Read(s);
		ragdoll_fx_on_collision.Read(s);
		collide_with_entities.Read(s);
		collide_with_tag.Read(s);
		dont_collide_with_tag.Read(s);
		collide_with_shooter_frames.Read(s);
		friendly_fire.Read(s);
		damage.Read(s);
		damage_by_type.Read(s);
		damage_critical.Read(s);
		knockback_force.Read(s);
		ragdoll_force_multiplier.Read(s);
		hit_particle_force_multiplier.Read(s);
		blood_count_multiplier.Read(s);
		damage_game_effect_entities.Read(s);
		never_hit_player.Read(s);
		collect_materials_to_shooter.Read(s);
		play_damage_sounds.Read(s);
		mLastFrameDamaged.Read(s);

    }
    public void Write(NoitaStream s){
		Deleted.Write(s);
		Enabled.Write(s);
		Tags.Write(s);
		projectile_type.Write(s);
		lifetime.Write(s);
		lifetime_randomness.Write(s);
		on_lifetime_out_explode.Write(s);
		collide_with_world.Write(s);
		config.Write(s);
		speed_min.Write(s);
		speed_max.Write(s);
		friction.Write(s);
		direction_random_rad.Write(s);
		direction_nonrandom_rad.Write(s);
		lob_min.Write(s);
		lob_max.Write(s);
		camera_shake_when_shot.Write(s);
		shoot_light_flash_radius.Write(s);
		shoot_light_flash_r.Write(s);
		shoot_light_flash_g.Write(s);
		shoot_light_flash_b.Write(s);
		create_shell_casing.Write(s);
		shell_casing_material.Write(s);
		shell_casing_offset.Write(s);
		muzzle_flash_file.Write(s);
		bounces_left.Write(s);
		bounce_energy.Write(s);
		bounce_always.Write(s);
		bounce_at_any_angle.Write(s);
		attach_to_parent_trigger.Write(s);
		bounce_fx_file.Write(s);
		angular_velocity.Write(s);
		velocity_sets_rotation.Write(s);
		velocity_sets_scale.Write(s);
		velocity_sets_scale_coeff.Write(s);
		velocity_sets_y_flip.Write(s);
		velocity_updates_animation.Write(s);
		ground_penetration_coeff.Write(s);
		ground_penetration_max_durability_to_destroy.Write(s);
		go_through_this_material.Write(s);
		do_moveto_update.Write(s);
		on_death_duplicate_remaining.Write(s);
		on_death_gfx_leave_sprite.Write(s);
		on_death_explode.Write(s);
		on_death_emit_particle.Write(s);
		on_death_emit_particle_count.Write(s);
		die_on_liquid_collision.Write(s);
		die_on_low_velocity.Write(s);
		die_on_low_velocity_limit.Write(s);
		on_death_emit_particle_type.Write(s);
		on_death_particle_check_concrete.Write(s);
		ground_collision_fx.Write(s);
		explosion_dont_damage_shooter.Write(s);
		config_explosion.Write(s);
		on_death_item_pickable_radius.Write(s);
		penetrate_world.Write(s);
		penetrate_world_velocity_coeff.Write(s);
		penetrate_entities.Write(s);
		on_collision_die.Write(s);
		on_collision_remove_projectile.Write(s);
		on_collision_spawn_entity.Write(s);
		spawn_entity.Write(s);
		spawn_entity_is_projectile.Write(s);
		physics_impulse_coeff.Write(s);
		damage_every_x_frames.Write(s);
		damage_scaled_by_speed.Write(s);
		damage_scale_max_speed.Write(s);
		ragdoll_fx_on_collision.Write(s);
		collide_with_entities.Write(s);
		collide_with_tag.Write(s);
		dont_collide_with_tag.Write(s);
		collide_with_shooter_frames.Write(s);
		friendly_fire.Write(s);
		damage.Write(s);
		damage_by_type.Write(s);
		damage_critical.Write(s);
		knockback_force.Write(s);
		ragdoll_force_multiplier.Write(s);
		hit_particle_force_multiplier.Write(s);
		blood_count_multiplier.Write(s);
		damage_game_effect_entities.Write(s);
		never_hit_player.Write(s);
		collect_materials_to_shooter.Write(s);
		play_damage_sounds.Write(s);
		mLastFrameDamaged.Write(s);

    }
}