namespace GeneratedNoitaClasses;
public class VerletPhysicsComponent : NoitaComponentBase,  iNoitaType<VerletPhysicsComponent>{
	public NoitaBool Deleted { get; set; } = new();
	public NoitaBool Enabled { get; set; } = new();
	public NoitaString Tags { get; set; } = new();
	public NoitaInt num_points { get; set; } = new();
	public NoitaInt num_links { get; set; } = new();
	public NoitaInt width { get; set; } = new();
	public NoitaUInt type { get; set; } = new();
	public NoitaFloat resting_distance { get; set; } = new();
	public NoitaFloat mass_min { get; set; } = new();
	public NoitaFloat mass_max { get; set; } = new();
	public NoitaFloat stiffness { get; set; } = new();
	public NoitaFloat velocity_dampening { get; set; } = new();
	public NoitaFloat liquid_damping { get; set; } = new();
	public NoitaFloat gets_entity_velocity_coeff { get; set; } = new();
	public NoitaBool collide_with_cells { get; set; } = new();
	public NoitaBool simulate_gravity { get; set; } = new();
	public NoitaBool simulate_wind { get; set; } = new();
	public NoitaFloat wind_change_speed { get; set; } = new();
	public NoitaBool constrain_stretching { get; set; } = new();
	public NoitaBool pixelate_sprite_transforms { get; set; } = new();
	public NoitaBool scale_sprite_x { get; set; } = new();
	public NoitaBool follow_entity_transform { get; set; } = new();
	public NoitaCVector2<NoitaFloat> animation_target_offset { get; set; } = new();
	public NoitaFloat animation_amount { get; set; } = new();
	public NoitaFloat animation_speed { get; set; } = new();
	public NoitaFloat animation_energy { get; set; } = new();
	public NoitaFloat cloth_sprite_z_index { get; set; } = new();
	public NoitaInt stain_cells_probability { get; set; } = new();
	public NoitaUInt cloth_color_edge { get; set; } = new();
	public NoitaUInt cloth_color { get; set; } = new();
	public NoitaCVector2<NoitaFloat> m_position_previous { get; set; } = new();
	public NoitaBool m_is_culled_previous { get; set; } = new();
	public NoitaUintArrayInline colors { get; set; } = new();
	public NoitaUintArrayInline materials { get; set; } = new();

    public void Read(NoitaStream s){
		Deleted.Read(s);
		Enabled.Read(s);
		Tags.Read(s);
		num_points.Read(s);
		num_links.Read(s);
		width.Read(s);
		type.Read(s);
		resting_distance.Read(s);
		mass_min.Read(s);
		mass_max.Read(s);
		stiffness.Read(s);
		velocity_dampening.Read(s);
		liquid_damping.Read(s);
		gets_entity_velocity_coeff.Read(s);
		collide_with_cells.Read(s);
		simulate_gravity.Read(s);
		simulate_wind.Read(s);
		wind_change_speed.Read(s);
		constrain_stretching.Read(s);
		pixelate_sprite_transforms.Read(s);
		scale_sprite_x.Read(s);
		follow_entity_transform.Read(s);
		animation_target_offset.Read(s);
		animation_amount.Read(s);
		animation_speed.Read(s);
		animation_energy.Read(s);
		cloth_sprite_z_index.Read(s);
		stain_cells_probability.Read(s);
		cloth_color_edge.Read(s);
		cloth_color.Read(s);
		m_position_previous.Read(s);
		m_is_culled_previous.Read(s);
		colors.Read(s);
		materials.Read(s);

    }
    public void Write(NoitaStream s){
		Deleted.Write(s);
		Enabled.Write(s);
		Tags.Write(s);
		num_points.Write(s);
		num_links.Write(s);
		width.Write(s);
		type.Write(s);
		resting_distance.Write(s);
		mass_min.Write(s);
		mass_max.Write(s);
		stiffness.Write(s);
		velocity_dampening.Write(s);
		liquid_damping.Write(s);
		gets_entity_velocity_coeff.Write(s);
		collide_with_cells.Write(s);
		simulate_gravity.Write(s);
		simulate_wind.Write(s);
		wind_change_speed.Write(s);
		constrain_stretching.Write(s);
		pixelate_sprite_transforms.Write(s);
		scale_sprite_x.Write(s);
		follow_entity_transform.Write(s);
		animation_target_offset.Write(s);
		animation_amount.Write(s);
		animation_speed.Write(s);
		animation_energy.Write(s);
		cloth_sprite_z_index.Write(s);
		stain_cells_probability.Write(s);
		cloth_color_edge.Write(s);
		cloth_color.Write(s);
		m_position_previous.Write(s);
		m_is_culled_previous.Write(s);
		colors.Write(s);
		materials.Write(s);

    }
}