namespace GeneratedNoitaClasses;
public class WorldStateComponent : NoitaComponentBase,  iNoitaType<WorldStateComponent>{
	public NoitaBool Deleted { get; set; } = new();
	public NoitaBool Enabled { get; set; } = new();
	public NoitaString Tags { get; set; } = new();
	public NoitaBool is_initialized { get; set; } = new();
	public NoitaFloat time { get; set; } = new();
	public NoitaFloat time_total { get; set; } = new();
	public NoitaFloat time_dt { get; set; } = new();
	public NoitaInt day_count { get; set; } = new();
	public NoitaFloat rain { get; set; } = new();
	public NoitaFloat rain_target { get; set; } = new();
	public NoitaFloat fog { get; set; } = new();
	public NoitaFloat fog_target { get; set; } = new();
	public NoitaBool intro_weather { get; set; } = new();
	public NoitaFloat wind { get; set; } = new();
	public NoitaFloat wind_speed { get; set; } = new();
	public NoitaFloat wind_speed_sin_t { get; set; } = new();
	public NoitaFloat wind_speed_sin { get; set; } = new();
	public NoitaFloat clouds_01_target { get; set; } = new();
	public NoitaFloat clouds_02_target { get; set; } = new();
	public NoitaFloat gradient_sky_alpha_target { get; set; } = new();
	public NoitaFloat sky_sunset_alpha_target { get; set; } = new();
	public NoitaInt lightning_count { get; set; } = new();
	public NoitaCVector2<NoitaFloat> player_spawn_location { get; set; } = new();
	
	public NoitaVector<MissingClassConfigPendingPortal> pending_portals { get; set; } = new();
	public NoitaUInt next_portal_id { get; set; } = new();
	public NoitaVector<NoitaInt> apparitions_per_level { get; set; } = new();
	public NoitaVector<MissingClassConfigNpcParty> npc_parties { get; set; } = new();
	public NoitaString session_stat_file { get; set; } = new();
	public NoitaVector<NoitaInt> orbs_found_thisrun { get; set; } = new();
	public NoitaVector<NoitaString> flags { get; set; } = new();
	public NoitaVector<NoitaString> changed_materials { get; set; } = new();
	public NoitaInt player_polymorph_count { get; set; } = new();
	public NoitaInt player_polymorph_random_count { get; set; } = new();
	public NoitaInt player_did_infinite_spell_count { get; set; } = new();
	public NoitaInt player_did_damage_over_1milj { get; set; } = new();
	public NoitaInt player_living_with_minus_hp { get; set; } = new();
	public NoitaFloat global_genome_relations_modifier { get; set; } = new();
	public NoitaBool mods_have_been_active_during_this_run { get; set; } = new();
	public NoitaBool twitch_has_been_active_during_this_run { get; set; } = new();
	public NoitaUInt next_cut_through_world_id { get; set; } = new();
	public NoitaVector<MissingClassConfigCutThroughWorld> cuts_through_world { get; set; } = new();
	public NoitaLensValue<NoitaInt> gore_multiplier { get; set; } = new();
	public NoitaLensValue<NoitaInt> trick_kill_gold_multiplier { get; set; } = new();
	public NoitaLensValue<NoitaFloat> damage_flash_multiplier { get; set; } = new();
	public NoitaLensValue<NoitaBool> open_fog_of_war_everywhere { get; set; } = new();
	public NoitaLensValue<NoitaBool> consume_actions { get; set; } = new();
	public NoitaBool perk_infinite_spells { get; set; } = new();
	public NoitaBool perk_trick_kills_blood_money { get; set; } = new();
	public NoitaInt perk_hp_drop_chance { get; set; } = new();
	public NoitaBool perk_gold_is_forever { get; set; } = new();
	public NoitaBool perk_rats_player_friendly { get; set; } = new();
	public NoitaBool EVERYTHING_TO_GOLD { get; set; } = new();
	public NoitaString material_everything_to_gold { get; set; } = new();
	public NoitaString material_everything_to_gold_static { get; set; } = new();
	public NoitaBool INFINITE_GOLD_HAPPENING { get; set; } = new();
	public NoitaBool ENDING_HAPPINESS_HAPPENING { get; set; } = new();
	public NoitaInt ENDING_HAPPINESS_FRAMES { get; set; } = new();
	public NoitaBool ENDING_HAPPINESS { get; set; } = new();
	public NoitaFloat mFlashAlpha { get; set; } = new();
	public NoitaInt DEBUG_LOADED_FROM_AUTOSAVE { get; set; } = new();
	public NoitaInt DEBUG_LOADED_FROM_OLD_VERSION { get; set; } = new();

    public void Read(NoitaStream s){
		Deleted.Read(s);
		Enabled.Read(s);
		Tags.Read(s);
		is_initialized.Read(s);
		time.Read(s);
		time_total.Read(s);
		time_dt.Read(s);
		day_count.Read(s);
		rain.Read(s);
		rain_target.Read(s);
		fog.Read(s);
		fog_target.Read(s);
		intro_weather.Read(s);
		wind.Read(s);
		wind_speed.Read(s);
		wind_speed_sin_t.Read(s);
		wind_speed_sin.Read(s);
		clouds_01_target.Read(s);
		clouds_02_target.Read(s);
		gradient_sky_alpha_target.Read(s);
		sky_sunset_alpha_target.Read(s);
		lightning_count.Read(s);
		player_spawn_location.Read(s);
		
		pending_portals.Read(s);
		next_portal_id.Read(s);
		apparitions_per_level.Read(s);
		npc_parties.Read(s);
		session_stat_file.Read(s);
		orbs_found_thisrun.Read(s);
		flags.Read(s);
		changed_materials.Read(s);
		player_polymorph_count.Read(s);
		player_polymorph_random_count.Read(s);
		player_did_infinite_spell_count.Read(s);
		player_did_damage_over_1milj.Read(s);
		player_living_with_minus_hp.Read(s);
		global_genome_relations_modifier.Read(s);
		mods_have_been_active_during_this_run.Read(s);
		twitch_has_been_active_during_this_run.Read(s);
		next_cut_through_world_id.Read(s);
		cuts_through_world.Read(s);
		gore_multiplier.Read(s);
		trick_kill_gold_multiplier.Read(s);
		damage_flash_multiplier.Read(s);
		open_fog_of_war_everywhere.Read(s);
		consume_actions.Read(s);
		perk_infinite_spells.Read(s);
		perk_trick_kills_blood_money.Read(s);
		perk_hp_drop_chance.Read(s);
		perk_gold_is_forever.Read(s);
		perk_rats_player_friendly.Read(s);
		EVERYTHING_TO_GOLD.Read(s);
		material_everything_to_gold.Read(s);
		material_everything_to_gold_static.Read(s);
		INFINITE_GOLD_HAPPENING.Read(s);
		ENDING_HAPPINESS_HAPPENING.Read(s);
		ENDING_HAPPINESS_FRAMES.Read(s);
		ENDING_HAPPINESS.Read(s);
		mFlashAlpha.Read(s);
		DEBUG_LOADED_FROM_AUTOSAVE.Read(s);
		DEBUG_LOADED_FROM_OLD_VERSION.Read(s);

    }
    public void Write(NoitaStream s){
		Deleted.Write(s);
		Enabled.Write(s);
		Tags.Write(s);
		is_initialized.Write(s);
		time.Write(s);
		time_total.Write(s);
		time_dt.Write(s);
		day_count.Write(s);
		rain.Write(s);
		rain_target.Write(s);
		fog.Write(s);
		fog_target.Write(s);
		intro_weather.Write(s);
		wind.Write(s);
		wind_speed.Write(s);
		wind_speed_sin_t.Write(s);
		wind_speed_sin.Write(s);
		clouds_01_target.Write(s);
		clouds_02_target.Write(s);
		gradient_sky_alpha_target.Write(s);
		sky_sunset_alpha_target.Write(s);
		lightning_count.Write(s);
		player_spawn_location.Write(s);
		
		pending_portals.Write(s);
		next_portal_id.Write(s);
		apparitions_per_level.Write(s);
		npc_parties.Write(s);
		session_stat_file.Write(s);
		orbs_found_thisrun.Write(s);
		flags.Write(s);
		changed_materials.Write(s);
		player_polymorph_count.Write(s);
		player_polymorph_random_count.Write(s);
		player_did_infinite_spell_count.Write(s);
		player_did_damage_over_1milj.Write(s);
		player_living_with_minus_hp.Write(s);
		global_genome_relations_modifier.Write(s);
		mods_have_been_active_during_this_run.Write(s);
		twitch_has_been_active_during_this_run.Write(s);
		next_cut_through_world_id.Write(s);
		cuts_through_world.Write(s);
		gore_multiplier.Write(s);
		trick_kill_gold_multiplier.Write(s);
		damage_flash_multiplier.Write(s);
		open_fog_of_war_everywhere.Write(s);
		consume_actions.Write(s);
		perk_infinite_spells.Write(s);
		perk_trick_kills_blood_money.Write(s);
		perk_hp_drop_chance.Write(s);
		perk_gold_is_forever.Write(s);
		perk_rats_player_friendly.Write(s);
		EVERYTHING_TO_GOLD.Write(s);
		material_everything_to_gold.Write(s);
		material_everything_to_gold_static.Write(s);
		INFINITE_GOLD_HAPPENING.Write(s);
		ENDING_HAPPINESS_HAPPENING.Write(s);
		ENDING_HAPPINESS_FRAMES.Write(s);
		ENDING_HAPPINESS.Write(s);
		mFlashAlpha.Write(s);
		DEBUG_LOADED_FROM_AUTOSAVE.Write(s);
		DEBUG_LOADED_FROM_OLD_VERSION.Write(s);

    }
}